/**
 * 旅行の教材 レベル1（2026-10-09 かずき決定・9-2）
 *
 * - 対象：初めて日本へ行く人（N5 くらい）
 * - 5場面：空港／ホテル／レストラン／買い物／電車と道を聞く
 * - 1場面＝フレーズ・使う場面・会話・穴埋め（2026-10-04 の決定）
 * - よみは教科書と同じ「漢字（かんじ）」の形。英語の訳を付ける（2026-10-09 かずき決定）
 * - 中身は Claude が書き、あいちゃんに見てもらって直す・増やす
 * 型と並べ方は lib/travel.ts
 */
import type { TravelScene } from '@/lib/travel';

export const TRAVEL_LEVEL1: TravelScene[] = [
    {
        id: 'airport',
        title: '空港（くうこう）',
        subtitle: '入国（にゅうこく）と荷物（にもつ）',
        titleEn: 'Airport: immigration and baggage',
        goal: { ja: '入国審査（にゅうこくしんさ）で、旅行（りょこう）の目的（もくてき）と日数（にっすう）を言（い）える。荷物（にもつ）の場所（ばしょ）を聞（き）ける。', en: 'Answer the purpose and length of your stay at immigration, and ask where your baggage is.' },
        phrases: [
            { ja: '観光（かんこう）です。', en: 'It’s for sightseeing.' },
            { ja: '一週間（いっしゅうかん）います。', en: 'I’ll stay for one week.' },
            { ja: 'ホテルに泊（と）まります。', en: 'I’ll stay at a hotel.' },
            { ja: '荷物（にもつ）はどこですか。', en: 'Where is the baggage?' },
            { ja: 'わたしのスーツケースがありません。', en: 'My suitcase isn’t here.' },
            { ja: '両替（りょうがえ）はどこですか。', en: 'Where can I exchange money?' },
            { ja: '電車（でんしゃ）の切符（きっぷ）はどこで買（か）いますか。', en: 'Where do I buy a train ticket?' },
            { ja: 'すみません、もう一度（いちど）お願（ねが）いします。', en: 'Sorry, could you say that again, please?' },
        ],
        usage: [
            { ja: '入国審査（にゅうこくしんさ）では、旅行（りょこう）の目的（もくてき）と日数（にっすう）をよく聞（き）かれます。「観光（かんこう）です」「一週間（いっしゅうかん）います」と短（みじか）く答（こた）えれば大丈夫（だいじょうぶ）です。', en: 'At immigration you are often asked your purpose and length of stay. Short answers like “Sightseeing” and “One week” are fine.' },
            { ja: 'パスポートを渡（わた）す時（とき）は「お願（ねが）いします」と言（い）いましょう。', en: 'Say “onegaishimasu” when you hand over your passport.' },
            { ja: '聞（き）き取（と）れない時（とき）は「もう一度（いちど）お願（ねが）いします」と言（い）えば、もう一度（いちど）言（い）ってくれます。', en: 'If you can’t catch something, say “mō ichido onegaishimasu” and they will repeat it.' },
        ],
        dialogue: [
            { speaker: '係員（かかりいん）', ja: 'パスポートをお願（ねが）いします。', en: 'Your passport, please.' },
            { speaker: '旅行者（りょこうしゃ）', ja: 'はい、お願（ねが）いします。', en: 'Here you are.' },
            { speaker: '係員（かかりいん）', ja: '旅行（りょこう）の目的（もくてき）は何（なん）ですか。', en: 'What is the purpose of your trip?' },
            { speaker: '旅行者（りょこうしゃ）', ja: '観光（かんこう）です。', en: 'Sightseeing.' },
            { speaker: '係員（かかりいん）', ja: '何日（なんにち）いますか。', en: 'How many days will you stay?' },
            { speaker: '旅行者（りょこうしゃ）', ja: '一週間（いっしゅうかん）います。', en: 'One week.' },
            { speaker: '係員（かかりいん）', ja: 'どこに泊（と）まりますか。', en: 'Where will you stay?' },
            { speaker: '旅行者（りょこうしゃ）', ja: '東京（とうきょう）のホテルに泊（と）まります。', en: 'At a hotel in Tokyo.' },
            { speaker: '係員（かかりいん）', ja: 'はい、どうぞ。', en: 'All right, go ahead.' },
            { speaker: '旅行者（りょこうしゃ）', ja: 'ありがとうございます。', en: 'Thank you.' },
        ],
        blanks: [
            { q: '旅行（りょこう）の目的（もくてき）は（　　）です。', answer: '観光（かんこう）', en: 'The purpose of my trip is sightseeing.' },
            { q: '一週間（いっしゅうかん）（　　）。', answer: 'います', en: 'I’ll stay for one week.' },
            { q: '荷物（にもつ）は（　　）ですか。', answer: 'どこ', en: 'Where is the baggage?' },
            { q: 'ホテルに（　　）。', answer: '泊（と）まります', en: 'I’ll stay at a hotel.' },
            { q: 'すみません、もう一度（いちど）（　　）。', answer: 'お願（ねが）いします', en: 'Sorry, could you say that again, please?' },
        ],
    },
    {
        id: 'hotel',
        title: 'ホテル',
        subtitle: 'チェックイン',
        titleEn: 'Hotel: checking in',
        goal: { ja: '予約（よやく）の名前（なまえ）を言（い）って、チェックインできる。時間（じかん）や物（もの）について聞（き）ける。', en: 'Check in by giving the name on your reservation, and ask about times and things you need.' },
        phrases: [
            { ja: 'チェックインをお願（ねが）いします。', en: 'I’d like to check in, please.' },
            { ja: '予約（よやく）しています。スミスです。', en: 'I have a reservation. My name is Smith.' },
            { ja: '朝（あさ）ごはんは何時（なんじ）からですか。', en: 'What time does breakfast start?' },
            { ja: 'チェックアウトは何時（なんじ）ですか。', en: 'What time is check-out?' },
            { ja: 'Wi-Fi（ワイファイ）のパスワードは何（なん）ですか。', en: 'What is the Wi-Fi password?' },
            { ja: '荷物（にもつ）を預（あず）かってください。', en: 'Please keep my luggage for me.' },
            { ja: 'タオルをもう一枚（いちまい）ください。', en: 'One more towel, please.' },
            { ja: 'エアコンがつきません。', en: 'The air conditioner doesn’t turn on.' },
        ],
        usage: [
            { ja: '予約（よやく）の名前（なまえ）は、パスポートと同（おな）じ名前（なまえ）を言（い）いましょう。', en: 'Give the same name as on your passport for the reservation.' },
            { ja: 'チェックインの前（まえ）やチェックアウトの後（あと）でも、荷物（にもつ）を預（あず）かってくれるホテルが多（おお）いです。', en: 'Many hotels will keep your luggage before check-in or after check-out.' },
            { ja: '部屋（へや）で困（こま）った時（とき）は「〜がつきません」「〜がありません」で伝（つた）えられます。', en: 'If something is wrong in your room, you can say “… ga tsukimasen” (… doesn’t turn on) or “… ga arimasen” (there is no …).' },
        ],
        dialogue: [
            { speaker: 'フロント', ja: 'いらっしゃいませ。', en: 'Welcome.' },
            { speaker: '旅行者（りょこうしゃ）', ja: 'チェックインをお願（ねが）いします。予約（よやく）しています。', en: 'I’d like to check in. I have a reservation.' },
            { speaker: 'フロント', ja: 'お名前（なまえ）をお願（ねが）いします。', en: 'Your name, please.' },
            { speaker: '旅行者（りょこうしゃ）', ja: 'スミスです。', en: 'It’s Smith.' },
            { speaker: 'フロント', ja: 'スミス様（さま）ですね。パスポートをお願（ねが）いします。', en: 'Mr./Ms. Smith. Your passport, please.' },
            { speaker: '旅行者（りょこうしゃ）', ja: 'はい。朝（あさ）ごはんは何時（なんじ）からですか。', en: 'Here you are. What time does breakfast start?' },
            { speaker: 'フロント', ja: '7時（しちじ）からです。お部屋（へや）は502号室（ごひゃくにごうしつ）です。', en: 'From seven. Your room is number 502.' },
            { speaker: '旅行者（りょこうしゃ）', ja: 'ありがとうございます。', en: 'Thank you.' },
        ],
        blanks: [
            { q: 'チェックインを（　　）。', answer: 'お願（ねが）いします', en: 'I’d like to check in, please.' },
            { q: '（　　）しています。', answer: '予約（よやく）', en: 'I have a reservation.' },
            { q: '朝（あさ）ごはんは（　　）からですか。', answer: '何時（なんじ）', en: 'What time does breakfast start?' },
            { q: 'タオルをもう一枚（いちまい）（　　）。', answer: 'ください', en: 'One more towel, please.' },
            { q: 'エアコンが（　　）。', answer: 'つきません', en: 'The air conditioner doesn’t turn on.' },
        ],
    },
    {
        id: 'restaurant',
        title: 'レストラン',
        subtitle: '注文（ちゅうもん）とお会計（かいけい）',
        titleEn: 'Restaurant: ordering and paying',
        goal: { ja: '人数（にんずう）を言（い）って席（せき）に着（つ）き、注文（ちゅうもん）とお会計（かいけい）ができる。', en: 'Tell the number of people, order, and pay the bill.' },
        phrases: [
            { ja: '二人（ふたり）です。', en: 'Two people.' },
            { ja: 'メニューをください。', en: 'A menu, please.' },
            { ja: 'これをください。', en: 'I’ll have this, please.' },
            { ja: 'おすすめは何（なん）ですか。', en: 'What do you recommend?' },
            { ja: '水（みず）をください。', en: 'Water, please.' },
            { ja: '肉（にく）は食（た）べられません。', en: 'I can’t eat meat.' },
            { ja: 'お会計（かいけい）をお願（ねが）いします。', en: 'The check, please.' },
            { ja: 'カードは使（つか）えますか。', en: 'Can I pay by card?' },
        ],
        usage: [
            { ja: '店（みせ）に入（はい）ると「何名様（なんめいさま）ですか」と聞（き）かれます。指（ゆび）で人数（にんずう）を見（み）せながら「二人（ふたり）です」と言（い）いましょう。', en: 'When you enter, you’ll be asked “How many people?” Say “futari desu” while showing the number with your fingers.' },
            { ja: '食（た）べられない物（もの）がある時（とき）は、注文（ちゅうもん）の前（まえ）に伝（つた）えましょう。', en: 'If there is something you can’t eat, say so before you order.' },
            { ja: '日本（にほん）では、チップは要（い）りません。', en: 'There is no tipping in Japan.' },
            { ja: 'お会計（かいけい）は、テーブルではなくレジで払（はら）う店（みせ）が多（おお）いです。', en: 'At many restaurants you pay at the register, not at the table.' },
        ],
        dialogue: [
            { speaker: '店員（てんいん）', ja: 'いらっしゃいませ。何名様（なんめいさま）ですか。', en: 'Welcome. How many people?' },
            { speaker: '旅行者（りょこうしゃ）', ja: '二人（ふたり）です。', en: 'Two.' },
            { speaker: '店員（てんいん）', ja: 'こちらへどうぞ。', en: 'This way, please.' },
            { speaker: '旅行者（りょこうしゃ）', ja: 'すみません、おすすめは何（なん）ですか。', en: 'Excuse me, what do you recommend?' },
            { speaker: '店員（てんいん）', ja: '天（てん）ぷらそばです。', en: 'The tempura soba.' },
            { speaker: '旅行者（りょこうしゃ）', ja: 'じゃあ、これを二（ふた）つください。', en: 'Then two of these, please.' },
            { speaker: '店員（てんいん）', ja: 'はい、少々（しょうしょう）お待（ま）ちください。', en: 'Certainly. Just a moment, please.' },
            { speaker: '旅行者（りょこうしゃ）', ja: 'すみません、お会計（かいけい）をお願（ねが）いします。', en: 'Excuse me, the check, please.' },
            { speaker: '店員（てんいん）', ja: '2,400円（にせんよんひゃくえん）です。', en: 'That will be 2,400 yen.' },
            { speaker: '旅行者（りょこうしゃ）', ja: 'カードは使（つか）えますか。', en: 'Can I pay by card?' },
            { speaker: '店員（てんいん）', ja: 'はい、使（つか）えます。', en: 'Yes, you can.' },
        ],
        blanks: [
            { q: '（　　）です。（2人（ふたり）の時（とき））', answer: '二人（ふたり）', en: 'Two people.' },
            { q: 'メニューを（　　）。', answer: 'ください', en: 'A menu, please.' },
            { q: 'おすすめは（　　）ですか。', answer: '何（なん）', en: 'What do you recommend?' },
            { q: 'お会計（かいけい）を（　　）。', answer: 'お願（ねが）いします', en: 'The check, please.' },
            { q: 'カードは（　　）か。', answer: '使（つか）えます', en: 'Can I pay by card?' },
        ],
    },
    {
        id: 'shopping',
        title: '買（か）い物（もの）',
        subtitle: '値段（ねだん）とサイズ',
        titleEn: 'Shopping: prices and sizes',
        goal: { ja: '値段（ねだん）を聞（き）き、サイズや色（いろ）を伝（つた）えて買（か）える。', en: 'Ask the price, tell the size and color you want, and buy it.' },
        phrases: [
            { ja: 'これはいくらですか。', en: 'How much is this?' },
            { ja: 'もっと大（おお）きいのはありますか。', en: 'Do you have a bigger one?' },
            { ja: 'Mサイズはありますか。', en: 'Do you have it in medium?' },
            { ja: 'ほかの色（いろ）はありますか。', en: 'Do you have other colors?' },
            { ja: '着（き）てみてもいいですか。', en: 'May I try it on?' },
            { ja: 'これにします。', en: 'I’ll take this.' },
            { ja: '袋（ふくろ）は要（い）りません。', en: 'I don’t need a bag.' },
            { ja: '免税（めんぜい）できますか。', en: 'Can I buy this tax-free?' },
        ],
        usage: [
            { ja: '値段（ねだん）は「〜円（えん）」で言（い）います。数字（すうじ）が聞（き）き取（と）れない時（とき）は、レジの画面（がめん）を見（み）ましょう。', en: 'Prices are said in yen. If you can’t catch the numbers, look at the screen at the register.' },
            { ja: '日本（にほん）では、値段（ねだん）の交渉（こうしょう）はほとんどしません。', en: 'Bargaining is rare in Japan.' },
            { ja: '袋（ふくろ）はお金（かね）がかかる店（みせ）が多（おお）いです。「袋（ふくろ）は要（い）りますか」と聞（き）かれます。', en: 'Many shops charge for bags. You’ll be asked “Do you need a bag?”' },
            { ja: '免税（めんぜい）で買（か）う時（とき）は、パスポートが要（い）ります。', en: 'You need your passport to shop tax-free.' },
        ],
        dialogue: [
            { speaker: '店員（てんいん）', ja: 'いらっしゃいませ。', en: 'Welcome.' },
            { speaker: '旅行者（りょこうしゃ）', ja: 'すみません、これはいくらですか。', en: 'Excuse me, how much is this?' },
            { speaker: '店員（てんいん）', ja: '3,000円（さんぜんえん）です。', en: 'It’s 3,000 yen.' },
            { speaker: '旅行者（りょこうしゃ）', ja: 'ほかの色（いろ）はありますか。', en: 'Do you have other colors?' },
            { speaker: '店員（てんいん）', ja: '白（しろ）と黒（くろ）があります。', en: 'We have white and black.' },
            { speaker: '旅行者（りょこうしゃ）', ja: 'じゃあ、黒（くろ）をください。Mサイズはありますか。', en: 'Then black, please. Do you have it in medium?' },
            { speaker: '店員（てんいん）', ja: 'はい、こちらです。', en: 'Yes, here it is.' },
            { speaker: '旅行者（りょこうしゃ）', ja: 'これにします。', en: 'I’ll take this.' },
            { speaker: '店員（てんいん）', ja: '袋（ふくろ）は要（い）りますか。', en: 'Do you need a bag?' },
            { speaker: '旅行者（りょこうしゃ）', ja: 'いいえ、要（い）りません。', en: 'No, I don’t.' },
        ],
        blanks: [
            { q: 'これは（　　）ですか。', answer: 'いくら', en: 'How much is this?' },
            { q: 'ほかの（　　）はありますか。', answer: '色（いろ）', en: 'Do you have other colors?' },
            { q: 'もっと（　　）のはありますか。', answer: '大（おお）きい', en: 'Do you have a bigger one?' },
            { q: 'これに（　　）。', answer: 'します', en: 'I’ll take this.' },
            { q: '袋（ふくろ）は（　　）。', answer: '要（い）りません', en: 'I don’t need a bag.' },
        ],
    },
    {
        id: 'train',
        title: '電車（でんしゃ）と道（みち）',
        subtitle: '駅（えき）と道（みち）を聞（き）く',
        titleEn: 'Trains and directions',
        goal: { ja: '駅（えき）や道（みち）を聞（き）いて、電車（でんしゃ）の行（い）き先（さき）を確（たし）かめられる。', en: 'Ask the way to a station or place, and check where a train is going.' },
        phrases: [
            { ja: 'すみません、駅（えき）はどこですか。', en: 'Excuse me, where is the station?' },
            { ja: 'ここに行（い）きたいです。', en: 'I want to go here.' },
            { ja: 'ここから遠（とお）いですか。', en: 'Is it far from here?' },
            { ja: '新宿（しんじゅく）までいくらですか。', en: 'How much is it to Shinjuku?' },
            { ja: 'この電車（でんしゃ）は新宿（しんじゅく）に行（い）きますか。', en: 'Does this train go to Shinjuku?' },
            { ja: '何番線（なんばんせん）ですか。', en: 'Which platform is it?' },
            { ja: '次（つぎ）は何駅（なにえき）ですか。', en: 'What is the next station?' },
            { ja: 'まっすぐ行（い）って、右（みぎ）です。', en: 'Go straight, and it’s on the right.' },
        ],
        usage: [
            { ja: '道（みち）を聞（き）く時（とき）は、スマホの地図（ちず）を見（み）せながら「ここに行（い）きたいです」と言（い）うと伝（つた）わりやすいです。', en: 'When asking the way, show the map on your phone and say “koko ni ikitai desu.” It is easy to understand.' },
            { ja: '駅（えき）では「〜番線（ばんせん）」の数字（すうじ）でホームを探（さが）します。', en: 'At the station, find your platform by its number, “… bansen.”' },
            { ja: '交通系（こうつうけい）ICカード（Suica・PASMOなど）があると、切符（きっぷ）を買（か）わずに乗（の）れます。', en: 'With a transit IC card (Suica, PASMO, etc.), you can ride without buying tickets.' },
            { ja: '電車（でんしゃ）の中（なか）では、電話（でんわ）で話（はな）さないのがマナーです。', en: 'It is good manners not to talk on the phone on the train.' },
        ],
        dialogue: [
            { speaker: '旅行者（りょこうしゃ）', ja: 'すみません、この電車（でんしゃ）は新宿（しんじゅく）に行（い）きますか。', en: 'Excuse me, does this train go to Shinjuku?' },
            { speaker: '駅員（えきいん）', ja: 'いいえ、行（い）きません。3番線（さんばんせん）の電車（でんしゃ）です。', en: 'No, it doesn’t. Take the train on platform 3.' },
            { speaker: '旅行者（りょこうしゃ）', ja: '3番線（さんばんせん）はどこですか。', en: 'Where is platform 3?' },
            { speaker: '駅員（えきいん）', ja: 'あの階段（かいだん）を上（あ）がって、右（みぎ）です。', en: 'Go up those stairs, and it’s on the right.' },
            { speaker: '旅行者（りょこうしゃ）', ja: '新宿（しんじゅく）まで何分（なんぷん）ですか。', en: 'How many minutes is it to Shinjuku?' },
            { speaker: '駅員（えきいん）', ja: '15分（じゅうごふん）ぐらいです。', en: 'About fifteen minutes.' },
            { speaker: '旅行者（りょこうしゃ）', ja: 'ありがとうございます。', en: 'Thank you.' },
        ],
        blanks: [
            { q: '駅（えき）は（　　）ですか。', answer: 'どこ', en: 'Where is the station?' },
            { q: '（　　）に行（い）きたいです。', answer: 'ここ', en: 'I want to go here.' },
            { q: '新宿（しんじゅく）まで（　　）ですか。', answer: 'いくら', en: 'How much is it to Shinjuku?' },
            { q: 'この電車（でんしゃ）は新宿（しんじゅく）に（　　）か。', answer: '行（い）きます', en: 'Does this train go to Shinjuku?' },
            { q: 'まっすぐ行（い）って、（　　）です。', answer: '右（みぎ）', en: 'Go straight, and it’s on the right.' },
        ],
    },
];
