import type { Translations } from './i18n';

export const es: Translations = {
    title: 'Hoja de Ruta para Aprender Japonés',
    subtitle: 'Crea tu plan de estudio personalizado',
    currentLevel: 'Nivel Actual',
    targetLevel: 'Nivel Objetivo',
    learningPeriod: 'Periodo de Estudio',
    months: ' meses',
    monthUnit: ' meses',
    beginner: 'Principiante',
    native: 'Nativo',
    purpose: '¿Por qué quieres aprender japonés?',
    createRoadmap: '📚 Crear Hoja de Ruta',
    selectPurpose: 'Selecciona tu objetivo',
    levelDescriptions: { n5: 'JLPT N5', n4: 'JLPT N4', n3: 'JLPT N3', n2: 'JLPT N2', n1: 'JLPT N1', nativeLevel: 'Nativo' },
    purposes: {
        anime: { label: 'Anime, Manga y Juegos', description: 'Disfrutar sin subtítulos' },
        friends: { label: 'Hacer Amigos/Pareja', description: 'Relaciones profundas con japoneses' },
        travel: { label: 'Viajar por Japón', description: 'Explorar libremente' },
        culture: { label: 'Cultura Japonesa', description: 'Tradiciones y gastronomía' },
        live: { label: 'Vivir en Japón', description: 'Vida segura y cómoda' },
        work: { label: 'Trabajar en Japón', description: 'Japonés de negocios' },
        beauty: { label: 'El Japonés es Bello', description: 'Sonidos y caracteres fascinantes' },
        challenge: { label: 'Reto Personal', description: 'Curiosidad y crecimiento' },
        other: { label: 'Otro', description: 'Otros objetivos' },
    },
    planSummary: '📊 Resumen de tu Plan',
    totalHours: 'Horas Totales',
    hoursPerWeek: 'hrs/sem',
    levelUp: 'Subir Nivel',
    current: 'Actual',
    goal: 'Meta',
    dailyStudy: 'Aproximadamente ',
    hoursUnit: ' horas',
    achievable: ' al día para alcanzar tu meta.',
    growthChart: 'Pronóstico de Crecimiento',
    now: 'Ahora',
    monthsLater: 'm después',
    level: 'Nivel',
    lessonDistribution: 'Distribución de Lecciones',
    optimizedForYou: 'Equilibrio optimizado para tus objetivos',
    whyThisBalance: '¿Por qué este equilibrio?',
    lessonTypes: { grammar: 'Gramática', vocabulary: 'Vocabulario', conversation: 'Conversación', reading: 'Lectura', listening: 'Comprensión auditiva' },
    monthlyMilestones: 'Hitos Mensuales',
    monthN: '',
    targetLevelLabel: 'Objetivo',
    purposeStep: 'Pasos hacia tu meta',
    learningContent: '🎯 Enfoque de este mes',
    achievedSkills: '✅ Habilidades que ganarás',
    whyThisOrder: '📌 ¿Por qué este orden?',
    recommendedLessons: 'Lecciones recomendadas',
    textbooksLabel: 'Libros de texto',
    aiPromptLabel: 'Prompt de IA',

    clickToCopy: 'Toca para copiar',
    promptCopied: '¡Copiado!',
    lessonsPerMonth: '/mes',
    roadmapComplete: '🎉 ¡Tu Hoja de Ruta está Lista!',
    ctaDescription: 'Con este plan, definitivamente alcanzarás tu meta.',
    ctaPeriod: ' en ',
    ctaFrom: 'De ',
    ctaTo: ' a ',
    startFreeTrial: '✨ Iniciar Prueba Gratuita',
    shareThisPlan: 'Compartir este Plan',
    generating: 'Generando...',
    trialBooked: '¡Prueba gratuita reservada!',
    imageError: 'Error al generar imagen',
    shareOpened: 'Menú de compartir abierto',
    downloaded: 'Imagen descargada',
    errorOccurred: 'Ocurrió un error',
    distributionReasons: {
        anime: { beginner: 'Para entender anime, la escucha es clave. Entrenaremos tu oído para expresiones coloquiales mientras construimos gramática y vocabulario.', advanced: 'Además de escuchar, necesitarás leer manga y juegos. Nos enfocamos en japonés coloquial, argot y onomatopeyas.' },
        friends: { beginner: 'Para conectar con personas, hablar es lo primero. Aunque uses gramática simple, mantener conversaciones profundiza las relaciones.', advanced: 'Las relaciones profundas requieren transmitir matices. Practicaremos cambio entre formal e informal y "leer el ambiente".' },
        travel: { beginner: 'El japonés para viajes: "frases que puedes usar ahora". Priorizamos vocabulario para estaciones, restaurantes y hoteles.', advanced: 'Entender dialectos regionales y comunicarte donde no se habla inglés. Leer señales y charlar con locales.' },
        culture: { beginner: 'Entender la cultura japonesa requiere lectura. Priorizamos vocabulario de etiqueta, eventos y gastronomía.', advanced: 'Expresiones clásicas, proverbios, escritura epistolar — saborear la profundidad de la cultura japonesa.' },
        live: { beginner: '"Japonés de supervivencia": ayuntamiento, hospitales, bancos, inmobiliarias — todo para la vida diaria.', advanced: 'Relaciones vecinales, PTA, asociaciones comunitarias. Uso correcto del keigo y reglas sociales japonesas.' },
        work: { beginner: 'Japonés de negocios: "keigo correcto". Emails, teléfono, presentaciones profesionales.', advanced: 'Reuniones, presentaciones, negociaciones, informes — japonés que genera confianza profesional.' },
        beauty: { beginner: 'Para apreciar el japonés bello, empezamos con caracteres. Trazos de hiragana/katakana, orígenes del kanji, ritmo del japonés.', advanced: 'Haiku, tanka, expresiones poéticas, vocabulario estacional — la esencia de la belleza japonesa.' },
        challenge: { beginner: 'Crecimiento equilibrado en todas las habilidades. Entender la estructura del japonés lógicamente.', advanced: 'Preparación JLPT: mejorar lectura y escucha. Gramática avanzada y vocabulario abstracto.' },
        other: { beginner: 'Plan equilibrado para 5 habilidades. ¡Cuéntame tus metas en la lección gratuita!', advanced: 'Plan integral para todas las habilidades. ¡Personalicemos en la lección gratuita!' },
    },
    purposeMilestones: {
        anime: ['Puedes leer letras de openings 🎵', 'Captas saludos simples en anime 👂', 'Entiendes 80% del anime con subs 📺', 'Sigues un episodio sin subs 🎉', 'Juegas juegos japoneses sin diccionario 🎮', 'Lees manga en japonés original 📖', 'Entiendes diálogos complejos y matices ✨'],
        friends: ['Puedes presentarte y hablar de hobbies 👋', 'Intercambias mensajes en LINE 📱', 'Charlas en un café 30 minutos ☕', 'Expresas sentimientos en japonés 💬', 'Entiendes bromas y ríes juntos 😄', 'Hablas de temas profundos 🤝', 'Discutes y te reconcilias en japonés 💪'],
        travel: ['Lees señales de estaciones 🚃', 'Pides y pagas en restaurantes 🍣', 'Pides y entiendes direcciones 🗺️', 'Charlas con personal del ryokan ♨️', 'Entiendes dialectos regionales 🏔️', 'Viajas solo sin guía 🎒', 'Haces amigos locales y descubres lugares secretos 🌸'],
        culture: ['Usas modales básicos correctamente 🙇', 'Conoces festividades japonesas 🎎', 'Explicas comida japonesa y etiqueta 🍱', 'Entiendes términos de ceremonia del té 🍵', 'Discutes historia y valores japoneses 🏯', 'Aprecias haiku y tanka 📝', 'Disfrutas la cultura a nivel nativo 🌊'],
        live: ['Compras en tiendas sin problemas 🏪', 'Haces trámites en el ayuntamiento 📋', 'Describes síntomas en el hospital 🏥', 'Charlas con vecinos 🏘️', 'Entiendes contratos bancarios 📄', 'Participas en reuniones de PTA 🤝', 'Vives independientemente en Japón 🏠'],
        work: ['Saludos de negocio y tarjetas 💼', 'Escribes correos de negocio ✉️', 'Manejas llamadas telefónicas 📞', 'Presentas ideas en reuniones 🎤', 'Negocias sin intérprete 🤝', 'Haces presentaciones en japonés 📊', 'Lideras un equipo en japonés 🏆'],
        beauty: ['Escribes hiragana/katakana bellamente ✍️', 'Dominas trazos de 50 kanji 📝', 'Aprecias la belleza del keigo 🌸', 'Escribes cartas elegantes ✉️', 'Intentas escribir haiku/tanka 🖊️', 'Distingues matices sutiles ✨', 'Aprecias plenamente los sonidos japoneses 🎵'],
        challenge: ['Dominas hiragana, katakana y kanji básico 🏅', 'Resuelves ejercicios N5 📚', 'Nivel de aprobación N4 🎯', 'Rango de aprobación N3 💪', 'Listo para N2 🔥', 'Apuntas a N1 🏆', '¡Maestro del japonés! ¿Qué sigue? 🌍'],
        other: ['Base sólida de japonés 📖', 'Conversaciones diarias simples 💬', 'Expresas ideas en japonés ✍️', 'Buscas información en japonés 🔍', 'Conversas sobre muchos temas 🗣️', 'Entiendes contenido especializado 📊', 'Usas japonés naturalmente ✨'],
    },
    monthlyContent: {
        focus: [['Hiragana y Katakana', 'Saludos básicos', 'Números y hora'], ['Gramática N5', '200 palabras', 'Oraciones simples'], ['Gramática N4', '500 palabras', 'Keigo básico'], ['Gramática N3', '1000 palabras', 'Lectura intermedia'], ['N3→N2', 'Vocabulario abstracto', 'Textos largos'], ['N2 gramática', 'Japonés de negocios', 'Lectura especializada'], ['Expresiones N1', 'Matices', 'Japonés académico']],
        skills: [['Presentarte', 'Responder preguntas simples'], ['Compras básicas', 'Pedir direcciones'], ['Pedir en restaurantes', 'Escribir correos'], ['Leer titulares', 'Expresar opiniones'], ['Entender noticias', 'Unirte a discusiones'], ['Hablar en reuniones', 'Escribir informes'], ['Leer artículos académicos', 'Dar presentaciones']],
        reasons: ['Dominar escritura japonesa y expresiones esenciales.', 'Japonés mínimo para uso real y conversaciones básicas.', 'Japonés para vida diaria y conversaciones naturales.', 'Expresiones complejas para negocios y academia.', 'Habilidades prácticas para trabajo y estudios.', 'Habilidades avanzadas para uso profesional.', 'Competencia casi nativa en cualquier situación.'],
    },
    purposeMonthlyContent: {
        anime: {
            focus: [['Saludos y exclamaciones de anime', 'Leer nombres en katakana', 'Hiragana y katakana básico'], ['50 frases típicas de anime', 'Vocabulario de anime cotidiano', 'Práctica de escucha de diálogos'], ['Patrones de conversación diaria', 'Lectura de diálogos de manga', 'Onomatopeyas y efectos sonoros'], ['Casual vs. formal', 'Textos de interfaz de juegos', 'Expresiones emocionales en anime'], ['Términos de género (batalla, ciencia ficción)', 'Lectura de guías de juegos', 'Argot y lenguaje juvenil'], ['Comprensión de tramas complejas', 'Lectura de novelas ligeras', 'Dialectos y habla de personajes'], ['Expresiones literarias y metáforas', 'Análisis y reseñas de anime', 'Conversación a velocidad nativa']],
            skills: [['Leer letras de openings', 'Pronunciar nombres de personajes'], ['Entender exclamaciones básicas', 'Captar saludos en anime'], ['Leer diálogos de manga', 'Entender 50% de anime subtitulado'], ['Entender 80% de anime subtitulado', 'Leer textos básicos de RPG'], ['Seguir anime cotidiano sin subs', 'Jugar videojuegos en japonés'], ['Disfrutar manga en japonés original', 'Entender presagios y metáforas'], ['Comprensión total de matices', 'Discutir anime en japonés']],
            reasons: ['El primer paso es leer. Poder leer letras de opening y nombres mantiene la motivación alta.', 'Priorizar expresiones coloquiales del anime. Aprender el japonés vivo que no está en los libros.', 'Fortalecer "escucha + lectura". La lectura de manga potencia eficientemente tu japonés de anime.', 'Entender la diferencia entre casual y formal, dominando el cambio según la situación.', 'Aprender jerga y argot específico del género, acercándote a ver sin subtítulos.', 'Comprender patrones de habla de personajes, dialectos y estructuras narrativas profundas.', 'Disfrutar obras con la misma profundidad que un nativo y discutir análisis en japonés.'],
            textbooks: [['Genki I', 'Anime Scripts'], ['Genki II', 'Yotsuba&! (Manga)'], ['Quartet I', 'Slice of Life Anime Scripts'], ['Quartet II', 'Shonen Manga (with Furigana)'], ['Tobira', 'RPG Game Scripts'], ['Shin Kanzen Master N1', 'Light Novels (Easy)'], ['Native Materials', 'Anime Scenarios']],
            aiPrompt: [
                'You are a Japanese teacher who loves anime. Teach me 5 basic greeting phrases a beginner should know, speaking in an energetic tone like Luffy from One Piece.',
                'Explain the nuance and usage of sentence endings like "~daze" and "~kashira" often found in anime, with character dialogue examples.',
                'Analyze the polite yet strong speaking style of Tanjiro from Demon Slayer and create 3 phrases I can use in daily life.',
                'Create 5 "tsundere" lines for an anime character, explaining the grammatical structure and emotional nuance of each.',
                'List 20 important words related to "magic," "equipment," and "adventure" frequent in fantasy RPGs, with example sentences.',
                'Reproduce lines of an anime character using Kyoto dialect (Kansai-ben) and explain the difference from standard Japanese.',
                'Write a philosophical monologue in Japanese like in "Neon Genesis Evangelion" and explain the abstract vocabulary used.',
            ],
        },
        friends: {
            focus: [['Frases de autopresentación', 'Saludos casuales', 'Hiragana y katakana básico'], ['Expresiones para SNS y LINE', 'Vocabulario de hobbies', 'Cómo dar reacciones (aizuchi)'], ['Cambio casual-formal', 'Vocabulario de emociones', 'Cómo invitar y declinar'], ['Expresar opiniones', 'Humor y bromas', 'Cambio entre casual y keigo'], ['Hablar de preocupaciones', 'Matices sutiles', 'Entender "leer el ambiente"'], ['Debate y discusión', 'Vocabulario de temas profundos', 'Dialectos regionales'], ['Sarcasmo y lenguaje figurado', 'Valores japoneses', 'Conversación a velocidad nativa']],
            skills: [['Presentarte y hablar de hobbies', 'Usar saludos como "yoroshiku"'], ['Chatear en LINE', 'Preguntar sobre hobbies'], ['Charlar 30 minutos manteniendo la conversación', 'Invitar y declinar educadamente'], ['Expresar sentimientos en japonés', 'Hacer reír con bromas'], ['Hablar de preocupaciones personales', 'Leer el ambiente como un local'], ['Tener conversaciones profundas', 'Chatear usando dialectos'], ['Discutir y reconciliarse', 'Conversar al mismo nivel que nativos']],
            reasons: ['Hacer amigos empieza con la autopresentación. Encontrar hobbies en común inicia las relaciones.', 'SNS es la base moderna de la amistad. Domina frases útiles para LINE.', 'Desarrolla la resistencia para charlar en un café. Aprende a invitar y declinar naturalmente.', 'Profundizar relaciones requiere expresar sentimientos. Añade humor para conversaciones atractivas.', 'Entiende la cultura de "leer el ambiente" para construir confianza más profunda.', 'Desarrolla la capacidad de debatir temas profundos en japonés — nivel de mejor amigo.', 'Completa tu capacidad de conversar natural e igualmente con hablantes nativos.'],
            textbooks: [['Genki I', 'HelloTalk'], ['Genki II', 'LINE Stickers Japanese'], ['Tsunagu Nihongo', 'Tandem'], ['Quartet I', 'Japanese Dramas (Subtitled)'], ['Quartet II', 'Japanese Variety Shows'], ['Tobira', 'Japanese YouTubers'], ['Native Materials', 'Sharehouse Conversations']],
            aiPrompt: [
                'I want to make friends with a Japanese person I just met. Teach me 3 self-introduction phrases that are friendly but not rude.',
                'Create two examples of natural LINE messages to invite someone to dinner: one for a "close friend" and one for "someone I just met."',
                'Teach me the positive and negative nuances of slang words young people use like "maji-de" and "yabai," with example sentences.',
                'List 10 empathetic Japanese phrases (like "That must have been hard") I can use when listening to a friend\'s worries.',
                'Explain what "reading the air" specifically means using a Japanese drinking party situation as an example.',
                'Teach me phrases to exchange opinions on recent news with a friend, like "I think this, but what do you think?"',
                'Teach me some Japanese jokes or "dad jokes" (oyaji gag) and explain why they are funny (wordplay, etc.).',
            ],
        },
        travel: {
            focus: [['Señales de estación y aeropuerto', 'Números, hora y días', 'Hiragana y katakana básico'], ['Frases para pedir en restaurantes', 'Check-in de hotel', 'Pedir direcciones'], ['Transbordos de transporte', 'Confirmar precios comprando', 'Preguntas en sitios turísticos'], ['Modales y conversación en ryokan', 'Vocabulario de especialidades locales', 'Expresiones de clima y salud'], ['Dialectos regionales básicos', 'Explicaciones de sitios históricos', 'Charlar con locales'], ['Lectura de blogs y reseñas de viajes', 'Reservas por teléfono', 'Situaciones de emergencia'], ['Conversación con dialectos', 'Conexiones profundas viajando', 'Explicar cultura japonesa']],
            skills: [['Leer señales de estación', 'Entender números hablados'], ['Pedir y pagar en restaurantes', 'Indicar destino al taxista'], ['Hacer transbordos de tren', 'Confirmar precios en tiendas'], ['Disfrutar conversaciones en ryokan', 'Describir problemas de salud'], ['Entender dialectos mayormente', 'Charlar con locales'], ['Hacer reservas por teléfono', 'Planear viajes con reseñas'], ['Viajar solo con total independencia', 'Descubrir lugares secretos de locales']],
            reasons: ['Viajar empieza con señales y números. Prioriza lo mínimo necesario para moverte.', 'Enfócate en "frases que puedes usar ya". Gana confianza en restaurantes y hoteles.', 'Alcanza independencia en transporte y compras. Practica expresiones prácticas intensivamente.', 'Duplica la alegría del viaje con experiencias "omotenashi". Disfruta conversaciones en ryokan.', 'Aprende dialectos básicos para disfrutar conversaciones naturales con locales.', 'Conviértete en un viajero autosuficiente que puede investigar y hacer reservas por teléfono.', 'Sé un viajero avanzado que disfruta cada rincón de Japón y conecta profundamente con locales.'],
            textbooks: [['Phrasebook', 'Google Maps'], ['Travel Japanese', 'Train Timetables'], ['Japan Travel Survival', 'Tabelog'], ['Omotenashi Japanese', 'Ryokan Booking Sites'], ['Dialect Chart', 'Rurubu (Travel Mag)'], ['Jalan (Booking Site)', 'Shinkansen App'], ['National Guides', 'Local Newspapers']],
            aiPrompt: [
                'I am lost at a station in Japan. Teach me a polite phrase to ask station staff "How to get to Shinjuku Station" and "How long it takes."',
                'I entered a restaurant in Japan. Create a phrase to say I have an allergy (e.g., shrimp) and ask for a menu without it.',
                'Explain basic manners I should know when staying at a Ryokan (taking off shoes, hot spring etiquette) in simple Japanese.',
                'Simulate a conversation where I ask a shop clerk "What do you recommend?" and ask for the reason.',
                'I am traveling to Kansai (Osaka/Kyoto). Teach me 5 simple Kansai-ben phrases (like "ookini") to use with shop staff.',
                'I want to book a restaurant by phone. Create a script saying "I would like to make a reservation for 2 people at 7 PM next Saturday."',
                'Think of 3 slightly intellectual mock questions to ask a guide about history when visiting Japanese castles or temples.',
            ],
        },
        culture: {
            focus: [['Etiqueta y modales básicos', 'Nombres de comida japonesa', 'Hiragana y katakana básico'], ['Vocabulario de eventos anuales', 'Modales de cultura gastronómica', 'Saludos estacionales'], ['Términos de ceremonia del té/flores', 'Tipos de kimono', 'Vocabulario de artesanía'], ['Historia japonesa básica', 'Sintoísmo y budismo', 'Introducción a waka'], ['Literatura clásica básica', 'Refranes y modismos', 'Caligrafía básica'], ['Apreciación de Noh y Kabuki', 'Comentario de arte japonés', 'Palabras estacionales y haiku'], ['Lectura de textos clásicos', 'Debate cultural', 'Estética japonesa']],
            skills: [['Conocer tipos de reverencia', 'Explicar etiqueta de palillos'], ['Explicar fiestas y eventos japoneses', 'Describir modales de washoku'], ['Entender flujo de ceremonia del té', 'Conocer kimonos por ocasión'], ['Hablar de historia japonesa', 'Explicar diferencia templo-santuario'], ['Usar refranes en la vida diaria', 'Entender reglas básicas de haiku'], ['Apreciar y explicar artes tradicionales', 'Hablar de características del arte japonés'], ['Apreciar literatura clásica en original', 'Discutir profundamente cultura japonesa']],
            reasons: ['La puerta a la cultura japonesa son la etiqueta y la comida. Aprende la "forma" con reverencias y palillos.', 'Aprende la conexión de Japón con la naturaleza a través de eventos estacionales.', 'Experimenta la cultura del "camino" (té, flores) y profundiza tu comprensión del "wabi-sabi".', 'Aprende la historia y religión detrás de la cultura. El conocimiento profundo transforma la experiencia cultural.', 'Encuentra expresiones clásicas y proverbios, saboreando la sabiduría cultural del japonés.', 'De artes escénicas a bellas artes — alcanza un nivel donde puedas apreciar y explicar la esencia cultural de Japón.', 'Lee clásicos en original, alcanzando un nivel de comprensión igual al de hablantes nativos.'],
            textbooks: [['Intro to Japanese Culture', 'Chopstick Tutorials'], ['Japanese Annual Events', 'Japanese Calendar'], ['Tea Ceremony Intro', 'Traditional Crafts Guide'], ['Japanese History Manga', 'Shrine Test Text'], ['Children\'s Analects', 'Hyakunin Isshu'], ['Kabuki Guide', 'Art History Intro'], ['Tale of Genji (Original/Modern)', 'Fushikaden']],
            aiPrompt: [
                'Explain the difference between Japanese bows (eshaku, keirei, saikeirei) and when to use each.',
                'Teach me Japanese phrases to explain the spiritual meaning of "Itadakimasu" and "Gochisousama" to foreigners.',
                'Briefly explain the Japanese aesthetic of "Wabi-Sabi" in Japanese, using moss or tea bowls as examples.',
                'Compare the differences between shrines and temples (worship methods, what is enshrined) and create a word list for each.',
                'Explain the meaning of the famous proverb "Ishi no ue ni mo sannen" and modern situations where it is used.',
                'I am going to see Kabuki for the first time. Teach me 3 points a beginner should know about unique calls and how to enjoy it.',
                'Explain the modern translation of the opening of "The Tale of Genji" and its unique atmosphere and cultural background.',
            ],
        },
        live: {
            focus: [['Señales de tiendas y supermercados', 'Cómo leer direcciones', 'Hiragana y katakana básico'], ['Términos de trámites municipales', 'Abrir cuenta bancaria', 'Recepción de hospital'], ['Términos de contrato de alquiler', 'Electricidad, gas y agua', 'Correo y paquetería'], ['Vocabulario de asociación vecinal', 'Términos escolares', 'Seguros y pensión'], ['Declaración de impuestos', 'Vocabulario inmobiliario', 'PTA y actividades comunitarias'], ['Términos legales básicos', 'Cambio de trabajo y carrera', 'Sistemas de apoyo a la crianza'], ['Todos los trámites administrativos', 'Actividades cívicas y voluntariado', 'Comprensión profunda de la sociedad japonesa']],
            skills: [['Comprar en tiendas de conveniencia', 'Escribir tu dirección en japonés'], ['Presentar formularios en el ayuntamiento', 'Abrir cuenta bancaria'], ['Entender puntos clave del contrato', 'Consultar sobre servicios públicos'], ['Charlar con vecinos', 'Entender cartas de la escuela'], ['Entender documentos de impuestos', 'Participar en actividades comunitarias'], ['Entender derechos legales', 'Buscar trabajo en japonés'], ['Totalmente integrado en la sociedad japonesa', 'Gestionar todos los trámites solo']],
            reasons: ['La vida en Japón empieza con tiendas y direcciones. Prioriza palabras que usarás cada día.', 'Completa trámites de infraestructura vital de forma independiente. Ayuntamiento, banco y hospital primero.', 'Estabiliza tu base de vida. Enfócate en contratos de alquiler y terminología de servicios.', 'Tiempo de integrarse en la comunidad local. Amplía vocabulario de vecindario y escuela.', 'Profundiza conocimientos para vivir a largo plazo. Echa raíces con impuestos y actividades comunitarias.', 'Desarrolla japonés avanzado para avance profesional y procedimientos legales.', 'Apunta a una integración completa en la sociedad japonesa, viviendo cómodamente en toda situación.'],
            textbooks: [['Japanese for Life', 'Supermarket Flyers'], ['City Hall Guide', 'Medical Japanese'], ['Reading Contracts', 'Rental Sites'], ['PTA Handbook', 'Circular Notices'], ['Tax Return Guide', 'Disaster Maps'], ['Business Law Intro', 'Hello Work Job Slips'], ['Understanding Japanese Society', 'Newspaper Editorials']],
            aiPrompt: [
                'Reproduce a natural interaction at a Japanese convenience store asking to warm up a bento and get chopsticks and a bag.',
                'Simulate a conversation at a hospital reception to convey "I have had a fever since yesterday and my throat hurts."',
                'I am looking for an apartment at a real estate agency. Create a dialogue conveying "Rent under 70,000 yen, within 10 min walk from station."',
                'Garbage sorting rules are confusing. Teach me a conversation to ask a neighbor "Which day should I put out this plastic?"',
                'Write a polite message for a child\'s school contact book saying "He will be absent tomorrow due to a cold."',
                'Explain basic keywords beginners should know about year-end tax adjustment and tax returns in Japan (deductions, withholding, etc.).',
                'Think of a self-introduction speech for a neighborhood association meeting saying "I am still studying Japanese, but nice to meet you."',
            ],
        },
        work: {
            focus: [['Saludos de negocios', 'Intercambio de tarjetas', 'Hiragana y katakana básico'], ['Plantillas de email de negocios', 'Atender teléfono', 'Autopresentación empresarial'], ['Redacción de actas', 'Cultura Ho-Ren-So', 'Sistema de keigo'], ['Materiales de presentación', 'Patrones de intervención en reunión', 'Expresiones de negociación'], ['Lectura de contratos', 'Informes y documentos', 'Vocabulario de política interna'], ['Vocabulario de estrategia empresarial', 'Términos IR y financieros', 'Expresiones de liderazgo'], ['Japonés nivel ejecutivo', 'Términos M&A y legales', 'Discursos y conferencias']],
            skills: [['Intercambiar tarjetas de visita', 'Saludar correctamente en negocios'], ['Escribir emails plantilla', 'Transferir llamadas'], ['Escribir actas de reunión', 'Hacer Ho-Ren-So con superiores'], ['Presentar opiniones en reuniones', 'Crear materiales de presentación'], ['Entender contratos', 'Escribir informes en japonés'], ['Participar en reuniones de dirección', 'Liderar equipos en japonés'], ['Presentar a ejecutivos', 'Gestionar todo en japonés']],
            reasons: ['La primera impresión en negocios es saludos y tarjetas. Domina la forma correcta primero.', 'Email y teléfono son básicos diarios. Domina plantillas para ser productivo de inmediato.', '"Ho-Ren-So" es vital en empresas japonesas. Construye tu base de comunicación con colegas.', 'Fortalece tu capacidad de expresión. Destaca en reuniones y presentaciones.', 'Desarrolla la capacidad de leer y escribir documentos con precisión, ganando confianza profesional.', 'Apunta a japonés de nivel gerencial para gestión de equipos y discusiones estratégicas.', 'El nivel más alto de japonés de negocios para roles ejecutivos. Maneja cualquier situación con confianza.'],
            textbooks: [['Keigo Training', 'Business Card Manners'], ['Business Writing', 'Phone Manuals'], ['Manga Ho-Ren-So', 'Meeting Japanese'], ['Presentation Japanese', 'Logical Speaking'], ['Business Contracts', 'Internal Reports'], ['Nikkei Business', 'Drucker (JP Ver)'], ['HBR Japan', 'Corporate Law']],
            aiPrompt: [
                'Teach me the correct step-by-step procedure for exchanging business cards in Japan, with dialogue.',
                'Create an example of a polite business email asking a client "I would like to change the meeting date."',
                'Create an appropriate conversation flow for reporting progress to a boss (Ho-Ren-So) starting with "Actually, there is a problem..."',
                'Teach me 5 variations of phrases to point out concerns in a meeting while agreeing, like "I agree basically, but just one point..."',
                'Explain the usage of "Osewa ni natte orimasu," "Otsukaresama desu," and "Gokurosama desu" and their NG scenes.',
                'Create an opening speech for a business presentation that apologizes for a project failure but proposes improvements sincerely.',
                'Teach me ideal praise words a Japanese boss uses to motivate subordinates (like "Sasuga da ne, kitai ijo da yo").',
            ],
        },
        beauty: {
            focus: [['Orden de trazos de hiragana', 'Orígenes del katakana', 'Características del sonido japonés'], ['Trazos de 50 kanji básicos', 'On\'yomi vs. kun\'yomi', 'Belleza de las onomatopeyas'], ['Radicales y significados del kanji', 'Práctica de escritura bella', 'Vocabulario estacional'], ['Sistema y belleza del keigo', 'Escritura de cartas', 'Nombres de colores tradicionales'], ['Reglas básicas del haiku', 'Apreciación del waka', 'Caligrafía básica'], ['Creación de tanka y poesía', 'Belleza del japonés clásico', 'Ritmo fonético japonés'], ['Dominio completo de expresión literaria', 'Maestría en caligrafía', 'Encarnación de la estética japonesa']],
            skills: [['Escribir hiragana bellamente', 'Sentir la belleza de las vocales japonesas'], ['Escribir 50 kanji con trazos correctos', 'Explicar orígenes del kanji'], ['Adivinar significado del kanji por radicales', 'Escribir cartas estacionales'], ['Usar keigo bellamente', 'Escribir cartas elegantes'], ['Componer haiku', 'Entender imágenes del waka'], ['Crear poemas tanka', 'Apreciar la belleza del japonés clásico'], ['Comprensión completa de la belleza sonora', 'Maestría en arte caligráfico']],
            reasons: ['La belleza del japonés empieza con la forma de los caracteres y el sonido. Aprender trazo a trazo cultiva el sentido estético.', 'Conocer los orígenes del kanji revela la profundidad de cada carácter. Escribir se vuelve doblemente placentero.', 'Comprensión sistemática del kanji y hermosas palabras estacionales. Esta etapa valora la calidez de lo manuscrito.', 'El keigo es la cristalización de la belleza japonesa. Dominarlo te permite sentir la profundidad del idioma.', 'Experimenta la belleza del japonés condensada en 17 y 31 sílabas a través de haiku y waka.', 'Entra en la alegría de la creación literaria. Toca la belleza única del japonés clásico.', 'El escenario final: saborear la belleza completa del japonés — sonido, forma y significado.'],
            textbooks: [['Calligraphy Practice', 'Hiragana Chart'], ['Kanji Origins', 'Beautiful Words Dict'], ['Japanese Colors', 'Seasonal Words'], ['Aesthetics of Keigo', 'Letter Writing'], ['Haiku Almanac', 'Manyoshu Intro'], ['Kokin Wakashu', 'Tale of the Bamboo Cutter'], ['Tale of Genji', 'Pillow Book']],
            aiPrompt: [
                'Teach me tips to write hiragana "a" and "no" beautifully and balanced, relating them to shapes (triangle, circle).',
                'Introduce 5 beautiful Japanese words related to "rain" (samidare, shigure, etc.) and explain the scenery of each.',
                'Teach me seasonal greetings (jikou no aisatsu) used in letter openings like "Haikei, sakura no kisetsu..." for each of the 4 seasons.',
                'Introduce some Japanese expressions that convey love indirectly and elegantly, like "The moon is beautiful, isn\'t it?"',
                'I want to make Haiku. Create and explain 3 beginner examples using "Summer" and "Sea" as themes.',
                'Select 10 Japanese onomatopoeia with particularly beautiful sounds (like "shitoshito," "kirakira").',
                'Select one famous romantic poem from Hyakunin Isshu and explain its meaning and background in a modern way.',
            ],
        },
        challenge: {
            focus: [['Memorización completa de hiragana y katakana', '100 kanji básicos', 'Estructura oracional japonesa'], ['Todos los patrones de gramática N5', '300 palabras', 'Preparación simulacro N5'], ['Dominio de gramática N4', '800 palabras', 'Preparación simulacro N4'], ['Sistema de gramática N3', '1500 palabras', 'Práctica de lectura intermedia'], ['Patrones de gramática N2', '3000 palabras', 'Lectura larga y comprensión auditiva'], ['Gramática y vocabulario N1', 'Expresiones abstractas', 'Ejercicios prácticos N1'], ['Expresiones ultra-avanzadas', 'Lectura de papers académicos', 'Logro de nivel nativo']],
            skills: [['Dominio completo de hiragana y katakana', 'Leer/escribir 100 kanji básicos'], ['Nivel de aprobación en simulacro N5', 'Responder preguntas básicas'], ['Alcanzado nivel N4', 'Manejar conversaciones diarias'], ['Dentro del rango de aprobación N3', 'Leer titulares de noticias'], ['Resolver problemas nivel N2', 'Entender noticieros'], ['Apuntando a aprobar N1', 'Competente en negocios'], ['Maestro del japonés', 'Usar japonés libremente en cualquier situación']],
            reasons: ['Todo desafío empieza con los fundamentos. Comprende caracteres y estructura para una base sólida.', 'Objetivo: dominio total de N5. Construye gramática y vocabulario sistemáticamente. Verifica con simulacros.', 'Apunta a nivel N4, expandiendo gramática y fortaleciendo conversación simultáneamente.', 'N3 es la puerta al nivel intermedio. Organiza sistemas gramaticales y mejora comprensión lectora rápidamente.', 'N2 prueba habilidad práctica. Mejora estratégicamente lectura larga y comprensión auditiva.', 'N1 es la cima para aprendices. Afronta vocabulario abstracto y patrones gramaticales complejos.', 'Más allá del N1 hacia la maestría real. Libertad total en situaciones académicas, laborales y cotidianas.'],
            textbooks: [['Genki I', 'Kanji Master N5'], ['Shin Kanzen Master N5', 'JLPT N5 Prep'], ['Shin Kanzen Master N4', 'Sou Matome N4'], ['Shin Kanzen Master N3', 'Sou Matome N3'], ['Shin Kanzen Master N2', 'Sou Matome N2'], ['Shin Kanzen Master N1', 'Sou Matome N1'], ['Advanced Reading', 'Learn with News']],
            aiPrompt: [
                'Create 10 conjugation practice questions for N5 essential verbs (iku, taberu, miru) covering present, past, and negative forms.',
                'Explain the difference between N4 grammar "~te wa ikemasen" (prohibition) and "~nakutemo ii desu" (not necessary) with 5 practice questions.',
                'Teach me techniques for "Task-Based Understanding" questions often found in N3 listening tests (reading questions first, taking notes, etc.).',
                'I run out of time in N2 reading. Explain tips for speed reading and how to focus on conjunctions (shikashi, tsumari).',
                'Propose some mnemonics or story memory methods to remember difficult N1 kanji (like "chucho," "kairi").',
                'Give me advice on what to do in the week before the JLPT (daily rhythm, review priorities).',
                'Correct my short essay ([Insert text here]) and rewrite it into more natural, advanced Japanese expressions.',
            ],
        },
        other: {
            focus: [['Hiragana y Katakana', 'Saludos básicos', 'Números y hora'], ['Gramática N5', '200 palabras', 'Oraciones simples'], ['Gramática N4', '500 palabras', 'Keigo básico'], ['Gramática N3', '1000 palabras', 'Lectura intermedia'], ['N3→N2', 'Vocabulario abstracto', 'Textos largos'], ['N2 gramática', 'Japonés de negocios', 'Lectura especializada'], ['Expresiones N1', 'Matices', 'Japonés académico']],
            skills: [['Presentarte', 'Responder preguntas simples'], ['Compras básicas', 'Pedir direcciones'], ['Pedir en restaurantes', 'Escribir correos'], ['Leer titulares', 'Expresar opiniones'], ['Entender noticias', 'Unirte a discusiones'], ['Hablar en reuniones', 'Escribir informes'], ['Leer artículos académicos', 'Dar presentaciones']],
            reasons: ['Dominar escritura japonesa y expresiones esenciales.', 'Japonés mínimo para uso real y conversaciones básicas.', 'Japonés para vida diaria y conversaciones naturales.', 'Expresiones complejas para negocios y academia.', 'Habilidades prácticas para trabajo y estudios.', 'Habilidades avanzadas para uso profesional.', 'Competencia casi nativa en cualquier situación.'],
            textbooks: [['Tae Kim\'s Guide', 'Duolingo'], ['Genki I', 'Anki Core 2k'], ['Genki II', 'NHK Easy Japanese'], ['Tobira Gateway', 'News Web Easy'], ['Tobira Advanced', 'Japanese Novels'], ['New Kanzen Master N1', 'Japanese News'], ['Read Japanese Society', 'Academic Papers']],
            aiPrompt: [
                'Explain the difference between Japanese "wa" and "ga" using simple example sentences a beginner can understand.',
                'Teach me 3 of the most basic and natural ordering phrases to use at restaurants or shops in Japan.',
                'Japanese counters (ippon, ippiki, ichimai) are hard to remember. Teach me the top 5 most used counters and how to remember them.',
                'Create a usage chart for Keigo (Teineigo, Sonkeigo, Kenjougo) showing representative verb changes (iku -> ikimasu, irasshaimasu, mairimasu).',
                'Summarize this recent Japanese news article ([Insert article here]) and rewrite it into simple Japanese a dictionary school student could understand.',
                'Teach me a short script for shadowing practice to improve my pronunciation, along with practice points.',
                'Teach me variations of "Aizuchi" (nodding/responses) Japanese use in conversation ("Hee," "Sou nanda," "Naruhodo") and how to use them.',
            ],
        },
    },
};

