import type { Translations } from './i18n';

export const fr: Translations = {
    title: 'Feuille de Route d\'Apprentissage du Japonais',
    subtitle: 'Créez votre plan d\'étude personnalisé',
    currentLevel: 'Niveau Actuel',
    targetLevel: 'Niveau Cible',
    learningPeriod: 'Période d\'Étude',
    months: ' mois',
    monthUnit: ' mois',
    beginner: 'Débutant',
    native: 'Natif',
    purpose: 'Pourquoi voulez-vous apprendre le japonais ?',
    createRoadmap: '📚 Créer la Feuille de Route',
    selectPurpose: 'Sélectionnez votre objectif',
    levelDescriptions: { n5: 'JLPT N5', n4: 'JLPT N4', n3: 'JLPT N3', n2: 'JLPT N2', n1: 'JLPT N1', nativeLevel: 'Natif' },
    purposes: {
        anime: { label: 'Anime, Manga et Jeux', description: 'Profiter sans sous-titres' },
        friends: { label: 'Se Faire des Amis', description: 'Liens profonds avec des Japonais' },
        travel: { label: 'Voyager au Japon', description: 'Explorer librement' },
        culture: { label: 'Culture Japonaise', description: 'Traditions et gastronomie' },
        live: { label: 'Vivre au Japon', description: 'Vie sûre et confortable' },
        work: { label: 'Travailler au Japon', description: 'Japonais d\'affaires' },
        beauty: { label: 'Le Japonais est Beau', description: 'Sons et caractères fascinants' },
        challenge: { label: 'Défi Personnel', description: 'Curiosité et croissance' },
        other: { label: 'Autre', description: 'Autres objectifs' },
    },
    planSummary: '📊 Résumé de votre Plan',
    totalHours: 'Heures Totales',
    hoursPerWeek: 'hrs/sem',
    levelUp: 'Monter de Niveau',
    current: 'Actuel',
    goal: 'Objectif',
    dailyStudy: 'Environ ',
    hoursUnit: ' heures',
    achievable: ' par jour pour atteindre votre objectif.',
    growthChart: 'Prévision de Croissance',
    now: 'Maintenant',
    monthsLater: 'm après',
    level: 'Niveau',
    lessonDistribution: 'Répartition des Leçons',
    optimizedForYou: 'Équilibre optimisé pour vos objectifs',
    whyThisBalance: 'Pourquoi cet équilibre ?',
    lessonTypes: { grammar: 'Grammaire', vocabulary: 'Vocabulaire', conversation: 'Conversation', reading: 'Lecture', listening: 'Compréhension orale' },
    monthlyMilestones: 'Jalons Mensuels',
    monthN: '',
    targetLevelLabel: 'Objectif',
    purposeStep: 'Étapes vers votre objectif',
    learningContent: '🎯 Focus de ce mois',
    achievedSkills: '✅ Compétences acquises',
    whyThisOrder: '📌 Pourquoi cet ordre ?',
    recommendedLessons: 'Leçons recommandées',
    textbooksLabel: 'Manuels recommandés',
    aiPromptLabel: 'Prompt IA',

    clickToCopy: 'Cliquez pour copier',
    promptCopied: 'Copié !',
    lessonsPerMonth: '/mois',
    roadmapComplete: '🎉 Votre Feuille de Route est Prête !',
    ctaDescription: 'Avec ce plan, vous atteindrez certainement votre objectif.',
    ctaPeriod: ' en ',
    ctaFrom: 'De ',
    ctaTo: ' à ',
    startFreeTrial: '✨ Commencer l\'Essai Gratuit',
    shareThisPlan: 'Partager ce Plan',
    generating: 'Génération...',
    trialBooked: 'Essai gratuit réservé !',
    imageError: 'Échec de génération d\'image',
    shareOpened: 'Menu de partage ouvert',
    downloaded: 'Image téléchargée',
    errorOccurred: 'Une erreur est survenue',
    distributionReasons: {
        anime: { beginner: 'Pour comprendre l\'anime, l\'écoute est clé. Entraînons votre oreille aux expressions familières tout en construisant les bases de grammaire et vocabulaire.', advanced: 'Au-delà de l\'écoute, il faut lire les dialogues de manga et textes de jeux. Focus sur le japonais familier, l\'argot et les onomatopées.' },
        friends: { beginner: 'Pour se connecter, parler vient en premier. Même avec une grammaire simple, pouvoir converser approfondit les relations.', advanced: 'Les relations profondes requièrent de transmettre les nuances avec précision. Pratiquons le passage entre formel et informel.' },
        travel: { beginner: 'Le japonais de voyage : "phrases utilisables maintenant". Priorité au vocabulaire des gares, restaurants et hôtels.', advanced: 'Comprendre les dialectes régionaux et communiquer là où l\'anglais n\'est pas parlé. Lire les panneaux et discuter avec les locaux.' },
        culture: { beginner: 'Comprendre la culture japonaise nécessite de la lecture. Priorité au vocabulaire de l\'étiquette, des événements et de la gastronomie.', advanced: 'Expressions classiques, proverbes, style épistolaire — savourer la profondeur de la culture japonaise.' },
        live: { beginner: '"Japonais de survie" : mairie, hôpitaux, banques, immobilier — tout pour la vie quotidienne.', advanced: 'Relations de voisinage, PTA, associations communautaires. Keigo correct et règles sociales japonaises.' },
        work: { beginner: 'Japonais des affaires : "keigo correct". Emails, téléphone, présentations professionnelles.', advanced: 'Réunions, présentations, négociations, rapports — japonais qui inspire confiance professionnelle.' },
        beauty: { beginner: 'Pour apprécier le beau japonais, commençons par les caractères. Tracés hiragana/katakana, origines du kanji, rythme du japonais.', advanced: 'Haiku, tanka, expressions poétiques, vocabulaire saisonnier — l\'essence de la beauté japonaise.' },
        challenge: { beginner: 'Croissance équilibrée de toutes les compétences. Comprendre logiquement la structure du japonais.', advanced: 'Préparation JLPT : améliorer lecture et écoute. Grammaire avancée et vocabulaire abstrait.' },
        other: { beginner: 'Plan équilibré pour 5 compétences. Partagez vos objectifs lors de la leçon gratuite !', advanced: 'Plan complet pour toutes les compétences. Personnalisation disponible lors de la leçon gratuite !' },
    },
    purposeMilestones: {
        anime: ['Lire les paroles d\'openings 🎵', 'Capter les salutations simples dans l\'anime 👂', 'Comprendre 80% de l\'anime sous-titré 📺', 'Suivre un épisode sans sous-titres 🎉', 'Jouer aux jeux japonais sans dictionnaire 🎮', 'Lire le manga en japonais original 📖', 'Comprendre les dialogues complexes et nuances ✨'],
        friends: ['Se présenter et parler de hobbies 👋', 'Échanger des messages sur LINE 📱', 'Discuter au café pendant 30 minutes ☕', 'Exprimer sentiments et opinions 💬', 'Comprendre les blagues et rire ensemble 😄', 'Parler de sujets profonds 🤝', 'Se disputer et se réconcilier en japonais 💪'],
        travel: ['Lire les panneaux de gare 🚃', 'Commander et payer au restaurant 🍣', 'Demander et comprendre les directions 🗺️', 'Discuter avec le personnel du ryokan ♨️', 'Comprendre les dialectes régionaux 🏔️', 'Voyager seul sans guide 🎒', 'Se lier d\'amitié avec les locaux 🌸'],
        culture: ['Utiliser les bonnes manières 🙇', 'Connaître les fêtes japonaises 🎎', 'Expliquer la cuisine japonaise 🍱', 'Comprendre les termes du thé 🍵', 'Discuter l\'histoire japonaise 🏯', 'Apprécier haiku et tanka 📝', 'Profiter de la culture au niveau natif 🌊'],
        live: ['Faire ses courses sans problème 🏪', 'Gérer les démarches administratives 📋', 'Décrire ses symptômes à l\'hôpital 🏥', 'Discuter avec les voisins 🏘️', 'Comprendre les contrats bancaires 📄', 'Participer aux réunions PTA 🤝', 'Vivre au Japon de façon autonome 🏠'],
        work: ['Salutations professionnelles et cartes de visite 💼', 'Écrire des emails professionnels ✉️', 'Gérer les appels téléphoniques 📞', 'Présenter ses idées en réunion 🎤', 'Négocier sans interprète 🤝', 'Faire des présentations en japonais 📊', 'Diriger une équipe en japonais 🏆'],
        beauty: ['Écrire hiragana/katakana joliment ✍️', 'Maîtriser les tracés de 50 kanji 📝', 'Apprécier la beauté du keigo 🌸', 'Écrire des lettres élégantes ✉️', 'Essayer d\'écrire des haiku 🖊️', 'Distinguer les nuances subtiles ✨', 'Apprécier pleinement les sons japonais 🎵'],
        challenge: ['Maîtriser hiragana, katakana et kanji de base 🏅', 'Résoudre des exercices N5 📚', 'Atteindre le niveau N4 🎯', 'Entrer dans la zone N3 💪', 'Prêt pour le N2 🔥', 'Viser le N1 🏆', 'Maître du japonais ! Quelle langue ensuite ? 🌍'],
        other: ['Base solide en japonais 📖', 'Conversations quotidiennes simples 💬', 'Exprimer ses idées en japonais ✍️', 'Chercher des infos en japonais 🔍', 'Converser sur divers sujets 🗣️', 'Comprendre du contenu spécialisé 📊', 'Utiliser le japonais naturellement ✨'],
    },
    monthlyContent: {
        focus: [['Hiragana et Katakana', 'Salutations de base', 'Nombres et heure'], ['Grammaire N5', '200 mots', 'Phrases simples'], ['Grammaire N4', '500 mots', 'Keigo de base'], ['Grammaire N3', '1000 mots', 'Lecture intermédiaire'], ['N3→N2', 'Vocabulaire abstrait', 'Textes longs'], ['Grammaire N2', 'Japonais d\'affaires', 'Lecture spécialisée'], ['Expressions N1', 'Nuances', 'Japonais académique']],
        skills: [['Se présenter', 'Répondre aux questions simples'], ['Achats de base', 'Demander son chemin'], ['Commander au restaurant', 'Écrire des emails'], ['Lire les titres', 'Exprimer ses opinions'], ['Comprendre les infos TV', 'Participer aux discussions'], ['Parler en réunion', 'Écrire des rapports'], ['Lire des articles académiques', 'Faire des présentations']],
        reasons: ['Maîtriser l\'écriture japonaise et les expressions essentielles.', 'Japonais minimum pour usage réel et conversations de base.', 'Japonais pour la vie quotidienne et conversations naturelles.', 'Expressions complexes pour les affaires et l\'académique.', 'Compétences pratiques pour le travail et les études.', 'Compétences avancées pour usage professionnel.', 'Compétence quasi native pour toute situation.'],
    },
    purposeMonthlyContent: {
        anime: {
            focus: [['Salutations d\'anime', 'Noms en katakana', 'Hiragana/katakana'], ['50 phrases d\'anime', 'Vocabulaire anime quotidien', 'Écoute de dialogues'], ['Conversation quotidienne', 'Dialogues manga', 'Onomatopées'], ['Familier vs. formel', 'UI de jeux', 'Émotions anime'], ['Termes de genre', 'Guides de jeux', 'Argot jeune'], ['Intrigues complexes', 'Light novels', 'Dialectes'], ['Métaphores littéraires', 'Analyses d\'anime', 'Vitesse native']], skills: [['Lire paroles d\'opening', 'Prononcer noms de personnages'], ['Comprendre exclamations', 'Capter salutations anime'], ['Lire dialogues manga', 'Comprendre 50% anime sous-titré'], ['Comprendre 80% anime sous-titré', 'Lire textes RPG'], ['Suivre anime sans sous-titres', 'Jouer en japonais'], ['Profiter manga original', 'Comprendre métaphores'], ['Compréhension totale nuances', 'Discuter anime en japonais']], reasons: ['Lire les paroles et noms maintient la motivation.', 'Expressions familières d\'anime pour compétences pratiques.', 'Écoute + lecture pour booster votre japonais anime.', 'Maîtriser le changement familier-formel.', 'Jargon de genre pour visionner sans sous-titres.', 'Comprendre dialectes et structures narratives profondes.', 'Profiter au même niveau qu\'un natif.'],
            textbooks: [['Genki I', 'Anime Scripts'], ['Genki II', 'Yotsuba&! (Manga)'], ['Quartet I', 'Slice of Life Anime Scripts'], ['Quartet II', 'Shonen Manga (with Furigana)'], ['Tobira', 'RPG Game Scripts'], ['Shin Kanzen Master N1', 'Light Novels (Easy)'], ['Native Materials', 'Anime Scenarios']],
            aiPrompt: [
                'You are a Japanese teacher who loves anime. Teach me 5 basic greeting phrases a beginner should know, speaking in an energetic tone like Luffy from One Piece.',
                'Explain the nuance and usage of sentence endings like "~daze" and "~kashira" often found in anime, with character dialogue examples.',
                'Analyze the polite yet strong speaking style of Tanjiro from Demon Slayer and create 3 phrases I can use in daily life.',
                'Create 5 "tsundere" lines for an anime character, explaining the grammatical structure and emotional nuance of each.',
                'List 20 important words related to "magic," "equipment," and "adventure" frequent in fantasy RPGs, with example sentences.',
                'Reproduce lines of an anime character using Kyoto dialect (Kansai-ben) and explain the difference from standard Japanese.',
                'Write a philosophical monologue in Japanese like in "Neon Genesis Evangelion" and explain the abstract vocabulary used.',
            ],
        },
        friends: {
            focus: [['Autopresentation', 'Salutations décontractées', 'Hiragana/katakana'], ['Expressions LINE/SNS', 'Vocabulaire loisirs', 'Aizuchi'], ['Basculer décontracté-formel', 'Émotions', 'Inviter/décliner'], ['Opinions', 'Humour', 'Casual vs. keigo'], ['Soucis/conseils', 'Nuances subtiles', 'Lire l\'ambiance'], ['Débat', 'Sujets profonds', 'Dialectes'], ['Sarcasme/figuré', 'Valeurs japonaises', 'Vitesse native']], skills: [['Se présenter et hobbies', 'Salutations "yoroshiku"'], ['Chatter LINE', 'Questions sur hobbies'], ['30 min conversation', 'Inviter/décliner'], ['Exprimer sentiments', 'Faire rire'], ['Discuter soucis', 'Lire l\'ambiance'], ['Conversations profondes', 'Dialectes'], ['Se disputer/réconcilier', 'Égalité avec natifs']], reasons: ['La présentation commence les amitiés.', 'LINE est la base de l\'amitié moderne.', 'Endurance pour les discussions de café.', 'Exprimer sentiments + humour pour des conversations engageantes.', 'Comprendre "lire l\'ambiance" pour la confiance.', 'Débattre de sujets profonds — niveau meilleur ami.', 'Conversation naturelle et égale avec les natifs.'],
            textbooks: [['Genki I', 'HelloTalk'], ['Genki II', 'LINE Stickers Japanese'], ['Tsunagu Nihongo', 'Tandem'], ['Quartet I', 'Japanese Dramas (Subtitled)'], ['Quartet II', 'Japanese Variety Shows'], ['Tobira', 'Japanese YouTubers'], ['Native Materials', 'Sharehouse Conversations']],
            aiPrompt: [
                'I want to make friends with a Japanese person I just met. Teach me 3 self-introduction phrases that are friendly but not rude.',
                'Create two examples of natural LINE messages to invite someone to dinner: one for a "close friend" and one for "someone I just met."',
                'Teach me the positive and negative nuances of slang words young people use like "maji-de" and "yabai," with example sentences.',
                'List 10 empathetic Japanese phrases (like "That must have been hard") I can use when listening to a friend\'s worries.',
                'Explain what "reading the air" specifically means using a Japanese drinking party situation as an example.',
                'Teach me phrases to exchange opinions on recent news with a friend, like "I think this, but what do you think?"',
                'Teach me some Japanese jokes or "dad jokes" (oyaji gag) and explain why they are funny (wordplay, etc.).',
            ],
        },
        travel: {
            focus: [['Panneaux gare/aéroport', 'Nombres/heure/jours', 'Hiragana/katakana'], ['Commander au restaurant', 'Check-in hôtel', 'Directions'], ['Correspondances', 'Prix shopping', 'Questions tourisme'], ['Manières ryokan', 'Spécialités locales', 'Météo/santé'], ['Dialectes régionaux', 'Sites historiques', 'Discuter locaux'], ['Blogs/avis voyage', 'Réservations tél.', 'Urgences'], ['Dialectes voyage', 'Connexions profondes', 'Culture japonaise']], skills: [['Lire panneaux gare', 'Comprendre nombres'], ['Commander/payer restaurant', 'Destination taxi'], ['Correspondances train', 'Confirmer prix'], ['Conversations ryokan', 'Décrire symptômes'], ['Comprendre dialectes', 'Discuter locaux'], ['Réservations tél.', 'Planifier avec avis'], ['Voyage solo indépendant', 'Lieux secrets locaux']], reasons: ['Panneaux et nombres en priorité.', 'Phrases utilisables maintenant pour restaurants/hôtels.', 'Indépendance transport et shopping.', '"Omotenashi" double la joie du voyage.', 'Dialectes pour conversations naturelles avec locaux.', 'Voyageur autonome : recherche et réservations.', 'Voyageur avancé connecté avec les locaux.'],
            textbooks: [['Phrasebook', 'Google Maps'], ['Travel Japanese', 'Train Timetables'], ['Japan Travel Survival', 'Tabelog'], ['Omotenashi Japanese', 'Ryokan Booking Sites'], ['Dialect Chart', 'Rurubu (Travel Mag)'], ['Jalan (Booking Site)', 'Shinkansen App'], ['National Guides', 'Local Newspapers']],
            aiPrompt: [
                'I am lost at a station in Japan. Teach me a polite phrase to ask station staff "How to get to Shinjuku Station" and "How long it takes."',
                'I entered a restaurant in Japan. Create a phrase to say I have an allergy (e.g., shrimp) and ask for a menu without it.',
                'Explain basic manners I should know when staying at a Ryokan (taking off shoes, hot spring etiquette) in simple Japanese.',
                'Simulate a conversation where I ask a shop clerk "What do you recommend?" and ask for the reason.',
                'I am traveling to Kansai (Osaka/Kyoto). Teach me 5 simple Kansai-ben phrases (like "ookini") to use with shop staff.',
                'I want to book a restaurant by phone. Create a script saying "I would like to make a reservation for 2 people at 7 PM next Saturday."',
                'Think of 3 slightly intellectual mock questions to ask a guide about history when visiting Japanese castles or temples.',
            ],
        },
        culture: {
            focus: [['Étiquette de base', 'Cuisine japonaise', 'Hiragana/katakana'], ['Événements annuels', 'Culture culinaire', 'Salutations saison'], ['Thé/fleurs', 'Types kimono', 'Artisanat'], ['Histoire japonaise', 'Shinto/bouddhisme', 'Waka'], ['Littérature classique', 'Proverbes', 'Calligraphie'], ['Noh/Kabuki', 'Art japonais', 'Haiku/saison'], ['Textes classiques', 'Débat culturel', 'Esthétique']], skills: [['Types de révérence', 'Étiquette baguettes'], ['Fêtes japonaises', 'Manières washoku'], ['Cérémonie du thé', 'Kimonos/occasions'], ['Histoire japonaise', 'Temple vs sanctuaire'], ['Proverbes quotidiens', 'Règles haiku'], ['Arts traditionnels', 'Art japonais'], ['Littérature classique originale', 'Discussion culture profonde']], reasons: ['Étiquette et cuisine sont la porte de la culture.', 'Événements saisonniers pour comprendre la nature.', 'Culture du "chemin" et "wabi-sabi".', 'Histoire et religion transforment l\'expérience culturelle.', 'Proverbes et sagesse culturelle du japonais.', 'Des arts scéniques aux beaux-arts japonais.', 'Lire les classiques en original comme un natif.'],
            textbooks: [['Intro to Japanese Culture', 'Chopstick Tutorials'], ['Japanese Annual Events', 'Japanese Calendar'], ['Tea Ceremony Intro', 'Traditional Crafts Guide'], ['Japanese History Manga', 'Shrine Test Text'], ['Children\'s Analects', 'Hyakunin Isshu'], ['Kabuki Guide', 'Art History Intro'], ['Tale of Genji (Original/Modern)', 'Fushikaden']],
            aiPrompt: [
                'Explain the difference between Japanese bows (eshaku, keirei, saikeirei) and when to use each.',
                'Teach me Japanese phrases to explain the spiritual meaning of "Itadakimasu" and "Gochisousama" to foreigners.',
                'Briefly explain the Japanese aesthetic of "Wabi-Sabi" in Japanese, using moss or tea bowls as examples.',
                'Compare the differences between shrines and temples (worship methods, what is enshrined) and create a word list for each.',
                'Explain the meaning of the famous proverb "Ishi no ue ni mo sannen" and modern situations where it is used.',
                'I am going to see Kabuki for the first time. Teach me 3 points a beginner should know about unique calls and how to enjoy it.',
                'Explain the modern translation of the opening of "The Tale of Genji" and its unique atmosphere and cultural background.',
            ],
        },
        live: {
            focus: [['Panneaux magasins', 'Adresses', 'Hiragana/katakana'], ['Procédures mairie', 'Compte bancaire', 'Hôpital'], ['Contrat location', 'Électricité/gaz/eau', 'Courrier'], ['Association quartier', 'École', 'Assurance/retraite'], ['Déclaration fiscale', 'Immobilier', 'PTA/communauté'], ['Termes juridiques', 'Carrière', 'Aide enfance'], ['Admin générale', 'Civique/bénévolat', 'Société japonaise']], skills: [['Courses supérette', 'Écrire adresse'], ['Formulaires mairie', 'Ouvrir compte'], ['Points clés contrat', 'Factures services'], ['Discuter voisins', 'Lettres école'], ['Documents fiscaux', 'Activités communautaires'], ['Droits légaux', 'Chercher emploi'], ['Intégration complète', 'Admin autonome']], reasons: ['Vie au Japon : supérettes et adresses en priorité.', 'Infrastructure vitale : mairie, banque, hôpital.', 'Stabiliser la base de vie avec contrats et services.', 'S\'intégrer dans la communauté locale.', 'Connaissances à long terme : impôts et communauté.', 'Japonais avancé pour carrière et droit.', 'Intégration complète dans la société japonaise.'],
            textbooks: [['Japanese for Life', 'Supermarket Flyers'], ['City Hall Guide', 'Medical Japanese'], ['Reading Contracts', 'Rental Sites'], ['PTA Handbook', 'Circular Notices'], ['Tax Return Guide', 'Disaster Maps'], ['Business Law Intro', 'Hello Work Job Slips'], ['Understanding Japanese Society', 'Newspaper Editorials']],
            aiPrompt: [
                'Reproduce a natural interaction at a Japanese convenience store asking to warm up a bento and get chopsticks and a bag.',
                'Simulate a conversation at a hospital reception to convey "I have had a fever since yesterday and my throat hurts."',
                'I am looking for an apartment at a real estate agency. Create a dialogue conveying "Rent under 70,000 yen, within 10 min walk from station."',
                'Garbage sorting rules are confusing. Teach me a conversation to ask a neighbor "Which day should I put out this plastic?"',
                'Write a polite message for a child\'s school contact book saying "He will be absent tomorrow due to a cold."',
                'Explain basic keywords beginners should know about year-end tax adjustment and tax returns in Japan (deductions, withholding, etc.).',
                'Think of a self-introduction speech for a neighborhood association meeting saying "I am still studying Japanese, but nice to meet you."',
            ],
        },
        work: {
            focus: [['Salutations affaires', 'Cartes de visite', 'Hiragana/katakana'], ['Emails modèles', 'Téléphone', 'Présentation entreprise'], ['Procès-verbaux', 'Ho-Ren-So', 'Keigo'], ['Présentations', 'Réunions', 'Négociation'], ['Contrats', 'Rapports', 'Politique interne'], ['Stratégie', 'IR/finances', 'Leadership'], ['Niveau cadre', 'M&A/juridique', 'Discours']], skills: [['Échanger cartes', 'Saluer en affaires'], ['Emails modèles', 'Transférer appels'], ['Procès-verbaux', 'Ho-Ren-So supérieurs'], ['Opinions en réunion', 'Créer présentations'], ['Comprendre contrats', 'Rapports japonais'], ['Réunions direction', 'Diriger en japonais'], ['Présenter dirigeants', 'Tout en japonais']], reasons: ['Première impression : salutations et cartes.', 'Emails et téléphone pour productivité immédiate.', 'Ho-Ren-So : communication avec collègues.', 'Expression renforcée en réunions et présentations.', 'Documents précis pour confiance professionnelle.', 'Japonais managérial pour gestion et stratégie.', 'Plus haut niveau de japonais d\'affaires.'],
            textbooks: [['Keigo Training', 'Business Card Manners'], ['Business Writing', 'Phone Manuals'], ['Manga Ho-Ren-So', 'Meeting Japanese'], ['Presentation Japanese', 'Logical Speaking'], ['Business Contracts', 'Internal Reports'], ['Nikkei Business', 'Drucker (JP Ver)'], ['HBR Japan', 'Corporate Law']],
            aiPrompt: [
                'Teach me the correct step-by-step procedure for exchanging business cards in Japan, with dialogue.',
                'Create an example of a polite business email asking a client "I would like to change the meeting date."',
                'Create an appropriate conversation flow for reporting progress to a boss (Ho-Ren-So) starting with "Actually, there is a problem..."',
                'Teach me 5 variations of phrases to point out concerns in a meeting while agreeing, like "I agree basically, but just one point..."',
                'Explain the usage of "Osewa ni natte orimasu," "Otsukaresama desu," and "Gokurosama desu" and their NG scenes.',
                'Create an opening speech for a business presentation that apologizes for a project failure but proposes improvements sincerely.',
                'Teach me ideal praise words a Japanese boss uses to motivate subordinates (like "Sasuga da ne, kitai ijo da yo").',
            ],
        },
        beauty: {
            focus: [['Tracés hiragana', 'Origines katakana', 'Sons japonais'], ['50 kanji tracés', 'On/kun\'yomi', 'Onomatopées'], ['Radicaux kanji', 'Belle écriture', 'Vocabulaire saison'], ['Keigo et beauté', 'Lettres', 'Couleurs traditionnelles'], ['Haiku règles', 'Waka', 'Calligraphie'], ['Tanka/poésie', 'Japonais classique', 'Rythme phonétique'], ['Expression littéraire', 'Calligraphie maîtrise', 'Esthétique japonaise']], skills: [['Écrire hiragana joliment', 'Beauté voyelles'], ['50 kanji tracés corrects', 'Origines kanji'], ['Sens par radicaux', 'Lettres saisonnières'], ['Keigo élégant', 'Lettres raffinées'], ['Composer haiku', 'Images waka'], ['Créer tanka', 'Beauté classique'], ['Beauté sonore complète', 'Art calligraphique']], reasons: ['Caractères et son : la beauté commence là.', 'Origines kanji : profondeur par caractère.', 'Kanji systématique et mots saisonniers.', 'Keigo : cristallisation de la beauté.', 'Haiku/waka : 17 et 31 syllabes de beauté.', 'Création littéraire et japonais classique.', 'Étape finale : son, forme et sens.'],
            textbooks: [['Calligraphy Practice', 'Hiragana Chart'], ['Kanji Origins', 'Beautiful Words Dict'], ['Japanese Colors', 'Seasonal Words'], ['Aesthetics of Keigo', 'Letter Writing'], ['Haiku Almanac', 'Manyoshu Intro'], ['Kokin Wakashu', 'Tale of the Bamboo Cutter'], ['Tale of Genji', 'Pillow Book']],
            aiPrompt: [
                'Teach me tips to write hiragana "a" and "no" beautifully and balanced, relating them to shapes (triangle, circle).',
                'Introduce 5 beautiful Japanese words related to "rain" (samidare, shigure, etc.) and explain the scenery of each.',
                'Teach me seasonal greetings (jikou no aisatsu) used in letter openings like "Haikei, sakura no kisetsu..." for each of the 4 seasons.',
                'Introduce some Japanese expressions that convey love indirectly and elegantly, like "The moon is beautiful, isn\'t it?"',
                'I want to make Haiku. Create and explain 3 beginner examples using "Summer" and "Sea" as themes.',
                'Select 10 Japanese onomatopoeia with particularly beautiful sounds (like "shitoshito," "kirakira").',
                'Select one famous romantic poem from Hyakunin Isshu and explain its meaning and background in a modern way.',
            ],
        },
        challenge: {
            focus: [['Hiragana/katakana complets', '100 kanji', 'Structure phrase'], ['Grammaire N5 complète', '300 mots', 'Examen blanc N5'], ['Grammaire N4', '800 mots', 'Examen blanc N4'], ['Grammaire N3', '1500 mots', 'Lecture intermédiaire'], ['Grammaire N2', '3000 mots', 'Lecture longue/écoute'], ['Grammaire N1', 'Abstrait', 'Exercices N1'], ['Ultra-avancé', 'Articles académiques', 'Niveau natif']], skills: [['Hiragana/katakana maîtrisés', '100 kanji lire/écrire'], ['Examen blanc N5 réussi', 'Questions de base'], ['Niveau N4 atteint', 'Conversation quotidienne'], ['Zone N3', 'Titres de journaux'], ['Problèmes N2', 'Comprendre JT'], ['Viser N1', 'Compétent affaires'], ['Maître japonais', 'Libre en toute situation']], reasons: ['Les fondamentaux d\'abord pour une base solide.', 'Maîtrise N5 : grammaire et vocabulaire systématiques.', 'Niveau N4 : grammaire élargie + conversation.', 'N3 : porte intermédiaire, compréhension écrite.', 'N2 : preuve d\'aptitude pratique.', 'N1 : sommet, vocabulaire abstrait et grammaire complexe.', 'Au-delà du N1 : liberté totale.'],
            textbooks: [['Genki I', 'Kanji Master N5'], ['Shin Kanzen Master N5', 'JLPT N5 Prep'], ['Shin Kanzen Master N4', 'Sou Matome N4'], ['Shin Kanzen Master N3', 'Sou Matome N3'], ['Shin Kanzen Master N2', 'Sou Matome N2'], ['Shin Kanzen Master N1', 'Sou Matome N1'], ['Advanced Reading', 'Learn with News']],
            aiPrompt: [
                'Create 10 conjugation practice questions for N5 essential verbs (iku, taberu, miru) covering present, past, and negative forms.',
                'Explain the difference between N4 grammar "~te wa ikemasen" (prohibition) and "~nakutemo ii desu" (not necessary) with 5 practice questions.',
                'Teach me techniques for "Task-Based Understanding" questions often found in N3 listening tests (reading questions first, taking notes, etc.).',
                'I run out of time in N2 reading. Explain tips for speed reading and how to focus on conjunctions (shikashi, tsumari).',
                'Propose some mnemonics or story memory methods to remember difficult N1 kanji (like "chucho," "kairi").',
                'Give me advice on what to do in the week before the JLPT (daily rhythm, review priorities).',
                'Correct my short essay ([Insert text here]) and rewrite it into more natural, advanced Japanese expressions.',
            ],
        },
        other: {
            focus: [['Hiragana et Katakana', 'Salutations de base', 'Nombres et heure'], ['Grammaire N5', '200 mots', 'Phrases simples'], ['Grammaire N4', '500 mots', 'Keigo de base'], ['Grammaire N3', '1000 mots', 'Lecture intermédiaire'], ['N3→N2', 'Vocabulaire abstrait', 'Textes longs'], ['Grammaire N2', 'Japonais d\'affaires', 'Lecture spécialisée'], ['Expressions N1', 'Nuances', 'Japonais académique']], skills: [['Se présenter', 'Répondre aux questions simples'], ['Achats de base', 'Demander son chemin'], ['Commander au restaurant', 'Écrire des emails'], ['Lire les titres', 'Exprimer ses opinions'], ['Comprendre les infos TV', 'Participer aux discussions'], ['Parler en réunion', 'Écrire des rapports'], ['Lire des articles académiques', 'Faire des présentations']], reasons: ['Maîtriser l\'écriture japonaise et expressions essentielles.', 'Japonais minimum pour usage réel et conversations de base.', 'Japonais pour vie quotidienne et conversations naturelles.', 'Expressions complexes pour affaires et académique.', 'Compétences pratiques pour travail et études.', 'Compétences avancées pour usage professionnel.', 'Compétence quasi native pour toute situation.'],
            textbooks: [['Tae Kim\'s Guide', 'Duolingo'], ['Genki I', 'Anki Core 2k'], ['Genki II', 'NHK Easy Japanese'], ['Tobira Gateway', 'News Web Easy'], ['Tobira Advanced', 'Japanese Novels'], ['New Kanzen Master N1', 'Japanese News'], ['Read Japanese Society', 'Academic Papers']],
            aiPrompt: [
                'Explain the difference between Japanese "wa" and "ga" using simple example sentences a beginner can understand.',
                'Teach me 3 of the most basic and natural ordering phrases to use at restaurants or shops in Japan.',
                'Japanese counters (ippon, ippiki, ichimai) are hard to remember. Teach me the top 5 most used counters and how to remember them.',
                'Create a usage chart for Keigo (Teineigo, Sonkeigo, Kenjougo) showing representative verb changes (iku -> ikimasu, irasshaimasu, mairimasu).',
                'Summarize this recent Japanese news article ([Insert article here]) and rewrite it into simple Japanese a dictionary school student could understand.',
                'Teach me a short script for shadowing practice to improve my pronunciation, along with practice points.',
                'Teach me variations of "Aizuchi" (nodding/responses) Japanese use in conversation ("Hee," "Sou nanda," "Naruhodo") and how to use them.',
            ],
        },
    },
};

