import type { Translations } from './i18n';

export const ko: Translations = {
    title: '일본어 학습 로드맵',
    subtitle: '맞춤형 학습 플랜을 만들어 드립니다',
    currentLevel: '현재 레벨',
    targetLevel: '목표 레벨',
    learningPeriod: '학습 기간',
    months: '개월',
    monthUnit: '개월',
    beginner: '초급',
    native: '원어민',
    purpose: '일본어를 배우는 이유는?',
    createRoadmap: '📚 로드맵 생성',
    selectPurpose: '목적을 선택해 주세요',
    levelDescriptions: { n5: 'N5 레벨', n4: 'N4 레벨', n3: 'N3 레벨', n2: 'N2 레벨', n1: 'N1 레벨', nativeLevel: '원어민' },
    purposes: {
        anime: { label: '애니메·만화·게임', description: '자막 없이 즐기고 싶어' },
        friends: { label: '친구·연인 만들기', description: '일본인과 깊은 관계 만들기' },
        travel: { label: '여행 즐기기', description: '자유롭게 일본 여행' },
        culture: { label: '일본 문화 좋아', description: '전통·사계절·음식문화' },
        live: { label: '일본에 살고 싶어', description: '안전하고 편안한 생활' },
        work: { label: '일본에서 일하고 싶어', description: '비즈니스 일본어' },
        beauty: { label: '일본어가 아름다워', description: '소리와 문자의 매력' },
        challenge: { label: '자기 도전', description: '지적 호기심·자기 성장' },
        other: { label: '기타', description: '기타 목적' },
    },
    planSummary: '📊 학습 플랜 개요',
    totalHours: '총 학습 시간',
    hoursPerWeek: '시간/주',
    levelUp: '레벨업',
    current: '현재',
    goal: '목표',
    dailyStudy: '하루 약 ',
    hoursUnit: '시간',
    achievable: '의 학습으로 달성 가능!',
    growthChart: '성장 예측 그래프',
    now: '현재',
    monthsLater: '개월 후',
    level: '레벨',
    lessonDistribution: '추천 레슨 배분',
    optimizedForYou: '목표에 최적화된 학습 밸런스',
    whyThisBalance: '왜 이 배분인가요?',
    lessonTypes: { grammar: '문법', vocabulary: '어휘', conversation: '회화', reading: '독해', listening: '청해' },
    monthlyMilestones: '월별 마일스톤',
    monthN: '개월차',
    targetLevelLabel: '목표',
    purposeStep: '목표에 한 발 더 가까이',
    learningContent: '🎯 이번 달 학습 내용',
    achievedSkills: '✅ 달성 스킬',
    whyThisOrder: '📌 왜 이 순서인가요?',
    recommendedLessons: '추천 레슨 횟수',
    textbooksLabel: '추천 교재',
    aiPromptLabel: 'AI 프롬프트',

    clickToCopy: '탭하여 복사',
    promptCopied: '복사했습니다',
    lessonsPerMonth: '회/월',
    roadmapComplete: '🎉 맞춤 로드맵 완성!',
    ctaDescription: '이 플랜이라면 확실히 목표 달성 가능합니다.',
    ctaPeriod: ', ',
    ctaFrom: '',
    ctaTo: '에서 ',
    startFreeTrial: '✨ 무료 체험 시작',
    shareThisPlan: '플랜 공유하기',
    generating: '생성 중...',
    trialBooked: '무료 체험 예약 완료!',
    imageError: '이미지 생성 실패',
    shareOpened: '공유 메뉴 열림',
    downloaded: '이미지 다운로드 완료',
    errorOccurred: '오류가 발생했습니다',
    distributionReasons: {
        anime: { beginner: '애니메 일본어를 이해하려면 듣기가 핵심입니다. 캐릭터의 구어체와 독특한 표현을 듣는 귀를 키우면서 기초 문법과 어휘를 다집니다.', advanced: '듣기 외에 만화 대사와 게임 텍스트를 읽는 능력도 중요합니다. 구어·슬랭·의성어 등 살아있는 일본어를 중점적으로 배웁니다.' },
        friends: { beginner: '사람과 연결하려면 "말하는 능력"이 최우선. 간단한 문법이라도 대화를 주고받을 수 있으면 관계가 깊어집니다.', advanced: '깊은 관계에는 뉘앙스와 감정을 정확히 전달하는 능력이 필요합니다. 존댓말과 반말 구분, "분위기 읽기" 문화를 연습합니다.' },
        travel: { beginner: '여행에서 가장 많이 쓰는 건 "바로 쓸 수 있는 실전 표현". 역·식당·호텔 어휘와 현지인에게 질문하는 회화력을 우선 익힙니다.', advanced: '지방 방언 이해와 영어가 안 통하는 지역에서의 커뮤니케이션 능력을 키웁니다. 간판 읽기와 현지인과의 대화에 집중합니다.' },
        culture: { beginner: '일본 문화를 깊이 이해하려면 읽기 능력이 중요합니다. 예의범절, 연중행사, 음식문화 관련 어휘를 우선 익힙니다.', advanced: '고전적 표현, 속담, 편지 쓰기 등 일본 문화의 깊이를 맛볼 수 있는 수준을 목표로 합니다.' },
        live: { beginner: '일본 생활에 필요한 "서바이벌 일본어" 우선. 관공서, 병원, 은행, 부동산 등 생활 인프라 관련 어휘와 회화를 폭넓게 배웁니다.', advanced: '이웃 관계, PTA, 자치회 등 일본 사회에 녹아드는 커뮤니케이션 능력을 강화합니다.' },
        work: { beginner: '비즈니스 일본어의 기초는 "올바른 존댓말". 이메일 작성, 전화 응대, 자기소개 등 실무에서 바로 쓸 수 있는 스킬을 우선 습득합니다.', advanced: '회의 발언, 프레젠테이션, 협상, 보고서 작성 등 프로로서 신뢰받는 일본어 능력을 갈고닦습니다.' },
        beauty: { beginner: '아름다운 일본어를 맛보려면 문자의 세계부터. 히라가나·가타카나 획순, 한자의 유래, 일본어의 소리 리듬을 정성스럽게 배웁니다.', advanced: '하이쿠, 단카, 시적 표현, 사계절 어휘 등 일본어 아름다움의 진수에 닿습니다.' },
        challenge: { beginner: '모든 스킬을 균형 있게 키우는 것이 가장 효율적입니다. 언어학적 관점도 함께하면서 일본어 구조를 논리적으로 이해합니다.', advanced: 'JLPT 시험 대비를 축으로 독해·청해 점수 향상을 노립니다. 고급 문법 패턴과 추상적 어휘에 도전합니다.' },
        other: { beginner: '5가지 스킬을 균형 있게 키우는 종합 플랜입니다. 무료 레슨에서 구체적 목표를 들려주세요!', advanced: '모든 스킬을 균등하게 강화하는 종합 향상 플랜입니다. 무료 레슨에서 상담해 주세요!' },
    },
    purposeMilestones: {
        anime: ['애니 오프닝 가사를 읽을 수 있다 🎵', '일상 애니의 간단한 인사·대사를 알아듣는다 👂', '자막 있는 애니 내용의 80%를 이해한다 📺', '자막 없이 일상 애니 1화의 대략을 이해한다 🎉', '일본어 게임을 사전 없이 플레이한다 🎮', '만화 원작을 그대로 읽고 즐긴다 📖', '애니의 복잡한 대사와 뉘앙스까지 이해한다 ✨'],
        friends: ['자기소개와 취미 이야기를 할 수 있다 👋', 'LINE으로 간단한 메시지 교환을 한다 📱', '카페에서 30분간 수다를 떨 수 있다 ☕', '자신의 감정과 의견을 일본어로 전달한다 💬', '농담을 이해하고 함께 웃을 수 있다 😄', '고민 상담과 깊은 화제로 대화한다 🤝', '일본어로 싸우고 화해할 수 있다 (진정한 친구!) 💪'],
        travel: ['역 안내와 간판을 읽을 수 있다 🚃', '식당에서 주문·계산을 한다 🍣', '길을 묻고 답을 이해한다 🗺️', '온천 료칸에서 직원과 대화를 즐긴다 ♨️', '지방에서 방언을 대체로 이해한다 🏔️', '혼자서 자유여행을 할 수 있다 🎒', '현지인과 친해져 숨겨진 명소를 소개받는다 🌸'],
        culture: ['기본 예절과 인사를 올바르게 할 수 있다 🙇', '일본 공휴일과 전통 행사를 알고 있다 🎎', '일본 음식 이름과 식사 매너를 설명한다 🍱', '다도·꽃꽂이의 기본 용어를 이해한다 🍵', '일본의 역사와 가치관을 토론한다 🏯', '하이쿠와 단카의 기초를 이해하고 감상한다 📝', '일본 문화를 원어민과 같은 깊이로 즐긴다 🌊'],
        live: ['편의점·마트 쇼핑 문제없다 🏪', '관공서 간단한 수속을 혼자 할 수 있다 📋', '병원에서 증상을 전달할 수 있다 🏥', '집주인·이웃과 잡담할 수 있다 🏘️', '은행·보험·통신 계약서를 이해한다 📄', 'PTA와 자치회 모임에 참가한다 🤝', '일본 사회에 완전히 녹아들어 불편 없이 생활한다 🏠'],
        work: ['비즈니스 기본 인사와 명함 교환 💼', '간단한 비즈니스 이메일 작성 ✉️', '기본 전화 응대 📞', '회의에서 의견 발표 🎤', '통역 없이 거래처와 상담 🤝', '일본어로 프레젠테이션 📊', '일본어로 리더십 발휘, 팀 이끌기 🏆'],
        beauty: ['히라가나·가타카나를 아름답게 쓸 수 있다 ✍️', '기본 한자 50자 획순 마스터 📝', '존댓말의 아름다움을 이해한다 🌸', '편지를 아름다운 일본어로 쓴다 ✉️', '하이쿠와 단카를 써본다 🖊️', '일본어의 미묘한 뉘앙스 차이를 알 수 있다 ✨', '일본어 소리의 아름다움을 완전히 만끽한다 🎵'],
        challenge: ['히라가나·가타카나·기본 한자 완벽 🏅', 'N5 레벨 문제집을 풀 수 있다 📚', 'N4 시험 합격 레벨 도달 🎯', 'N3 시험 합격권 진입 💪', 'N2 시험에 도전할 수 있는 레벨 🔥', 'N1 시험 합격을 노릴 수 있는 레벨 🏆', '일본어 마스터! 다음은 무슨 언어? 🌍'],
        other: ['일본어 기초를 탄탄히 쌓는다 📖', '간단한 일상 대화를 할 수 있다 💬', '일본어로 자기 생각을 표현한다 ✍️', '일본어로 정보 수집을 할 수 있다 🔍', '다양한 주제로 대화한다 🗣️', '전문적인 내용도 일본어로 이해한다 📊', '일본어를 자유자재로 구사한다 ✨'],
    },
    monthlyContent: {
        focus: [['히라가나·가타카나', '기본 인사', '숫자·시간'], ['N5 기초 문법', '일상 어휘 200개', '간단한 문장 만들기'], ['N4 문법 패턴', '어휘 500개', '존댓말 기초'], ['N3 문법', '어휘 1000개', '중급 독해'], ['N3→N2 전환', '추상적 어휘', '장문 독해'], ['N2 문법·어휘', '비즈니스 일본어', '전문 독해'], ['N1 레벨 표현', '뉘앙스 이해', '학술 일본어']],
        skills: [['자기소개 가능', '간단한 질문에 대답'], ['기본 쇼핑 대화', '길 묻기'], ['식당 주문', '일상 이메일 작성'], ['뉴스 제목 읽기', '의견 진술'], ['뉴스 이해', '토론 참가'], ['회의 발언', '보고서 작성'], ['논문 읽기', '프레젠테이션']],
        reasons: ['일본어 문자 체계와 첫 커뮤니케이션에 필요한 표현을 습득합니다.', '실생활에서 사용할 수 있는 최소한의 일본어를 익히고 간단한 대화를 합니다.', '일상생활에 필요한 일본어를 다지고 자연스러운 대화를 합니다.', '비즈니스와 학술의 입문으로서 복잡한 표현을 이해하고 사용합니다.', '실용적 일본어 능력을 연마하여 업무나 학업에 활용합니다.', '전문가로서 일본어를 사용하는 고급 스킬을 습득합니다.', '원어민에 가까운 운용력을 목표로 모든 상황에서 일본어를 자신 있게 사용합니다.'],
    },
    purposeMonthlyContent: {
        anime: {
            focus: [['애니메 인사·감탄사', '가타카나 캐릭터명', '히라가나/가타카나'], ['애니 명대사 50선', '일상 애니 기본 어휘', '대사 듣기 연습'], ['일상 회화 패턴', '만화 대사 읽기', '의성어·의태어'], ['구어vs경어 구분', '게임 UI 텍스트', '애니 감정 표현'], ['장르별 전문용어', '공략 사이트 읽기', '슬랭·젊은이 말'], ['복잡한 스토리 이해', '라이트노벨 읽기', '방언·캐릭터어'], ['문학적 표현·은유', '애니 고찰·리뷰', '원어민 속도 대화']], skills: [['OP 가사 읽기', '캐릭터명 정확한 발음'], ['기본 감탄사 이해', '일상 애니 인사 듣기'], ['만화 대사 읽기', '자막 애니 50% 이해'], ['자막 애니 80% 이해', 'RPG 기본 텍스트 읽기'], ['자막 없이 대략 이해', '일본어로 게임 플레이'], ['만화 원작 그대로 즐기기', '복선·은유 이해'], ['뉘앙스 완전 이해', '일본어로 작품 토론']], reasons: ['애니를 즐기는 첫걸음은 읽기. OP 가사와 캐릭터명을 읽으면 동기부여 유지.', '애니 특유의 구어 표현 우선 학습. 교과서에 없는 살아있는 일본어 습득.', '"듣기+읽기" 양륜 학습. 만화 대사 읽기로 애니 일본어 효율 향상.', '구어와 경어의 차이를 이해하고 상황 전환 능력 습득.', '장르 특유의 전문용어와 슬랭으로 무자막 시청의 다리 놓기.', '캐릭터 특유의 말투, 방언, 스토리 깊은 구조 이해력 연마.', '원어민처럼 작품을 깊이 음미하고 일본어로 고찰 토론하는 수준.'],
            textbooks: [['Genki I', 'Anime Scripts'], ['Genki II', 'Yotsuba&! (Manga)'], ['Quartet I', 'Slice of Life Anime Scripts'], ['Quartet II', 'Shonen Manga (with Furigana)'], ['Tobira', 'RPG Game Scripts'], ['Shin Kanzen Master N1', 'Light Novels (Easy)'], ['Native Materials', 'Anime Scenarios']],
            aiPrompt: [
                'You are a Japanese teacher who loves anime. Teach me 5 basic greeting phrases a beginner should know, speaking in an energetic tone like Luffy from One Piece.',
                'Explain the nuance and usage of sentence endings like "~daze" and "~kashira" often found in anime, with character dialogue examples.',
                'Analyze the polite yet strong speaking style of Tanjiro from Demon Slayer and create 3 phrases I can use in daily life.',
                'Create 5 "tsundere" lines for an anime character, explaining the grammatical structure and emotional nuance of each.',
                'List 20 important words related to "magic," "equipment," and "adventure" frequent in fantasy RPGs, with example sentences.',
                'Reproduce lines of an anime character using Kyoto dialect (Kansai-ben) and explain the difference from standard Japanese.',
                'Write a philosophical monologue in Japanese like in "Neon Genesis Evangelion" and explain the abstract vocabulary used.',
            ],
        },
        friends: {
            focus: [['자기소개 문구', '캐주얼 인사', '히라가나/가타카나'], ['SNS·LINE 표현', '취미 어휘', '맞장구(아이즈치)'], ['캐주얼-경어 전환', '감정 어휘', '초대·거절 방법'], ['의견 표현', '유머·농담', '반말과 존댓말 전환'], ['고민 상담 표현', '미묘한 뉘앙스', '"분위기 읽기" 문화'], ['토론·디스커션', '깊은 화제 어휘', '방언·지역 차이'], ['풍자·비유 표현', '일본인 가치관', '원어민 속도 대화']], skills: [['자기소개와 취미 대화', '"요로시쿠" 등 인사'], ['LINE으로 간단한 채팅', '상대 취미 물어보기'], ['30분간 수다 지속', '초대·정중한 거절'], ['일본어로 감정 표현', '농담으로 웃기기'], ['고민 상담하기', '일본인의 분위기 읽기'], ['깊은 대화 나누기', '방언으로 채팅'], ['싸우고 화해하기', '원어민과 대등한 대화']], reasons: ['친구 사귀기는 자기소개부터. 취미에서 공통점을 찾으면 관계 시작.', 'SNS는 현대 우정의 기반. LINE에서 쓸 수 있는 표현 마스터.', '카페 수다의 지구력 키우기. 자연스러운 초대와 거절 학습.', '관계 깊어짐에는 감정 표현이 필수. 유머를 더해 매력적인 대화.', '"분위기 읽기" 문화를 이해하고 더 깊은 신뢰 관계 구축.', '일본어로 깊은 화제를 토론하는 능력, 진정한 친구 수준.', '원어민과 자연스럽게 대등한 대화를 나누는 능력 완성.'],
            textbooks: [['Genki I', 'HelloTalk'], ['Genki II', 'LINE Stickers Japanese'], ['Tsunagu Nihongo', 'Tandem'], ['Quartet I', 'Japanese Dramas (Subtitled)'], ['Quartet II', 'Japanese Variety Shows'], ['Tobira', 'Japanese YouTubers'], ['Native Materials', 'Sharehouse Conversations']],
            aiPrompt: [
                'I want to make friends with a Japanese person I just met. Teach me 3 self-introduction phrases that are friendly but not rude.',
                'Create two examples of natural LINE messages to invite someone to dinner: one for a "close friend" and one for "someone I just met."',
                'Teach me the positive and negative nuances of slang words young people use like "maji-de" and "yabai," with example sentences.',
                'List 10 empathetic Japanese phrases (like "That must have been hard") I can use when listening to a friend\'s worries.',
                'Explain what "reading the air" specifically means using a Japanese drinking party situation as an example.',
                'Teach me phrases to exchange opinions on recent news with a friend, like "I think this, but what do you think?"',
                'Teach me some Japanese jokes or "dad jokes" (oyaji gag) and explain why they are funny (wordplay, etc.).',
            ],
        },
        travel: {
            focus: [['역·공항 간판', '숫자·시간·요일', '히라가나/가타카나'], ['식당 주문 표현', '호텔 체크인', '길 물어보기'], ['교통 환승', '쇼핑 가격 확인', '관광지 질문'], ['료칸 매너·대화', '지역 특산물 어휘', '날씨·건강 표현'], ['지역 방언 기초', '역사 건축 해설', '현지인과 잡담'], ['여행 블로그·리뷰 읽기', '전화 예약', '긴급 상황 대응'], ['방언 섞인 대화', '여행 중 깊은 교류', '일본 문화 해설']], skills: [['역 간판 읽기', '숫자 듣기 이해'], ['식당 주문·계산', '택시에 목적지 전달'], ['전철 환승', '가게에서 가격 확인'], ['료칸 대화 즐기기', '건강 문제 설명'], ['방언 대체로 이해', '현지인과 잡담'], ['전화 예약', '리뷰로 여행 계획'], ['완전 독립 자유여행', '현지인에게 숨겨진 명소 안내']], reasons: ['여행은 간판과 숫자부터. 이동에 필요한 최소한 우선.', '"바로 쓸 수 있는 표현"에 집중. 식당과 호텔에서 당황하지 않기.', '교통과 쇼핑 독립 수준 달성. 실용 표현 집중 연습.', '"오모테나시" 체험으로 여행 즐거움 배가. 료칸 대화와 지역 맛집 화제.', '방언 기초를 배워 현지인과 자연스러운 대화 수준.', '스스로 정보 조사하고 전화 예약할 수 있는 독립 여행자.', '일본 구석구석을 즐기는 고급 여행자. 현지인과 깊은 교류.'],
            textbooks: [['Phrasebook', 'Google Maps'], ['Travel Japanese', 'Train Timetables'], ['Japan Travel Survival', 'Tabelog'], ['Omotenashi Japanese', 'Ryokan Booking Sites'], ['Dialect Chart', 'Rurubu (Travel Mag)'], ['Jalan (Booking Site)', 'Shinkansen App'], ['National Guides', 'Local Newspapers']],
            aiPrompt: [
                'I am lost at a station in Japan. Teach me a polite phrase to ask station staff "How to get to Shinjuku Station" and "How long it takes."',
                'I entered a restaurant in Japan. Create a phrase to say I have an allergy (e.g., shrimp) and ask for a menu without it.',
                'Explain basic manners I should know when staying at a Ryokan (taking off shoes, hot spring etiquette) in simple Japanese.',
                'Simulate a conversation where I ask a shop clerk "What do you recommend?" and ask for the reason.',
                'I am traveling to Kansai (Osaka/Kyoto). Teach me 5 simple Kansai-ben phrases (like "ookini") to use with shop staff.',
                'I want to book a restaurant by phone. Create a script saying "I would like to make a reservation for 2 people at 7 PM next Saturday."',
                'Think of 3 slightly intellectual mock questions to ask a guide about history when visiting Japanese castles or temples.',
            ],
        },
        culture: {
            focus: [['기본 예절·매너', '일본 요리 이름', '히라가나/가타카나'], ['연중행사 어휘', '식문화 매너', '계절 인사'], ['다도·꽃꽂이 기본 용어', '기모노 종류', '전통 공예 어휘'], ['일본사 기본 용어', '신도·불교 기초', '와카 감상 입문'], ['고전 문학 기초', '속담·관용구', '서도 기초'], ['노·가부키 감상', '일본 미술 해설', '계절어와 하이쿠'], ['고문 읽기', '문화론 토론', '일본 미학 이해']], skills: [['인사 종류 알기', '젓가락 매너 설명'], ['일본 명절 소개', '일식 매너 설명'], ['다도 흐름 이해', '기모노 TPO 알기'], ['일본 역사 개요', '신사와 절의 차이 설명'], ['일상에서 속담 사용', '하이쿠 기본 규칙 이해'], ['전통 예능 감상·해설', '일본 미술 특징 설명'], ['고전 문학 원문 감상', '일본 문화 깊이 토론']], reasons: ['일본 문화의 입구는 예절과 식문화. 올바른 인사와 젓가락 사용으로 "형"을 배우기.', '사계절 행사를 통해 자연관 학습. 계절 인사를 할 수 있으면 일본인이 감탄.', '"도(道)" 문화에 접하며 "와비사비" 이해 심화. 체험의 질이 크게 향상.', '문화 이면의 역사와 종교 학습. 지식의 심화가 문화 체험의 질을 바꿈.', '고전 표현과 속담에 접하며 일본어에 담긴 문화적 지혜를 음미.', '전통 예능에서 미술까지 일본 문화의 정수를 감상·해설하는 수준.', '고전을 원문으로 접하며 원어민과 동등한 깊이로 이해·토론하는 수준.'],
            textbooks: [['Intro to Japanese Culture', 'Chopstick Tutorials'], ['Japanese Annual Events', 'Japanese Calendar'], ['Tea Ceremony Intro', 'Traditional Crafts Guide'], ['Japanese History Manga', 'Shrine Test Text'], ['Children\'s Analects', 'Hyakunin Isshu'], ['Kabuki Guide', 'Art History Intro'], ['Tale of Genji (Original/Modern)', 'Fushikaden']],
            aiPrompt: [
                'Explain the difference between Japanese bows (eshaku, keirei, saikeirei) and when to use each.',
                'Teach me Japanese phrases to explain the spiritual meaning of "Itadakimasu" and "Gochisousama" to foreigners.',
                'Briefly explain the Japanese aesthetic of "Wabi-Sabi" in Japanese, using moss or tea bowls as examples.',
                'Compare the differences between shrines and temples (worship methods, what is enshrined) and create a word list for each.',
                'Explain the meaning of the famous proverb "Ishi no ue ni mo sannen" and modern situations where it is used.',
                'I am going to see Kabuki for the first time. Teach me 3 points a beginner should know about unique calls and how to enjoy it.',
                'Explain the modern translation of the opening of "The Tale of Genji" and its unique atmosphere and cultural background.',
            ],
        },
        live: {
            focus: [['편의점·마트 간판', '주소 읽는 법', '히라가나/가타카나'], ['관공서 수속 용어', '은행 계좌 개설', '병원 접수'], ['임대 계약 용어', '전기·가스·수도', '우편·택배'], ['동네회 어휘', '학교 관련 용어', '보험·연금'], ['확정 신고 기초', '부동산 어휘', 'PTA·지역 활동'], ['법률 용어 기초', '이직·커리어 상담', '육아 지원 제도'], ['행정 수속 전반', '시민 활동·봉사', '일본 사회 깊이 이해']], skills: [['편의점 쇼핑', '자기 주소 쓰기'], ['관공서 전입 신고', '은행 계좌 개설'], ['임대 계약 핵심 이해', '공공요금 문의'], ['이웃과 잡담', '학교 편지 이해'], ['확정 신고 서류 이해', '지역 활동 참가'], ['법적 권리 이해', '일본어로 구직'], ['일본 사회 완전 적응', '행정 수속 독립']], reasons: ['일본 생활은 편의점과 주소부터. 매일 쓰는 단어 우선 기억.', '생활 인프라 수속을 혼자 완료. 관공서, 은행, 병원 최우선.', '주소와 생활 기반 안정화. 계약과 생활 인프라 용어 중점.', '지역 사회에 녹아드는 단계. 이웃 교류와 학교 관련 어휘 추가.', '장기 거주에 필요한 지식 심화. 세금과 지역 활동으로 사회에 뿌리내리기.', '커리어 발전과 법률 수속에 대응하는 고급 일본어 능력 육성.', '일본 사회에 완전히 녹아들어 어떤 상황에서도 자유롭게 생활하는 것이 목표.'],
            textbooks: [['Japanese for Life', 'Supermarket Flyers'], ['City Hall Guide', 'Medical Japanese'], ['Reading Contracts', 'Rental Sites'], ['PTA Handbook', 'Circular Notices'], ['Tax Return Guide', 'Disaster Maps'], ['Business Law Intro', 'Hello Work Job Slips'], ['Understanding Japanese Society', 'Newspaper Editorials']],
            aiPrompt: [
                'Reproduce a natural interaction at a Japanese convenience store asking to warm up a bento and get chopsticks and a bag.',
                'Simulate a conversation at a hospital reception to convey "I have had a fever since yesterday and my throat hurts."',
                'I am looking for an apartment at a real estate agency. Create a dialogue conveying "Rent under 70,000 yen, within 10 min walk from station."',
                'Garbage sorting rules are confusing. Teach me a conversation to ask a neighbor "Which day should I put out this plastic?"',
                'Write a polite message for a child\'s school contact book saying "He will be absent tomorrow due to a cold."',
                'Explain basic keywords beginners should know about year-end tax adjustment and tax returns in Japan (deductions, withholding, etc.).',
                'Think of a self-introduction speech for a neighborhood association meeting saying "I am still studying Japanese, but nice to meet you."',
            ],
        },
        work: {
            focus: [['비즈니스 인사', '명함 교환 절차', '히라가나/가타카나'], ['비즈니스 이메일 틀', '전화 응대', '회사 자기소개'], ['회의록 작성', '보련소 문화', '경어 체계'], ['프레젠테이션 자료', '회의 발언 패턴', '협상 표현'], ['계약서 읽기', '보고서·문서', '사내 정치 어휘'], ['경영 전략 어휘', 'IR·재무 용어', '리더십 표현'], ['임원급 일본어', 'M&A·법무 용어', '연설·강연']], skills: [['명함 교환', '비즈니스 인사 올바르게'], ['템플릿 이메일 작성', '전화 전달'], ['회의록 작성', '상사에게 보련소'], ['회의에서 의견 발표', '프레젠테이션 자료 작성'], ['계약서 이해', '일본어로 보고서 작성'], ['경영 회의 참가', '일본어로 팀 리드'], ['임원에게 프레젠테이션', '모든 업무 일본어 처리']], reasons: ['비즈니스 첫인상은 인사와 명함 교환. 올바른 형식 먼저 마스터.', '이메일과 전화는 일상 업무 기본. 템플릿 표현으로 즉전력.', '"보련소"는 일본 기업의 생명줄. 상사·동료와의 커뮤니케이션 기반 구축.', '아웃풋 능력 강화. 회의 발언과 프레젠테이션으로 존재감 발휘.', '문서를 정확하게 읽고 쓰는 능력으로 전문가로서의 신뢰 획득.', '매니지먼트급 일본어 능력을 목표로 팀 관리와 전략 토론.', '최고 수준의 비즈니스 일본어로 임원 역할 대응. 어떤 장면도 자신 있게.'],
            textbooks: [['Keigo Training', 'Business Card Manners'], ['Business Writing', 'Phone Manuals'], ['Manga Ho-Ren-So', 'Meeting Japanese'], ['Presentation Japanese', 'Logical Speaking'], ['Business Contracts', 'Internal Reports'], ['Nikkei Business', 'Drucker (JP Ver)'], ['HBR Japan', 'Corporate Law']],
            aiPrompt: [
                'Teach me the correct step-by-step procedure for exchanging business cards in Japan, with dialogue.',
                'Create an example of a polite business email asking a client "I would like to change the meeting date."',
                'Create an appropriate conversation flow for reporting progress to a boss (Ho-Ren-So) starting with "Actually, there is a problem..."',
                'Teach me 5 variations of phrases to point out concerns in a meeting while agreeing, like "I agree basically, but just one point..."',
                'Explain the usage of "Osewa ni natte orimasu," "Otsukaresama desu," and "Gokurosama desu" and their NG scenes.',
                'Create an opening speech for a business presentation that apologizes for a project failure but proposes improvements sincerely.',
                'Teach me ideal praise words a Japanese boss uses to motivate subordinates (like "Sasuga da ne, kitai ijo da yo").',
            ],
        },
        beauty: {
            focus: [['아름다운 히라가나 획순', '가타카나의 유래', '일본어 소리의 특징'], ['기본 한자 50자 획순', '음독·훈독', '의성어의 아름다움'], ['한자 편방과 의미', '아름다운 필기 연습', '계절 어휘'], ['경어의 체계와 아름다움', '편지 쓰는 법', '색의 일본어 이름'], ['하이쿠 기본 규칙', '와카 감상', '서도 기초'], ['단카·시 창작', '고어의 아름다움', '일본어의 리듬'], ['문학 표현 완전 이해', '서도의 극치', '일본어 미학의 구현']], skills: [['히라가나 아름답게 쓰기', '일본어 모음의 맛 느끼기'], ['50자 올바른 획순', '한자 유래 설명'], ['편방으로 한자 의미 추측', '계절 편지 쓰기'], ['경어 아름답게 사용', '편지지에 아름다운 편지'], ['하이쿠 짓기', '와카의 의경 이해'], ['단카 창작', '고어의 맛 음미'], ['일본어 소리의 아름다움 완전 이해', '서도의 극치']], reasons: ['일본어 아름다움의 원점은 문자의 형태와 소리의 울림. 한 획 한 획 정성스러운 학습으로 미의식 배양.', '한자의 유래를 알면 각 글자에 담긴 깊은 의미 발견. 쓰는 즐거움이 배가.', '한자를 체계적으로 이해하고 계절 미적 표현 학습. 손글씨의 온기를 소중히.', '경어는 일본어 아름다움의 결정체. 구분 사용할 수 있으면 깊은 맛을 체감.', '하이쿠와 와카에 접하며 17음·31음에 응축된 일본어의 아름다움 체험.', '창작의 즐거움에 진입. 고어만의 아름다움과 깊이에 접속.', '일본어의 소리·형태·뜻 모든 아름다움을 남김없이 음미하는 최종 단계.'],
            textbooks: [['Calligraphy Practice', 'Hiragana Chart'], ['Kanji Origins', 'Beautiful Words Dict'], ['Japanese Colors', 'Seasonal Words'], ['Aesthetics of Keigo', 'Letter Writing'], ['Haiku Almanac', 'Manyoshu Intro'], ['Kokin Wakashu', 'Tale of the Bamboo Cutter'], ['Tale of Genji', 'Pillow Book']],
            aiPrompt: [
                'Teach me tips to write hiragana "a" and "no" beautifully and balanced, relating them to shapes (triangle, circle).',
                'Introduce 5 beautiful Japanese words related to "rain" (samidare, shigure, etc.) and explain the scenery of each.',
                'Teach me seasonal greetings (jikou no aisatsu) used in letter openings like "Haikei, sakura no kisetsu..." for each of the 4 seasons.',
                'Introduce some Japanese expressions that convey love indirectly and elegantly, like "The moon is beautiful, isn\'t it?"',
                'I want to make Haiku. Create and explain 3 beginner examples using "Summer" and "Sea" as themes.',
                'Select 10 Japanese onomatopoeia with particularly beautiful sounds (like "shitoshito," "kirakira").',
                'Select one famous romantic poem from Hyakunin Isshu and explain its meaning and background in a modern way.',
            ],
        },
        challenge: {
            focus: [['히라가나·가타카나 완전 기억', '기본 한자 100자', '일본어 문장 구조'], ['N5 문법 전 학습', '어휘 300개', 'N5 모의시험 대책'], ['N4 문법 정복', '어휘 800개', 'N4 모의시험 대책'], ['N3 문법 체계', '어휘 1500개', '중급 독해 훈련'], ['N2 문법 패턴', '어휘 3000개', '장문 독해·청해'], ['N1 문법·어휘', '추상적 표현', 'N1 실전 연습'], ['초고급 표현', '학술 논문 읽기', '원어민 수준 달성']], skills: [['히라가나·가타카나 완벽', '기본 한자 100자 읽기/쓰기'], ['N5 모의시험 합격', '기본 질문 대답'], ['N4 수준 달성', '일상 대화 가능'], ['N3 합격권 진입', '뉴스 제목 읽기'], ['N2 레벨 문제 풀기', '뉴스 이해'], ['N1 합격 도전', '비즈니스 대응 가능'], ['일본어 마스터', '어떤 상황에서도 자유자재']], reasons: ['도전은 기초부터. 문자와 문장 구조를 철저히 이해하고 견고한 토대 다지기.', 'N5 완전 공략을 목표로 문법과 어휘를 체계적으로 쌓기. 모의시험으로 실력 확인.', 'N4 수준을 목표로 문법 패턴 확장과 일상 회화력 강화를 동시에.', 'N3는 중급으로 가는 관문. 문법 체계 정리와 독해력 급속 향상.', 'N2는 실용 수준의 증명. 전략적으로 장문 독해와 청해 점수 향상.', 'N1은 일본어 학습자의 최고봉. 추상적 어휘와 복잡한 문법 패턴에 도전.', 'N1을 넘어 진정한 일본어 마스터로. 학술·비즈니스·일상 어떤 상황에서도 자유자재.'],
            textbooks: [['Genki I', 'Kanji Master N5'], ['Shin Kanzen Master N5', 'JLPT N5 Prep'], ['Shin Kanzen Master N4', 'Sou Matome N4'], ['Shin Kanzen Master N3', 'Sou Matome N3'], ['Shin Kanzen Master N2', 'Sou Matome N2'], ['Shin Kanzen Master N1', 'Sou Matome N1'], ['Advanced Reading', 'Learn with News']],
            aiPrompt: [
                'Create 10 conjugation practice questions for N5 essential verbs (iku, taberu, miru) covering present, past, and negative forms.',
                'Explain the difference between N4 grammar "~te wa ikemasen" (prohibition) and "~nakutemo ii desu" (not necessary) with 5 practice questions.',
                'Teach me techniques for "Task-Based Understanding" questions often found in N3 listening tests (reading questions first, taking notes, etc.).',
                'I run out of time in N2 reading. Explain tips for speed reading and how to focus on conjunctions (shikashi, tsumari).',
                'Propose some mnemonics or story memory methods to remember difficult N1 kanji (like "chucho," "kairi").',
                'Give me advice on what to do in the week before the JLPT (daily rhythm, review priorities).',
                'Correct my short essay ([Insert text here]) and rewrite it into more natural, advanced Japanese expressions.',
            ],
        },
        other: {
            focus: [['히라가나·가타카나', '기본 인사', '숫자·시간'], ['N5 기초 문법', '일상 어휘 200개', '간단한 문장 만들기'], ['N4 문법 패턴', '어휘 500개', '존댓말 기초'], ['N3 문법', '어휘 1000개', '중급 독해'], ['N3→N2 전환', '추상적 어휘', '장문 독해'], ['N2 문법·어휘', '비즈니스 일본어', '전문 독해'], ['N1 레벨 표현', '뉘앙스 이해', '학술 일본어']], skills: [['자기소개 가능', '간단한 질문에 대답'], ['기본 쇼핑 대화', '길 묻기'], ['식당 주문', '일상 이메일 작성'], ['뉴스 제목 읽기', '의견 진술'], ['뉴스 이해', '토론 참가'], ['회의 발언', '보고서 작성'], ['논문 읽기', '프레젠테이션']], reasons: ['일본어 문자 체계와 첫 커뮤니케이션에 필요한 표현을 습득합니다.', '실생활에서 사용할 수 있는 최소한의 일본어를 익히고 간단한 대화를 합니다.', '일상생활에 필요한 일본어를 다지고 자연스러운 대화를 합니다.', '비즈니스와 학술의 입문으로서 복잡한 표현을 이해하고 사용합니다.', '실용적 일본어 능력을 연마하여 업무나 학업에 활용합니다.', '전문가로서 일본어를 사용하는 고급 스킬을 습득합니다.', '원어민에 가까운 운용력을 목표로 모든 상황에서 일본어를 자신 있게 사용합니다.'],
            textbooks: [['Tae Kim\'s Guide', 'Duolingo'], ['Genki I', 'Anki Core 2k'], ['Genki II', 'NHK Easy Japanese'], ['Tobira Gateway', 'News Web Easy'], ['Tobira Advanced', 'Japanese Novels'], ['New Kanzen Master N1', 'Japanese News'], ['Read Japanese Society', 'Academic Papers']],
            aiPrompt: [
                'Explain the difference between Japanese "wa" and "ga" using simple example sentences a beginner can understand.',
                'Teach me 3 of the most basic and natural ordering phrases to use at restaurants or shops in Japan.',
                'Japanese counters (ippon, ippiki, ichimai) are hard to remember. Teach me the top 5 most used counters and how to remember them.',
                'Create a usage chart for Keigo (Teineigo, Sonkeigo, Kenjougo) showing representative verb changes (iku -> ikimasu, irasshaimasu, mairimasu).',
                'Summarize this recent Japanese news article ([Insert article here]) and rewrite it into simple Japanese a dictionary school student could understand.',
                'Teach me a short script for shadowing practice to improve my pronunciation, along with practice points.',
                'Teach me variations of "Aizuchi" (nodding/responses) Japanese use in conversation ("Hee," "Sou nanda," "Naruhodo") and how to use them.',
            ],
        },
    },
};

