import type { Translations } from './index';

export const en: Translations = {
    title: 'Japanese Learning Roadmap',
    subtitle: 'Create your personalized study plan',

    currentLevel: 'Current Level',
    targetLevel: 'Target Level',
    learningPeriod: 'Study Period',
    months: ' months',
    monthUnit: ' months',
    beginner: 'Beginner',
    native: 'Native',
    purpose: 'Why do you want to learn Japanese?',
    createRoadmap: '📚 Create Roadmap',
    selectPurpose: 'Please select your purpose',

    levelDescriptions: {
        n5: 'JLPT N5',
        n4: 'JLPT N4',
        n3: 'JLPT N3',
        n2: 'JLPT N2',
        n1: 'JLPT N1',
        nativeLevel: 'Native',
    },

    purposes: {
        anime: { label: 'Anime, Manga & Games', description: 'Enjoy without subtitles' },
        friends: { label: 'Make Friends & Partners', description: 'Build deep connections with Japanese people' },
        travel: { label: 'Travel Japan', description: 'Explore freely, even off the beaten path' },
        culture: { label: 'Japanese Culture', description: 'Appreciate traditions, food & seasons' },
        live: { label: 'Live in Japan', description: 'Safe, clean & comfortable lifestyle' },
        work: { label: 'Work in Japan', description: 'Use Japanese for business' },
        beauty: { label: 'Japanese is Beautiful', description: 'Fascinated by sounds & characters' },
        challenge: { label: 'Personal Challenge', description: 'Intellectual curiosity & self-growth' },
        other: { label: 'Other', description: 'Other purposes' },
    },

    planSummary: '📊 Your Study Plan Overview',
    totalHours: 'Total Hours',
    hoursPerWeek: 'hrs/week',
    levelUp: 'Level Up',
    current: 'Current',
    goal: 'Goal',
    dailyStudy: 'About ',
    hoursUnit: ' hours',
    achievable: ' per day to reach your goal!',

    growthChart: 'Growth Forecast',
    now: 'Now',
    monthsLater: 'm later',
    level: 'Level',

    lessonDistribution: 'Recommended Lesson Mix',
    optimizedForYou: 'Optimized balance for your goals',
    whyThisBalance: 'Why this balance?',
    lessonTypes: {
        grammar: 'Grammar',
        vocabulary: 'Vocabulary',
        conversation: 'Conversation',
        reading: 'Reading',
        listening: 'Listening',
    },

    monthlyMilestones: 'Monthly Milestones',
    monthN: '',
    targetLevelLabel: 'Target',
    purposeStep: 'Steps toward your goal',
    learningContent: '🎯 This month\'s focus',
    achievedSkills: '✅ Skills you\'ll gain',
    whyThisOrder: '📌 Why this order?',
    recommendedLessons: 'Recommended lessons',
    textbooksLabel: 'Recommended Textbooks',
    aiPromptLabel: 'AI Roleplay Prompt',

    lessonsPerMonth: '/month',

    roadmapComplete: '🎉 Your Personal Roadmap is Ready!',
    ctaDescription: 'With this plan, you can definitely reach your goal.',
    ctaPeriod: ' in ',
    ctaFrom: 'From ',
    ctaTo: ' to ',
    startFreeTrial: '✨ Start Free Trial',
    shareThisPlan: 'Share This Plan',
    generating: 'Generating...',
    trialBooked: 'Free trial booked!',
    imageError: 'Failed to generate image',
    shareOpened: 'Share menu opened',
    downloaded: 'Image downloaded',
    errorOccurred: 'An error occurred',

    distributionReasons: {
        anime: {
            beginner: 'To understand anime Japanese, listening is key. We\'ll build your ear for casual speech, slang, and unique character expressions while building grammar and vocabulary fundamentals.',
            advanced: 'Beyond listening, you\'ll need to read manga dialogue and game text. We focus on colloquial Japanese, slang, and onomatopoeia — the living language you won\'t find in textbooks.',
        },
        friends: {
            beginner: 'To connect with people, speaking comes first. Even with simple grammar, being able to have a back-and-forth conversation deepens relationships. Let\'s start with expressing your feelings.',
            advanced: 'Deep relationships require conveying nuance and emotion accurately. We\'ll practice switching between formal and casual speech, and understanding "reading the air" in Japanese culture.',
        },
        travel: {
            beginner: 'Travel Japanese is all about "phrases you can use right now." We prioritize vocabulary for stations, restaurants, and hotels, plus the conversation skills to ask locals for help.',
            advanced: 'We\'ll build your ability to understand regional dialects and communicate where English isn\'t spoken. Reading signs and chatting with locals become the focus.',
        },
        culture: {
            beginner: 'Understanding Japanese culture deeply requires reading ability. We prioritize vocabulary for etiquette, annual events, and food culture to build a foundation for cultural literacy.',
            advanced: 'Classical expressions, proverbs, letter-writing styles — we aim for a level where you can truly savor the depth of Japanese culture, including specialized vocabulary for arts like tea ceremony.',
        },
        live: {
            beginner: 'Priority: "survival Japanese" for daily life. We comprehensively cover vocabulary for city hall, hospitals, banks, and real estate — everything you need for life infrastructure.',
            advanced: 'Building communication skills for neighborhood relationships, PTA, and community associations. We deepen proper keigo usage and understanding of Japan\'s unique social rules.',
        },
        work: {
            beginner: 'Business Japanese starts with "proper keigo." We prioritize immediately usable skills: email writing, phone manners, and professional self-introductions.',
            advanced: 'Speaking in meetings, presentations, negotiations, and report writing — building the Japanese proficiency that earns professional trust. Including industry-specific terminology.',
        },
        beauty: {
            beginner: 'To appreciate beautiful Japanese, we start with the world of characters. We carefully learn hiragana/katakana stroke order, kanji origins, and the rhythm of Japanese sounds.',
            advanced: 'Haiku, tanka, poetic expressions, seasonal vocabulary — touching the essence of Japanese beauty. We also explore calligraphy basics and elegant letter-writing styles.',
        },
        challenge: {
            beginner: 'The most efficient approach is balanced growth across all skills. We\'ll understand Japanese structure logically, incorporating a linguistic perspective.',
            advanced: 'Using JLPT prep as the backbone, we target reading and listening score improvements. Tackle advanced grammar patterns and abstract vocabulary to satisfy your intellectual curiosity.',
        },
        other: {
            beginner: 'A balanced plan to grow all 5 skills evenly. Tell me your specific goals in the free lesson — let\'s customize together!',
            advanced: 'A comprehensive plan to strengthen all skills equally. Customization for your specific goals is available — let\'s discuss in the free lesson!',
        },
    },

    purposeMilestones: {
        anime: [
            'Can read anime opening song lyrics 🎵',
            'Can catch simple greetings in slice-of-life anime 👂',
            'Can understand 80% of anime with subtitles 📺',
            'Can follow a daily-life anime episode without subs 🎉',
            'Can play Japanese games without a dictionary 🎮',
            'Can read manga in the original Japanese 📖',
            'Can understand complex dialogue and nuance in anime ✨',
        ],
        friends: [
            'Can introduce yourself and talk about hobbies 👋',
            'Can exchange simple messages on LINE 📱',
            'Can chat at a café for 30 minutes ☕',
            'Can express feelings and opinions in Japanese 💬',
            'Can understand jokes and laugh together 😄',
            'Can discuss worries and deep topics 🤝',
            'Can argue and make up in Japanese (true friendship!) 💪',
        ],
        travel: [
            'Can read station signs and notices 🚃',
            'Can order and pay at restaurants 🍣',
            'Can ask for and understand directions 🗺️',
            'Can chat with ryokan staff at hot springs ♨️',
            'Can mostly understand regional dialects 🏔️',
            'Can travel solo without a Japanese guide 🎒',
            'Can befriend locals and discover hidden gems 🌸',
        ],
        culture: [
            'Can use basic manners and greetings correctly 🙇',
            'Can name Japanese holidays and traditional events 🎎',
            'Can explain washoku names and dining etiquette 🍱',
            'Can understand basic tea/flower ceremony terms 🍵',
            'Can discuss Japanese history and values 🏯',
            'Can appreciate haiku and tanka basics 📝',
            'Can enjoy Japanese culture at a native level 🌊',
        ],
        live: [
            'Can shop at convenience stores without trouble 🏪',
            'Can handle simple city hall procedures alone 📋',
            'Can describe symptoms at the hospital 🏥',
            'Can small-talk with landlord and neighbors 🏘️',
            'Can understand bank/insurance/phone contracts 📄',
            'Can participate in PTA and community meetings 🤝',
            'Can live in Japan completely independently 🏠',
        ],
        work: [
            'Can do basic business greetings and card exchange 💼',
            'Can write simple business emails ✉️',
            'Can handle basic phone calls 📞',
            'Can present your opinion in meetings 🎤',
            'Can negotiate with clients without an interpreter 🤝',
            'Can give presentations in Japanese 📊',
            'Can lead a team using Japanese 🏆',
        ],
        beauty: [
            'Can write hiragana and katakana beautifully ✍️',
            'Can master stroke order for 50 basic kanji 📝',
            'Can appreciate the beauty of keigo 🌸',
            'Can write letters in beautiful Japanese ✉️',
            'Can try writing haiku and tanka 🖊️',
            'Can distinguish subtle Japanese nuances ✨',
            'Can fully appreciate the beauty of Japanese sounds 🎵',
        ],
        challenge: [
            'Master hiragana, katakana & basic kanji 🏅',
            'Can solve N5 level practice tests 📚',
            'Reach N4 exam passing level 🎯',
            'Enter N3 exam passing range 💪',
            'Ready to challenge N2 exam 🔥',
            'Aiming for N1 exam pass 🏆',
            'Japanese master! What language\'s next? 🌍',
        ],
        other: [
            'Build a solid Japanese foundation 📖',
            'Can handle simple daily conversations 💬',
            'Can express your thoughts in Japanese ✍️',
            'Can gather information in Japanese 🔍',
            'Can discuss a wide range of topics 🗣️',
            'Can understand specialized content in Japanese 📊',
            'Can use Japanese freely and naturally ✨',
        ],
    },

    monthlyContent: {
        focus: [
            ['Hiragana & Katakana', 'Basic greetings', 'Numbers & time'],
            ['N5 basic grammar', '200 daily vocabulary', 'Simple sentence building'],
            ['N4 grammar patterns', '500 vocabulary milestone', 'Keigo basics'],
            ['N3 grammar', '1000 vocabulary', 'Intermediate reading'],
            ['N3→N2 transition', 'Abstract vocabulary', 'Long-text reading'],
            ['N2 grammar & vocab', 'Business Japanese', 'Specialized reading'],
            ['N1 expressions', 'Nuance understanding', 'Academic Japanese'],
        ],
        skills: [
            ['Can introduce yourself', 'Can answer simple questions'],
            ['Basic shopping conversations', 'Can ask for directions'],
            ['Can order at restaurants', 'Can write casual emails'],
            ['Can read news headlines', 'Can state opinions'],
            ['Can understand TV news', 'Can join discussions'],
            ['Can speak in meetings', 'Can write reports'],
            ['Can read academic papers', 'Can give presentations'],
        ],
        reasons: [
            'Master the Japanese writing system and essential expressions for first communication.',
            'Build minimum Japanese for real-life use and basic daily conversations.',
            'Solidify Japanese needed for daily life and natural conversations.',
            'Understand complex expressions as a gateway to business and academic Japanese.',
            'Polish practical Japanese skills for use in work and studies.',
            'Acquire advanced skills to use Japanese professionally.',
            'Aim for near-native proficiency to use Japanese confidently in any situation.',
        ],
    },

    purposeMonthlyContent: {
        anime: {
            focus: [
                ['Common anime greetings & exclamations', 'Reading character names in katakana', 'Hiragana & katakana basics'],
                ['Top 50 anime phrases', 'Slice-of-life anime vocabulary', 'Dialogue listening practice'],
                ['Daily conversation patterns', 'Manga dialogue reading', 'Onomatopoeia & sound effects'],
                ['Casual vs. polite speech', 'Game UI text reading', 'Anime emotion expressions'],
                ['Genre-specific terms (battle, sci-fi)', 'Game walkthrough reading', 'Slang & youth language'],
                ['Complex storyline comprehension', 'Light novel reading', 'Dialects & character speech'],
                ['Literary expressions & metaphors', 'Anime analysis & reviews', 'Native-speed conversation'],
            ],
            skills: [
                ['Can read opening song lyrics', 'Can pronounce character names correctly'],
                ['Understand basic exclamations', 'Can catch greetings in daily anime'],
                ['Can read manga dialogue', 'Understand 50% of subtitled anime'],
                ['Understand 80% of subtitled anime', 'Can read basic RPG text'],
                ['Can follow daily anime without subs', 'Can play games in Japanese'],
                ['Can enjoy manga in original Japanese', 'Understand foreshadowing & metaphors'],
                ['Full nuance comprehension', 'Can discuss anime in Japanese'],
            ],
            reasons: [
                'The first step to enjoying anime is reading. Being able to read OP lyrics and character names keeps motivation high.',
                'Prioritize casual expressions common in anime. Real-life language not found in textbooks builds practical skills.',
                'Strengthen both "listening + reading." Adding manga reading efficiently boosts your anime Japanese.',
                'Understand the difference between casual and formal speech, mastering situational switching.',
                'Learn genre-specific jargon and slang, bridging the gap to subtitle-free viewing.',
                'Build the ability to understand character-specific speech patterns, dialects, and deeper narrative structures.',
                'Aim to enjoy works at the same depth as native viewers and discuss analysis in Japanese.',
            ],
            textbooks: [['Genki I', 'Anime Scripts'], ['Genki II', 'Yotsuba&! (Manga)'], ['Quartet I', 'Slice of Life Anime Scripts'], ['Quartet II', 'Shonen Manga (with Furigana)'], ['Tobira', 'RPG Game Scripts'], ['Shin Kanzen Master N1', 'Light Novels (Easy)'], ['Native Materials', 'Anime Scenarios']],
            aiPrompt: [
                'You are a Japanese teacher who loves anime. Teach me 5 basic greeting phrases a beginner should know, speaking in an energetic tone like Luffy from One Piece.',
                'Explain the nuance and usage of sentence endings like "~daze" and "~kashira" often found in anime, with character dialogue examples.',
                'Analyze the polite yet strong speaking style of Tanjiro from Demon Slayer and create 3 phrases I can use in daily life.',
                'Create 5 "tsundere" lines for an anime character, explaining the grammatical structure and emotional nuance of each.',
                'List 20 important words related to "magic," "equipment," and "adventure" frequent in fantasy RPGs, with example sentences.',
                'Reproduce lines of an anime character using Kyoto dialect (Kansai-ben) and explain the difference from standard Japanese.',
                'Write a philosophical monologue in Japanese like in "Neon Genesis Evangelion" and explain the abstract vocabulary used.',
            ],
        },
        friends: {
            focus: [
                ['Self-introduction phrases', 'Casual greetings', 'Hiragana & katakana basics'],
                ['SNS & LINE message expressions', 'Hobby vocabulary', 'How to give reactions (aizuchi)'],
                ['Casual vs. polite switching', 'Emotion vocabulary', 'How to invite & decline'],
                ['Expressing opinions', 'Humor & joke expressions', 'Casual vs. keigo switching'],
                ['Discussing worries & advice', 'Subtle nuances', 'Understanding "reading the air"'],
                ['Debate & discussion expressions', 'Deep topic vocabulary', 'Regional dialect awareness'],
                ['Sarcasm & figurative language', 'Understanding Japanese values', 'Native-speed conversation'],
            ],
            skills: [
                ['Can do self-introductions & talk hobbies', 'Can use greetings like "yoroshiku"'],
                ['Can chat on LINE', 'Can ask about someone\'s hobbies'],
                ['Can sustain 30-min small talk', 'Can invite friends & politely decline'],
                ['Can express feelings in Japanese', 'Can make people laugh with jokes'],
                ['Can discuss personal worries', 'Can read the air like a local'],
                ['Can have deep conversations', 'Can chat using some dialect'],
                ['Can argue and make up', 'Can converse equally with natives'],
            ],
            reasons: [
                'Making friends starts with self-introductions. Finding common hobbies is how relationships begin.',
                'SNS is the modern foundation of friendship. Master phrases you can use on LINE.',
                'Build the stamina for café small talk. Learn to invite and decline naturally.',
                'Deepening relationships requires expressing feelings. Add humor for engaging conversations.',
                'Understand "reading the air" culture to build deeper trust and stronger bonds.',
                'Develop the ability to discuss deep topics in Japanese — reaching true best-friend level.',
                'Complete your ability to converse naturally and equally with native speakers, including cultural depth.',
            ],
            textbooks: [['Genki I', 'HelloTalk'], ['Genki II', 'LINE Stickers Japanese'], ['Tsunagu Nihongo', 'Tandem'], ['Quartet I', 'Japanese Dramas (Subtitled)'], ['Quartet II', 'Japanese Variety Shows'], ['Tobira', 'Japanese YouTubers'], ['Native Materials', 'Sharehouse Conversations']],
            aiPrompt: [
                'I want to make friends with a Japanese person I just met. Teach me 3 self-introduction phrases that are friendly but not rude.',
                'Create two examples of natural LINE messages to invite someone to dinner: one for a "close friend" and one for "someone I just met."',
                'Teach me the positive and negative nuances of slang words young people use like "maji-de" and "yabai," with example sentences.',
                'List 10 empathetic Japanese phrases (like "That must have been hard") I can use when listening to a friend\'s worries.',
                'Explain what "reading the air" specifically means using a Japanese drinking party situation as an example.',
                'Teach me phrases to exchange opinions on recent news with a friend, like "I think this, but what do you think?"',
                'Teach me some Japanese jokes or "dad jokes" (oyaji gag) and explain why they are funny (wordplay, etc.).',
            ],
        },
        travel: {
            focus: [
                ['Station & airport signs', 'Numbers, time & days', 'Hiragana & katakana basics'],
                ['Restaurant ordering phrases', 'Hotel check-in', 'Asking for directions'],
                ['Transit transfers', 'Price checking while shopping', 'Tourist site questions'],
                ['Ryokan manners & conversation', 'Regional specialty vocabulary', 'Weather & health expressions'],
                ['Regional dialect basics', 'Historical site explanations', 'Chatting with locals'],
                ['Travel blog & review reading', 'Phone reservations', 'Emergency situations'],
                ['Conversation with dialects', 'Deep connections while traveling', 'Explaining Japanese culture'],
            ],
            skills: [
                ['Can read station signs', 'Can understand spoken numbers'],
                ['Can order & pay at restaurants', 'Can tell taxi where to go'],
                ['Can transfer between trains', 'Can confirm prices at shops'],
                ['Can enjoy ryokan conversations', 'Can describe health issues'],
                ['Can mostly understand dialects', 'Can small-talk with locals'],
                ['Can make phone reservations', 'Can plan trips using reviews'],
                ['Can travel solo with full independence', 'Can discover hidden gems from locals'],
            ],
            reasons: [
                'Travel starts with signs and numbers. Prioritize the bare minimum needed for getting around.',
                'Focus on "phrases you can use right now." Build confidence at restaurants and hotels.',
                'Reach independence for transit and shopping. Practice practical expressions intensively.',
                'Double the joy of travel with "omotenashi" experiences. Enjoy ryokan conversations and local cuisine talk.',
                'Learn dialect basics to enjoy natural conversations with locals at a deeper level.',
                'Become a self-sufficient traveler who can research and make phone reservations independently.',
                'Become an advanced traveler who can enjoy every corner of Japan and connect deeply with locals.',
            ],
            textbooks: [['Phrasebook', 'Google Maps'], ['Travel Japanese', 'Train Timetables'], ['Japan Travel Survival', 'Tabelog'], ['Omotenashi Japanese', 'Ryokan Booking Sites'], ['Dialect Chart', 'Rurubu (Travel Mag)'], ['Jalan (Booking Site)', 'Shinkansen App'], ['National Guides', 'Local Newspapers']],
            aiPrompt: [
                'I am lost at a station in Japan. Teach me a polite phrase to ask station staff "How to get to Shinjuku Station" and "How long it takes."',
                'I entered a restaurant in Japan. Create a phrase to say I have an allergy (e.g., shrimp) and ask for a menu without it.',
                'Explain basic manners I should know when staying at a Ryokan (taking off shoes, hot spring etiquette) in simple Japanese.',
                'Simulate a conversation where I ask a shop clerk "What do you recommend?" and ask for the reason.',
                'I am traveling to Kansai (Osaka/Kyoto). Teach me 5 simple Kansai-ben phrases (like "ookini") to use with shop staff.',
                'I want to book a restaurant by phone. Create a script saying "I would like to make a reservation for 2 people at 7 PM next Saturday."',
                'Think of 3 slightly intellectual mock questions to ask a guide about history when visiting Japanese castles or temples.',
            ],
        },
        culture: {
            focus: [
                ['Basic etiquette & manners', 'Washoku (Japanese food) names', 'Hiragana & katakana basics'],
                ['Annual event vocabulary', 'Food culture manners', 'Seasonal greetings'],
                ['Tea/flower ceremony terms', 'Kimono types', 'Traditional craft vocabulary'],
                ['Japanese history basics', 'Shinto & Buddhism basics', 'Waka poetry introduction'],
                ['Classical literature basics', 'Proverbs & idioms', 'Calligraphy basics'],
                ['Noh & Kabuki appreciation', 'Japanese art commentary', 'Seasonal words & haiku'],
                ['Classical text reading', 'Cultural debate', 'Japanese aesthetics understanding'],
            ],
            skills: [
                ['Know different types of bowing', 'Can explain chopstick etiquette'],
                ['Can explain Japanese holidays & events', 'Can describe washoku dining manners'],
                ['Understand tea ceremony flow', 'Know kimono types for occasions'],
                ['Can discuss Japanese history overview', 'Can explain shrine vs. temple differences'],
                ['Can use proverbs in daily life', 'Understand basic haiku rules'],
                ['Can appreciate & explain traditional arts', 'Can discuss Japanese art characteristics'],
                ['Can appreciate classical literature in original', 'Can deeply discuss Japanese culture'],
            ],
            reasons: [
                'The gateway to Japanese culture is etiquette and food. Learn the "form" through proper bowing and chopstick use.',
                'Learn Japan\'s connection to nature through seasonal events. Using seasonal greetings impresses Japanese people.',
                'Experience "way" culture (tea, flowers) and deepen your understanding of "wabi-sabi."',
                'Learn the history and religion behind the culture. Deeper knowledge transforms the quality of cultural experiences.',
                'Encounter classical expressions and proverbs, savoring the cultural wisdom embedded in Japanese.',
                'From traditional performing arts to fine arts — reach a level where you can appreciate and explain Japan\'s cultural essence.',
                'Read classics in the original, reaching a level of understanding and discussion equal to native speakers.',
            ],
            textbooks: [['Intro to Japanese Culture', 'Chopstick Tutorials'], ['Japanese Annual Events', 'Japanese Calendar'], ['Tea Ceremony Intro', 'Traditional Crafts Guide'], ['Japanese History Manga', 'Shrine Test Text'], ['Children\'s Analects', 'Hyakunin Isshu'], ['Kabuki Guide', 'Art History Intro'], ['Tale of Genji (Original/Modern)', 'Fushikaden']],
            aiPrompt: [
                'Explain the difference between Japanese bows (eshaku, keirei, saikeirei) and when to use each.',
                'Teach me Japanese phrases to explain the spiritual meaning of "Itadakimasu" and "Gochisousama" to foreigners.',
                'Briefly explain the Japanese aesthetic of "Wabi-Sabi" in Japanese, using moss or tea bowls as examples.',
                'Compare the differences between shrines and temples (worship methods, what is enshrined) and create a word list for each.',
                'Explain the meaning of the famous proverb "Ishi no ue ni mo sannen" and modern situations where it is used.',
                'I am going to see Kabuki for the first time. Teach me 3 points a beginner should know about unique calls and how to enjoy it.',
                'Explain the modern translation of the opening of "The Tale of Genji" and its unique atmosphere and cultural background.',
            ],
        },
        live: {
            focus: [
                ['Convenience store & supermarket signs', 'How to read addresses', 'Hiragana & katakana basics'],
                ['City hall procedure terms', 'Opening bank accounts', 'Hospital reception'],
                ['Rental contract terms', 'Electricity, gas & water', 'Mail & delivery services'],
                ['Neighborhood association vocabulary', 'School-related terms', 'Insurance & pension'],
                ['Tax return basics', 'Real estate vocabulary', 'PTA & community activities'],
                ['Basic legal terms', 'Job change & career consulting', 'Childcare support systems'],
                ['All administrative procedures', 'Civic activities & volunteering', 'Deep understanding of Japanese society'],
            ],
            skills: [
                ['Can shop at convenience stores', 'Can write your address in Japanese'],
                ['Can submit move-in forms at city hall', 'Can open a bank account'],
                ['Understand key rental contract points', 'Can inquire about utility bills'],
                ['Can small-talk with neighbors', 'Can understand school letters'],
                ['Can understand tax return documents', 'Can participate in community activities'],
                ['Can understand legal rights', 'Can job-hunt in Japanese'],
                ['Fully integrated into Japanese society', 'Handle all admin independently'],
            ],
            reasons: [
                'Life in Japan starts with convenience stores and addresses. Prioritize words you\'ll use every day.',
                'Complete life infrastructure procedures independently. City hall, bank, and hospital come first.',
                'Stabilize your living foundation. Focus on rental contracts and utility terminology.',
                'Time to integrate into the local community. Expand vocabulary for neighborhood and school interactions.',
                'Deepen knowledge for long-term living. Put down roots through taxes and community activities.',
                'Build advanced Japanese for career advancement and legal procedures.',
                'Aim for complete integration into Japanese society, living comfortably in every situation.',
            ],
            textbooks: [['Japanese for Life', 'Supermarket Flyers'], ['City Hall Guide', 'Medical Japanese'], ['Reading Contracts', 'Rental Sites'], ['PTA Handbook', 'Circular Notices'], ['Tax Return Guide', 'Disaster Maps'], ['Business Law Intro', 'Hello Work Job Slips'], ['Understanding Japanese Society', 'Newspaper Editorials']],
            aiPrompt: [
                'Reproduce a natural interaction at a Japanese convenience store asking to warm up a bento and get chopsticks and a bag.',
                'Simulate a conversation at a hospital reception to convey "I have had a fever since yesterday and my throat hurts."',
                'I am looking for an apartment at a real estate agency. Create a dialogue conveying "Rent under 70,000 yen, within 10 min walk from station."',
                'Garbage sorting rules are confusing. Teach me a conversation to ask a neighbor "Which day should I put out this plastic?"',
                'Write a polite message for a child\'s school contact book saying "He will be absent tomorrow due to a cold."',
                'Explain basic keywords beginners should know about year-end tax adjustment and tax returns in Japan (deductions, withholding, etc.).',
                'Think of a self-introduction speech for a neighborhood association meeting saying "I am still studying Japanese, but nice to meet you."',
            ],
        },
        work: {
            focus: [
                ['Business greetings', 'Business card exchange flow', 'Hiragana & katakana basics'],
                ['Business email templates', 'Phone answering', 'Company self-introduction'],
                ['Meeting minutes writing', 'Ho-Ren-So culture', 'Keigo system'],
                ['Presentation materials', 'Meeting speaking patterns', 'Negotiation expressions'],
                ['Reading contracts', 'Reports & documents', 'Office politics vocabulary'],
                ['Management strategy vocabulary', 'IR & financial terms', 'Leadership expressions'],
                ['Executive-level Japanese', 'M&A & legal terms', 'Speeches & lectures'],
            ],
            skills: [
                ['Can exchange business cards', 'Can greet properly in business settings'],
                ['Can write template business emails', 'Can transfer phone calls'],
                ['Can write meeting minutes', 'Can do Ho-Ren-So with superiors'],
                ['Can present opinions in meetings', 'Can create presentation materials'],
                ['Can understand contracts', 'Can write reports in Japanese'],
                ['Can participate in management meetings', 'Can lead teams in Japanese'],
                ['Can present to executives', 'Can handle all business in Japanese'],
            ],
            reasons: [
                'First impressions in business are made through greetings and card exchange. Master the proper form first.',
                'Email and phone are daily business basics. Master templates to become immediately productive.',
                '"Ho-Ren-So" is the lifeblood of Japanese companies. Build your communication foundation with colleagues.',
                'Strengthen your output skills. Stand out through meeting participation and presentations.',
                'Build the ability to read and write documents accurately, earning professional trust.',
                'Aim for managerial-level Japanese for team management and strategic discussions.',
                'The highest level of business Japanese for executive roles. Handle any situation with confidence.',
            ],
            textbooks: [['Keigo Training', 'Business Card Manners'], ['Business Writing', 'Phone Manuals'], ['Manga Ho-Ren-So', 'Meeting Japanese'], ['Presentation Japanese', 'Logical Speaking'], ['Business Contracts', 'Internal Reports'], ['Nikkei Business', 'Drucker (JP Ver)'], ['HBR Japan', 'Corporate Law']],
            aiPrompt: [
                'Teach me the correct step-by-step procedure for exchanging business cards in Japan, with dialogue.',
                'Create an example of a polite business email asking a client "I would like to change the meeting date."',
                'Create an appropriate conversation flow for reporting progress to a boss (Ho-Ren-So) starting with "Actually, there is a problem..."',
                'Teach me 5 variations of phrases to point out concerns in a meeting while agreeing, like "I agree basically, but just one point..."',
                'Explain the usage of "Osewa ni natte orimasu," "Otsukaresama desu," and "Gokurosama desu" and their NG scenes.',
                'Create an opening speech for a business presentation that apologizes for a project failure but proposes improvements sincerely.',
                'Teach me ideal praise words a Japanese boss uses to motivate subordinates (like "Sasuga da ne, kitai ijo da yo").',
            ],
        },
        beauty: {
            focus: [
                ['Beautiful hiragana stroke order', 'Katakana origins', 'Characteristics of Japanese sounds'],
                ['50 basic kanji stroke order', 'On\'yomi vs. kun\'yomi', 'Beauty of onomatopoeia'],
                ['Kanji radicals & meanings', 'Beautiful handwriting practice', 'Seasonal vocabulary'],
                ['Keigo system & beauty', 'Letter writing', 'Traditional color names'],
                ['Haiku basic rules', 'Waka appreciation', 'Calligraphy basics'],
                ['Tanka & poetry creation', 'Beauty of classical words', 'Japanese phonetic rhythm'],
                ['Complete literary expression mastery', 'Calligraphy mastery', 'Embodying Japanese aesthetics'],
            ],
            skills: [
                ['Can write hiragana beautifully', 'Can feel the beauty of Japanese vowels'],
                ['Can write 50 kanji with correct stroke order', 'Can explain kanji origins'],
                ['Can guess kanji meaning from radicals', 'Can write seasonal letters'],
                ['Can use keigo beautifully', 'Can write elegant letters on stationery'],
                ['Can compose haiku', 'Can understand waka imagery'],
                ['Can create tanka poems', 'Can appreciate classical Japanese beauty'],
                ['Complete understanding of Japanese sound beauty', 'Mastery of calligraphy art'],
            ],
            reasons: [
                'The beauty of Japanese starts with character shapes and sound. Careful stroke-by-stroke learning cultivates aesthetic sense.',
                'Learning kanji origins reveals the depth of meaning in each character. Writing becomes twice as enjoyable.',
                'Systematic kanji understanding and beautiful seasonal words. This stage treasures the warmth of handwriting.',
                'Keigo is the crystallization of Japanese beauty. Mastering its use lets you feel the language\'s depth.',
                'Experience the beauty of Japanese condensed into 17 and 31 syllables through haiku and waka.',
                'Enter the joy of creative writing. Touch the unique beauty and depth of classical Japanese.',
                'The final stage: savoring the complete beauty of Japanese — sound, form, and meaning.',
            ],
            textbooks: [['Calligraphy Practice', 'Hiragana Chart'], ['Kanji Origins', 'Beautiful Words Dict'], ['Japanese Colors', 'Seasonal Words'], ['Aesthetics of Keigo', 'Letter Writing'], ['Haiku Almanac', 'Manyoshu Intro'], ['Kokin Wakashu', 'Tale of the Bamboo Cutter'], ['Tale of Genji', 'Pillow Book']],
            aiPrompt: [
                'Teach me tips to write hiragana "a" and "no" beautifully and balanced, relating them to shapes (triangle, circle).',
                'Introduce 5 beautiful Japanese words related to "rain" (samidare, shigure, etc.) and explain the scenery of each.',
                'Teach me seasonal greetings (jikou no aisatsu) used in letter openings like "Haikei, sakura no kisetsu..." for each of the 4 seasons.',
                'Introduce some Japanese expressions that convey love indirectly and elegantly, like "The moon is beautiful, isn\'t it?"',
                'I want to make Haiku. Create and explain 3 beginner examples using "Summer" and "Sea" as themes.',
                'Select 10 Japanese onomatopoeia with particularly beautiful sounds (like "shitoshito," "kirakira").',
                'Select one famous romantic poem from Hyakunin Isshu and explain its meaning and background in a modern way.',
            ],
        },
        challenge: {
            focus: [
                ['Complete hiragana & katakana memorization', '100 basic kanji', 'Japanese sentence structure'],
                ['All N5 grammar patterns', '300 vocabulary words', 'N5 mock test prep'],
                ['N4 grammar mastery', '800 vocabulary words', 'N4 mock test prep'],
                ['N3 grammar system', '1500 vocabulary words', 'Intermediate reading practice'],
                ['N2 grammar patterns', '3000 vocabulary words', 'Long-text reading & listening'],
                ['N1 grammar & vocabulary', 'Abstract expressions', 'N1 practical exercises'],
                ['Ultra-advanced expressions', 'Academic paper reading', 'Native-level achievement'],
            ],
            skills: [
                ['Complete hiragana & katakana mastery', 'Can read/write 100 basic kanji'],
                ['N5 mock test passing level', 'Can answer basic questions'],
                ['Reached N4 level', 'Can handle daily conversations'],
                ['Within N3 passing range', 'Can read news headlines'],
                ['Can solve N2 level problems', 'Can understand news broadcasts'],
                ['Aiming for N1 pass', 'Competent in business settings'],
                ['Japanese master', 'Can use Japanese freely in any situation'],
            ],
            reasons: [
                'Every challenge starts with fundamentals. Thoroughly understand characters and sentence structure for a solid foundation.',
                'Target N5 complete mastery, systematically building grammar and vocabulary. Verify with mock tests.',
                'Aim for N4 level, expanding grammar patterns and strengthening daily conversation simultaneously.',
                'N3 is the gateway to intermediate. Organize grammar systems and rapidly boost reading comprehension.',
                'N2 proves practical ability. Strategically target long-text reading and listening score improvements.',
                'N1 is the pinnacle for Japanese learners. Tackle abstract vocabulary and complex grammar patterns.',
                'Beyond N1 to true Japanese mastery. Complete freedom in academic, business, and daily situations.',
            ],
            textbooks: [['Genki I', 'Kanji Master N5'], ['Shin Kanzen Master N5', 'JLPT N5 Prep'], ['Shin Kanzen Master N4', 'Sou Matome N4'], ['Shin Kanzen Master N3', 'Sou Matome N3'], ['Shin Kanzen Master N2', 'Sou Matome N2'], ['Shin Kanzen Master N1', 'Sou Matome N1'], ['Advanced Reading', 'Learn with News']],
            aiPrompt: [
                'Create 10 conjugation practice questions for N5 essential verbs (iku, taberu, miru) covering present, past, and negative forms.',
                'Explain the difference between N4 grammar "~te wa ikemasen" (prohibition) and "~nakutemo ii desu" (not necessary) with 5 practice questions.',
                'Teach me techniques for "Task-Based Understanding" questions often found in N3 listening tests (reading questions first, taking notes, etc.).',
                'I run out of time in N2 reading. Explain tips for speed reading and how to focus on conjunctions (shikashi, tsumari).',
                'Propose some mnemonics or story memory methods to remember difficult N1 kanji (like "chucho," "kairi").',
                'Give me advice on what to do in the week before the JLPT (daily rhythm, review priorities).',
                'Correct my short essay ([Insert text here]) and rewrite it into more natural, advanced Japanese expressions.',
            ],
        },
        other: {
            focus: [
                ['Hiragana & Katakana', 'Basic greetings', 'Numbers & time'],
                ['N5 basic grammar', '200 daily vocabulary', 'Simple sentence building'],
                ['N4 grammar patterns', '500 vocabulary milestone', 'Keigo basics'],
                ['N3 grammar', '1000 vocabulary', 'Intermediate reading'],
                ['N3→N2 transition', 'Abstract vocabulary', 'Long-text reading'],
                ['N2 grammar & vocab', 'Business Japanese', 'Specialized reading'],
                ['N1 expressions', 'Nuance understanding', 'Academic Japanese'],
            ],
            skills: [
                ['Can introduce yourself', 'Can answer simple questions'],
                ['Basic shopping conversations', 'Can ask for directions'],
                ['Can order at restaurants', 'Can write casual emails'],
                ['Can read news headlines', 'Can state opinions'],
                ['Can understand TV news', 'Can join discussions'],
                ['Can speak in meetings', 'Can write reports'],
                ['Can read academic papers', 'Can give presentations'],
            ],
            reasons: [
                'Master the Japanese writing system and essential expressions for first communication.',
                'Build minimum Japanese for real-life use and basic daily conversations.',
                'Solidify Japanese needed for daily life and natural conversations.',
                'Understand complex expressions as a gateway to business and academic Japanese.',
                'Polish practical Japanese skills for use in work and studies.',
                'Acquire advanced skills to use Japanese professionally.',
                'Aim for near-native proficiency to use Japanese confidently in any situation.',
            ],
            textbooks: [['Tae Kim\'s Guide', 'Duolingo'], ['Genki I', 'Anki Core 2k'], ['Genki II', 'NHK Easy Japanese'], ['Tobira Gateway', 'News Web Easy'], ['Tobira Advanced', 'Japanese Novels'], ['New Kanzen Master N1', 'Japanese News'], ['Read Japanese Society', 'Academic Papers']],
            aiPrompt: [
                'Explain the difference between Japanese "wa" and "ga" using simple example sentences a beginner can understand.',
                'Teach me 3 of the most basic and natural ordering phrases to use at restaurants or shops in Japan.',
                'Japanese counters (ippon, ippiki, ichimai) are hard to remember. Teach me the top 5 most used counters and how to remember them.',
                'Create a usage chart for Keigo (Teineigo, Sonkeigo, Kenjougo) showing representative verb changes (iku -> ikimasu, irasshaimasu, mairimasu).',
                'Summarize this recent Japanese news article ([Insert article here]) and rewrite it into simple Japanese a dictionary school student could understand.',
                'Teach me a short script for shadowing practice to improve my pronunciation, along with practice points.',
                'Teach me variations of "Aizuchi" (nodding/responses) Japanese use in conversation ("Hee," "Sou nanda," "Naruhodo") and how to use them.',
            ],
        },
    },
};

