import type { Translations } from './index';

export const pt: Translations = {
    title: 'Roteiro de Aprendizado de Japonês',
    subtitle: 'Crie seu plano de estudo personalizado',
    currentLevel: 'Nível Atual',
    targetLevel: 'Nível Alvo',
    learningPeriod: 'Período de Estudo',
    months: ' meses',
    monthUnit: ' meses',
    beginner: 'Iniciante',
    native: 'Nativo',
    purpose: 'Por que você quer aprender japonês?',
    createRoadmap: '📚 Criar Roteiro',
    selectPurpose: 'Selecione seu objetivo',
    levelDescriptions: { n5: 'JLPT N5', n4: 'JLPT N4', n3: 'JLPT N3', n2: 'JLPT N2', n1: 'JLPT N1', nativeLevel: 'Nativo' },
    purposes: {
        anime: { label: 'Anime, Mangá e Jogos', description: 'Curtir sem legendas' },
        friends: { label: 'Fazer Amigos/Parceiro', description: 'Relações profundas com japoneses' },
        travel: { label: 'Viajar pelo Japão', description: 'Explorar livremente' },
        culture: { label: 'Cultura Japonesa', description: 'Tradições e gastronomia' },
        live: { label: 'Morar no Japão', description: 'Vida segura e confortável' },
        work: { label: 'Trabalhar no Japão', description: 'Japonês para negócios' },
        beauty: { label: 'Japonês é Bonito', description: 'Sons e caracteres fascinantes' },
        challenge: { label: 'Desafio Pessoal', description: 'Curiosidade e crescimento' },
        other: { label: 'Outro', description: 'Outros objetivos' },
    },
    planSummary: '📊 Resumo do seu Plano',
    totalHours: 'Horas Totais',
    hoursPerWeek: 'hrs/sem',
    levelUp: 'Subir de Nível',
    current: 'Atual',
    goal: 'Meta',
    dailyStudy: 'Aproximadamente ',
    hoursUnit: ' horas',
    achievable: ' por dia para alcançar sua meta!',
    growthChart: 'Previsão de Crescimento',
    now: 'Agora',
    monthsLater: 'm depois',
    level: 'Nível',
    lessonDistribution: 'Distribuição de Aulas',
    optimizedForYou: 'Equilíbrio otimizado para seus objetivos',
    whyThisBalance: 'Por que esse equilíbrio?',
    lessonTypes: { grammar: 'Gramática', vocabulary: 'Vocabulário', conversation: 'Conversação', reading: 'Leitura', listening: 'Compreensão auditiva' },
    monthlyMilestones: 'Marcos Mensais',
    monthN: '',
    targetLevelLabel: 'Objetivo',
    purposeStep: 'Passos rumo ao seu objetivo',
    learningContent: '🎯 Foco deste mês',
    achievedSkills: '✅ Habilidades conquistadas',
    whyThisOrder: '📌 Por que essa ordem?',
    recommendedLessons: 'Aulas recomendadas',
    textbooksLabel: 'Livros Didáticos',
    aiPromptLabel: 'Prompt de IA',

    lessonsPerMonth: '/mês',
    roadmapComplete: '🎉 Seu Roteiro Personalizado está Pronto!',
    ctaDescription: 'Com este plano, você com certeza alcançará sua meta.',
    ctaPeriod: ' em ',
    ctaFrom: 'De ',
    ctaTo: ' para ',
    startFreeTrial: '✨ Começar Teste Gratuito',
    shareThisPlan: 'Compartilhar este Plano',
    generating: 'Gerando...',
    trialBooked: 'Teste gratuito agendado!',
    imageError: 'Falha ao gerar imagem',
    shareOpened: 'Menu de compartilhamento aberto',
    downloaded: 'Imagem baixada',
    errorOccurred: 'Ocorreu um erro',
    distributionReasons: {
        anime: { beginner: 'Para entender japonês de anime, escuta é fundamental. Treinaremos seu ouvido para expressões coloquiais enquanto construímos base de gramática e vocabulário.', advanced: 'Além de escutar, você precisará ler diálogos de mangá e textos de jogos. Foco em japonês coloquial, gírias e onomatopeias.' },
        friends: { beginner: 'Para conectar com pessoas, falar vem primeiro. Mesmo com gramática simples, poder conversar aprofunda relacionamentos.', advanced: 'Relações profundas exigem nuances e emoções precisas. Praticaremos alternância entre formal e informal e "ler o ambiente".' },
        travel: { beginner: 'Japonês de viagem: "frases para usar agora". Priorizamos vocabulário de estações, restaurantes e hotéis.', advanced: 'Entender dialetos regionais e se comunicar onde inglês não funciona. Ler placas e conversar com moradores locais.' },
        culture: { beginner: 'Entender cultura japonesa requer leitura. Priorizamos vocabulário de etiqueta, eventos e gastronomia.', advanced: 'Expressões clássicas, provérbios, estilo epistolar — saborear a profundidade da cultura japonesa.' },
        live: { beginner: '"Japonês de sobrevivência": prefeitura, hospitais, bancos, imóveis — tudo para o dia a dia.', advanced: 'Relações de vizinhança, PTA, associações comunitárias. Keigo correto e regras sociais japonesas.' },
        work: { beginner: 'Japonês de negócios: "keigo correto". Emails, telefone, apresentações profissionais.', advanced: 'Reuniões, apresentações, negociações, relatórios — japonês que inspira confiança profissional.' },
        beauty: { beginner: 'Para apreciar o belo japonês, começamos pelos caracteres. Traços de hiragana/katakana, origens do kanji, ritmo do japonês.', advanced: 'Haiku, tanka, expressões poéticas, vocabulário sazonal — a essência da beleza japonesa.' },
        challenge: { beginner: 'Crescimento equilibrado é mais eficiente. Entender a estrutura do japonês logicamente.', advanced: 'Preparação JLPT: melhorar leitura e escuta. Gramática avançada e vocabulário abstrato.' },
        other: { beginner: 'Plano equilibrado para 5 habilidades. Conte seus objetivos na aula gratuita!', advanced: 'Plano abrangente para todas as habilidades. Personalização disponível na aula gratuita!' },
    },
    purposeMilestones: {
        anime: ['Ler letras de openings 🎵', 'Captar cumprimentos simples em anime 👂', 'Entender 80% do anime legendado 📺', 'Acompanhar episódio sem legendas 🎉', 'Jogar jogos japoneses sem dicionário 🎮', 'Ler mangá no japonês original 📖', 'Entender diálogos complexos e nuances ✨'],
        friends: ['Se apresentar e falar de hobbies 👋', 'Trocar mensagens no LINE 📱', 'Conversar no café por 30 minutos ☕', 'Expressar sentimentos em japonês 💬', 'Entender piadas e rir junto 😄', 'Conversar sobre temas profundos 🤝', 'Brigar e fazer as pazes em japonês 💪'],
        travel: ['Ler placas de estação 🚃', 'Pedir e pagar em restaurantes 🍣', 'Pedir e entender direções 🗺️', 'Conversar com staff do ryokan ♨️', 'Entender dialetos regionais 🏔️', 'Viajar sozinho sem guia 🎒', 'Fazer amigos locais e descobrir lugares secretos 🌸'],
        culture: ['Usar boas maneiras corretamente 🙇', 'Conhecer feriados japoneses 🎎', 'Explicar culinária japonesa 🍱', 'Entender termos da cerimônia do chá 🍵', 'Discutir história japonesa 🏯', 'Apreciar haiku e tanka 📝', 'Apreciar a cultura no nível nativo 🌊'],
        live: ['Comprar em lojas sem problemas 🏪', 'Resolver procedimentos na prefeitura 📋', 'Descrever sintomas no hospital 🏥', 'Conversar com vizinhos 🏘️', 'Entender contratos bancários 📄', 'Participar de reuniões do PTA 🤝', 'Viver no Japão de forma independente 🏠'],
        work: ['Cumprimentos de negócios e cartões 💼', 'Escrever emails de negócios ✉️', 'Atender ligações telefônicas 📞', 'Apresentar ideias em reuniões 🎤', 'Negociar sem intérprete 🤝', 'Fazer apresentações em japonês 📊', 'Liderar equipe em japonês 🏆'],
        beauty: ['Escrever hiragana/katakana bonito ✍️', 'Dominar traços de 50 kanji 📝', 'Apreciar a beleza do keigo 🌸', 'Escrever cartas elegantes ✉️', 'Tentar escrever haiku/tanka 🖊️', 'Distinguir nuances sutis ✨', 'Apreciar plenamente os sons japoneses 🎵'],
        challenge: ['Dominar hiragana, katakana e kanji básico 🏅', 'Resolver exercícios N5 📚', 'Atingir nível de aprovação N4 🎯', 'Entrar na faixa N3 💪', 'Pronto para N2 🔥', 'Mirar aprovação N1 🏆', 'Mestre do japonês! Qual língua vem a seguir? 🌍'],
        other: ['Base sólida de japonês 📖', 'Conversas diárias simples 💬', 'Expressar ideias em japonês ✍️', 'Buscar informações em japonês 🔍', 'Conversar sobre vários temas 🗣️', 'Entender conteúdo especializado 📊', 'Usar japonês naturalmente ✨'],
    },
    monthlyContent: {
        focus: [['Hiragana e Katakana', 'Cumprimentos', 'Números e horas'], ['Gramática N5', '200 palavras', 'Frases simples'], ['Gramática N4', '500 palavras', 'Keigo básico'], ['Gramática N3', '1000 palavras', 'Leitura intermediária'], ['N3→N2', 'Vocabulário abstrato', 'Textos longos'], ['Gramática N2', 'Japonês de negócios', 'Leitura especializada'], ['Expressões N1', 'Nuances', 'Japonês acadêmico']],
        skills: [['Se apresentar', 'Responder perguntas simples'], ['Compras básicas', 'Pedir direções'], ['Pedir em restaurantes', 'Escrever emails'], ['Ler manchetes', 'Expressar opiniões'], ['Entender notícias', 'Participar de discussões'], ['Falar em reuniões', 'Escrever relatórios'], ['Ler artigos acadêmicos', 'Dar apresentações']],
        reasons: ['Dominar escrita japonesa e expressões essenciais.', 'Japonês mínimo para uso real e conversas básicas.', 'Japonês para vida diária e conversas naturais.', 'Expressões complexas para negócios e academia.', 'Habilidades práticas para trabalho e estudos.', 'Habilidades avançadas para uso profissional.', 'Competência quase nativa em qualquer situação.'],
    },
    purposeMonthlyContent: {
        anime: {
            focus: [['Cumprimentos e exclamações de anime', 'Nomes em katakana', 'Hiragana/katakana'], ['50 frases típicas de anime', 'Vocabulário anime diário', 'Escuta de diálogos'], ['Conversa do dia a dia', 'Diálogos de mangá', 'Onomatopeias'], ['Casual vs. formal', 'UI de jogos', 'Emoções anime'], ['Termos de gênero', 'Guias de jogos', 'Gírias e linguagem jovem'], ['Enredos complexos', 'Light novels', 'Dialetos'], ['Metáforas literárias', 'Análises de anime', 'Velocidade nativa']], skills: [['Ler letras de opening', 'Pronunciar nomes de personagens'], ['Entender exclamações', 'Captar cumprimentos em anime'], ['Ler diálogos de mangá', 'Entender 50% anime legendado'], ['Entender 80% anime legendado', 'Ler textos RPG'], ['Seguir anime sem legendas', 'Jogar em japonês'], ['Curtir mangá original', 'Entender metáforas'], ['Compreensão total de nuances', 'Discutir anime em japonês']], reasons: ['Ler letras e nomes mantém a motivação alta.', 'Expressões coloquiais de anime para habilidades práticas.', 'Escuta + leitura para potencializar seu japonês de anime.', 'Dominar a mudança casual-formal.', 'Jargão de gênero para assistir sem legendas.', 'Entender dialetos e estruturas narrativas profundas.', 'Curtir no mesmo nível que um nativo.'],
            textbooks: [['Genki I', 'Anime Scripts'], ['Genki II', 'Yotsuba&! (Manga)'], ['Quartet I', 'Slice of Life Anime Scripts'], ['Quartet II', 'Shonen Manga (with Furigana)'], ['Tobira', 'RPG Game Scripts'], ['Shin Kanzen Master N1', 'Light Novels (Easy)'], ['Native Materials', 'Anime Scenarios']],
            aiPrompt: [
                'You are a Japanese teacher who loves anime. Teach me 5 basic greeting phrases a beginner should know, speaking in an energetic tone like Luffy from One Piece.',
                'Explain the nuance and usage of sentence endings like "~daze" and "~kashira" often found in anime, with character dialogue examples.',
                'Analyze the polite yet strong speaking style of Tanjiro from Demon Slayer and create 3 phrases I can use in daily life.',
                'Create 5 "tsundere" lines for an anime character, explaining the grammatical structure and emotional nuance of each.',
                'List 20 important words related to "magic," "equipment," and "adventure" frequent in fantasy RPGs, with example sentences.',
                'Reproduce lines of an anime character using Kyoto dialect (Kansai-ben) and explain the difference from standard Japanese.',
                'Write a philosophical monologue in Japanese like in "Neon Genesis Evangelion" and explain the abstract vocabulary used.',
            ],
        },
        friends: {
            focus: [['Autoapresentação', 'Cumprimentos casuais', 'Hiragana/katakana'], ['Expressões LINE/SNS', 'Vocabulário hobbies', 'Aizuchi'], ['Casual-formal', 'Emoções', 'Convidar/recusar'], ['Opiniões', 'Humor', 'Casual vs. keigo'], ['Preocupações/conselhos', 'Nuances sutis', 'Ler o ambiente'], ['Debate', 'Temas profundos', 'Dialetos'], ['Sarcasmo/figurado', 'Valores japoneses', 'Velocidade nativa']], skills: [['Apresentar-se e hobbies', 'Cumprimentos "yoroshiku"'], ['Chat no LINE', 'Perguntar sobre hobbies'], ['30 min de conversa', 'Convidar/recusar'], ['Expressar sentimentos', 'Fazer rir'], ['Discutir preocupações', 'Ler o ambiente'], ['Conversas profundas', 'Dialetos'], ['Brigar/reconciliar', 'Igualdade com nativos']], reasons: ['Amizades começam com apresentação. Hobbies em comum iniciam relações.', 'LINE é base da amizade moderna.', 'Resistência para conversas de café. Convidar e recusar naturalmente.', 'Sentimentos + humor para conversas envolventes.', 'Entender "ler o ambiente" para confiança profunda.', 'Debater temas profundos — nível melhor amigo.', 'Conversa natural e igualitária com nativos.'],
            textbooks: [['Genki I', 'HelloTalk'], ['Genki II', 'LINE Stickers Japanese'], ['Tsunagu Nihongo', 'Tandem'], ['Quartet I', 'Japanese Dramas (Subtitled)'], ['Quartet II', 'Japanese Variety Shows'], ['Tobira', 'Japanese YouTubers'], ['Native Materials', 'Sharehouse Conversations']],
            aiPrompt: [
                'I want to make friends with a Japanese person I just met. Teach me 3 self-introduction phrases that are friendly but not rude.',
                'Create two examples of natural LINE messages to invite someone to dinner: one for a "close friend" and one for "someone I just met."',
                'Teach me the positive and negative nuances of slang words young people use like "maji-de" and "yabai," with example sentences.',
                'List 10 empathetic Japanese phrases (like "That must have been hard") I can use when listening to a friend\'s worries.',
                'Explain what "reading the air" specifically means using a Japanese drinking party situation as an example.',
                'Teach me phrases to exchange opinions on recent news with a friend, like "I think this, but what do you think?"',
                'Teach me some Japanese jokes or "dad jokes" (oyaji gag) and explain why they are funny (wordplay, etc.).',
            ],
        },
        travel: {
            focus: [['Placas estação/aeroporto', 'Números/hora/dias', 'Hiragana/katakana'], ['Pedir em restaurante', 'Check-in hotel', 'Direções'], ['Baldeações', 'Preços compras', 'Perguntas turismo'], ['Maneiras ryokan', 'Especialidades locais', 'Clima/saúde'], ['Dialetos regionais', 'Sítios históricos', 'Conversar com locais'], ['Blogs/reviews viagem', 'Reservas tel.', 'Emergências'], ['Dialetos viagem', 'Conexões profundas', 'Cultura japonesa']], skills: [['Ler placas estação', 'Entender números'], ['Pedir/pagar restaurante', 'Destino ao táxi'], ['Baldeações trem', 'Confirmar preços'], ['Conversas ryokan', 'Descrever sintomas'], ['Entender dialetos', 'Conversar com locais'], ['Reservas tel.', 'Planejar com reviews'], ['Viagem solo independente', 'Lugares secretos locais']], reasons: ['Placas e números é prioridade no início.', 'Frases utilizáveis agora para restaurantes/hotéis.', 'Independência em transporte e compras.', '"Omotenashi" dobra a alegria da viagem.', 'Dialetos para conversas naturais com locais.', 'Viajante autossuficiente: pesquisa e reservas.', 'Viajante avançado conectado com locais.'],
            textbooks: [['Phrasebook', 'Google Maps'], ['Travel Japanese', 'Train Timetables'], ['Japan Travel Survival', 'Tabelog'], ['Omotenashi Japanese', 'Ryokan Booking Sites'], ['Dialect Chart', 'Rurubu (Travel Mag)'], ['Jalan (Booking Site)', 'Shinkansen App'], ['National Guides', 'Local Newspapers']],
            aiPrompt: [
                'I am lost at a station in Japan. Teach me a polite phrase to ask station staff "How to get to Shinjuku Station" and "How long it takes."',
                'I entered a restaurant in Japan. Create a phrase to say I have an allergy (e.g., shrimp) and ask for a menu without it.',
                'Explain basic manners I should know when staying at a Ryokan (taking off shoes, hot spring etiquette) in simple Japanese.',
                'Simulate a conversation where I ask a shop clerk "What do you recommend?" and ask for the reason.',
                'I am traveling to Kansai (Osaka/Kyoto). Teach me 5 simple Kansai-ben phrases (like "ookini") to use with shop staff.',
                'I want to book a restaurant by phone. Create a script saying "I would like to make a reservation for 2 people at 7 PM next Saturday."',
                'Think of 3 slightly intellectual mock questions to ask a guide about history when visiting Japanese castles or temples.',
            ],
        },
        culture: {
            focus: [['Etiqueta básica', 'Culinária japonesa', 'Hiragana/katakana'], ['Eventos anuais', 'Cultura gastronômica', 'Cumprimentos sazonais'], ['Chá/flores', 'Tipos kimono', 'Artesanato'], ['História japonesa', 'Xintoísmo/budismo', 'Waka'], ['Literatura clássica', 'Provérbios', 'Caligrafia'], ['Noh/Kabuki', 'Arte japonesa', 'Haiku/estações'], ['Textos clássicos', 'Debate cultural', 'Estética']], skills: [['Tipos de reverência', 'Etiqueta de hashi'], ['Festas japonesas', 'Maneiras washoku'], ['Cerimônia do chá', 'Kimonos/ocasiões'], ['História japonesa', 'Templo vs santuário'], ['Provérbios no dia a dia', 'Regras haiku'], ['Artes tradicionais', 'Arte japonesa'], ['Literatura clássica original', 'Discussão cultural profunda']], reasons: ['Etiqueta e comida são a porta da cultura.', 'Eventos sazonais para entender a natureza.', 'Cultura do "caminho" e "wabi-sabi".', 'História e religião transformam a experiência cultural.', 'Provérbios e sabedoria cultural do japonês.', 'Artes cênicas e belas-artes japonesas.', 'Ler clássicos em original como um nativo.'],
            textbooks: [['Intro to Japanese Culture', 'Chopstick Tutorials'], ['Japanese Annual Events', 'Japanese Calendar'], ['Tea Ceremony Intro', 'Traditional Crafts Guide'], ['Japanese History Manga', 'Shrine Test Text'], ['Children\'s Analects', 'Hyakunin Isshu'], ['Kabuki Guide', 'Art History Intro'], ['Tale of Genji (Original/Modern)', 'Fushikaden']],
            aiPrompt: [
                'Explain the difference between Japanese bows (eshaku, keirei, saikeirei) and when to use each.',
                'Teach me Japanese phrases to explain the spiritual meaning of "Itadakimasu" and "Gochisousama" to foreigners.',
                'Briefly explain the Japanese aesthetic of "Wabi-Sabi" in Japanese, using moss or tea bowls as examples.',
                'Compare the differences between shrines and temples (worship methods, what is enshrined) and create a word list for each.',
                'Explain the meaning of the famous proverb "Ishi no ue ni mo sannen" and modern situations where it is used.',
                'I am going to see Kabuki for the first time. Teach me 3 points a beginner should know about unique calls and how to enjoy it.',
                'Explain the modern translation of the opening of "The Tale of Genji" and its unique atmosphere and cultural background.',
            ],
        },
        live: {
            focus: [['Placas lojas', 'Endereços', 'Hiragana/katakana'], ['Procedimentos prefeitura', 'Conta bancária', 'Hospital'], ['Contrato aluguel', 'Eletricidade/gás/água', 'Correio'], ['Associação bairro', 'Escola', 'Seguro/aposentadoria'], ['Declaração impostos', 'Imobiliário', 'PTA/comunidade'], ['Termos jurídicos', 'Carreira', 'Apoio infantil'], ['Admin geral', 'Cívico/voluntariado', 'Sociedade japonesa']], skills: [['Compras conveniência', 'Escrever endereço'], ['Formulários prefeitura', 'Abrir conta'], ['Pontos-chave contrato', 'Contas serviços'], ['Conversar vizinhos', 'Cartas escola'], ['Documentos fiscais', 'Atividades comunitárias'], ['Direitos legais', 'Buscar emprego'], ['Integração completa', 'Admin autônomo']], reasons: ['Vida no Japão: lojas e endereços primeiro.', 'Infraestrutura vital: prefeitura, banco, hospital.', 'Estabilizar base de vida com contratos e serviços.', 'Integrar-se na comunidade local.', 'Conhecimentos a longo prazo: impostos e comunidade.', 'Japonês avançado para carreira e direito.', 'Integração completa na sociedade japonesa.'],
            textbooks: [['Japanese for Life', 'Supermarket Flyers'], ['City Hall Guide', 'Medical Japanese'], ['Reading Contracts', 'Rental Sites'], ['PTA Handbook', 'Circular Notices'], ['Tax Return Guide', 'Disaster Maps'], ['Business Law Intro', 'Hello Work Job Slips'], ['Understanding Japanese Society', 'Newspaper Editorials']],
            aiPrompt: [
                'Reproduce a natural interaction at a Japanese convenience store asking to warm up a bento and get chopsticks and a bag.',
                'Simulate a conversation at a hospital reception to convey "I have had a fever since yesterday and my throat hurts."',
                'I am looking for an apartment at a real estate agency. Create a dialogue conveying "Rent under 70,000 yen, within 10 min walk from station."',
                'Garbage sorting rules are confusing. Teach me a conversation to ask a neighbor "Which day should I put out this plastic?"',
                'Write a polite message for a child\'s school contact book saying "He will be absent tomorrow due to a cold."',
                'Explain basic keywords beginners should know about year-end tax adjustment and tax returns in Japan (deductions, withholding, etc.).',
                'Think of a self-introduction speech for a neighborhood association meeting saying "I am still studying Japanese, but nice to meet you."',
            ],
        },
        work: {
            focus: [['Cumprimentos negócios', 'Cartões visita', 'Hiragana/katakana'], ['Emails modelo', 'Telefone', 'Apresentação empresa'], ['Atas reunião', 'Ho-Ren-So', 'Keigo'], ['Apresentações', 'Reuniões', 'Negociação'], ['Contratos', 'Relatórios', 'Política interna'], ['Estratégia', 'IR/finanças', 'Liderança'], ['Nível executivo', 'M&A/jurídico', 'Discursos']], skills: [['Trocar cartões', 'Cumprimentar em negócios'], ['Emails modelo', 'Transferir ligações'], ['Atas reunião', 'Ho-Ren-So superiores'], ['Opiniões em reunião', 'Criar apresentações'], ['Entender contratos', 'Relatórios em japonês'], ['Reuniões diretoria', 'Liderar em japonês'], ['Apresentar executivos', 'Tudo em japonês']], reasons: ['Primeira impressão: cumprimentos e cartões.', 'Emails e telefone para produtividade imediata.', 'Ho-Ren-So: comunicação com colegas.', 'Expressão reforçada em reuniões e apresentações.', 'Documentos precisos para confiança profissional.', 'Japonês gerencial para gestão e estratégia.', 'Mais alto nível de japonês de negócios.'],
            textbooks: [['Keigo Training', 'Business Card Manners'], ['Business Writing', 'Phone Manuals'], ['Manga Ho-Ren-So', 'Meeting Japanese'], ['Presentation Japanese', 'Logical Speaking'], ['Business Contracts', 'Internal Reports'], ['Nikkei Business', 'Drucker (JP Ver)'], ['HBR Japan', 'Corporate Law']],
            aiPrompt: [
                'Teach me the correct step-by-step procedure for exchanging business cards in Japan, with dialogue.',
                'Create an example of a polite business email asking a client "I would like to change the meeting date."',
                'Create an appropriate conversation flow for reporting progress to a boss (Ho-Ren-So) starting with "Actually, there is a problem..."',
                'Teach me 5 variations of phrases to point out concerns in a meeting while agreeing, like "I agree basically, but just one point..."',
                'Explain the usage of "Osewa ni natte orimasu," "Otsukaresama desu," and "Gokurosama desu" and their NG scenes.',
                'Create an opening speech for a business presentation that apologizes for a project failure but proposes improvements sincerely.',
                'Teach me ideal praise words a Japanese boss uses to motivate subordinates (like "Sasuga da ne, kitai ijo da yo").',
            ],
        },
        beauty: {
            focus: [['Traços hiragana', 'Origens katakana', 'Sons japoneses'], ['50 kanji traços', 'On/kun\'yomi', 'Onomatopeias'], ['Radicais kanji', 'Bela escrita', 'Vocabulário sazonal'], ['Keigo e beleza', 'Cartas', 'Cores tradicionais'], ['Regras haiku', 'Waka', 'Caligrafia'], ['Tanka/poesia', 'Japonês clássico', 'Ritmo fonético'], ['Expressão literária', 'Maestria caligráfica', 'Estética japonesa']], skills: [['Escrever hiragana bonito', 'Beleza das vogais'], ['50 kanji traços corretos', 'Origens kanji'], ['Sentido por radicais', 'Cartas sazonais'], ['Keigo elegante', 'Cartas refinadas'], ['Compor haiku', 'Imagens waka'], ['Criar tanka', 'Beleza clássica'], ['Beleza sonora completa', 'Arte caligráfica']], reasons: ['Caracteres e som: a beleza começa aqui.', 'Origens kanji: profundidade por caractere.', 'Kanji sistemático e palavras sazonais.', 'Keigo: cristalização da beleza.', 'Haiku/waka: 17 e 31 sílabas de beleza.', 'Criação literária e japonês clássico.', 'Etapa final: som, forma e significado.'],
            textbooks: [['Calligraphy Practice', 'Hiragana Chart'], ['Kanji Origins', 'Beautiful Words Dict'], ['Japanese Colors', 'Seasonal Words'], ['Aesthetics of Keigo', 'Letter Writing'], ['Haiku Almanac', 'Manyoshu Intro'], ['Kokin Wakashu', 'Tale of the Bamboo Cutter'], ['Tale of Genji', 'Pillow Book']],
            aiPrompt: [
                'Teach me tips to write hiragana "a" and "no" beautifully and balanced, relating them to shapes (triangle, circle).',
                'Introduce 5 beautiful Japanese words related to "rain" (samidare, shigure, etc.) and explain the scenery of each.',
                'Teach me seasonal greetings (jikou no aisatsu) used in letter openings like "Haikei, sakura no kisetsu..." for each of the 4 seasons.',
                'Introduce some Japanese expressions that convey love indirectly and elegantly, like "The moon is beautiful, isn\'t it?"',
                'I want to make Haiku. Create and explain 3 beginner examples using "Summer" and "Sea" as themes.',
                'Select 10 Japanese onomatopoeia with particularly beautiful sounds (like "shitoshito," "kirakira").',
                'Select one famous romantic poem from Hyakunin Isshu and explain its meaning and background in a modern way.',
            ],
        },
        challenge: {
            focus: [['Hiragana/katakana completos', '100 kanji', 'Estrutura frase'], ['Gramática N5 completa', '300 palavras', 'Simulado N5'], ['Gramática N4', '800 palavras', 'Simulado N4'], ['Gramática N3', '1500 palavras', 'Leitura intermediária'], ['Gramática N2', '3000 palavras', 'Leitura longa/escuta'], ['Gramática N1', 'Abstrato', 'Exercícios N1'], ['Ultra-avançado', 'Artigos acadêmicos', 'Nível nativo']], skills: [['Hiragana/katakana dominados', '100 kanji ler/escrever'], ['Simulado N5 aprovado', 'Perguntas básicas'], ['Nível N4 atingido', 'Conversa diária'], ['Faixa N3', 'Manchetes jornal'], ['Problemas N2', 'Entender noticiário'], ['Mirar N1', 'Competente negócios'], ['Mestre japonês', 'Livre em qualquer situação']], reasons: ['Fundamentos primeiro para base sólida.', 'Domínio N5: gramática e vocabulário sistemáticos.', 'Nível N4: gramática expandida + conversa.', 'N3: porta intermediária, compreensão leitora.', 'N2: prova de aptidão prática.', 'N1: cume, vocabulário abstrato e gramática complexa.', 'Além do N1: liberdade total.'],
            textbooks: [['Genki I', 'Kanji Master N5'], ['Shin Kanzen Master N5', 'JLPT N5 Prep'], ['Shin Kanzen Master N4', 'Sou Matome N4'], ['Shin Kanzen Master N3', 'Sou Matome N3'], ['Shin Kanzen Master N2', 'Sou Matome N2'], ['Shin Kanzen Master N1', 'Sou Matome N1'], ['Advanced Reading', 'Learn with News']],
            aiPrompt: [
                'Create 10 conjugation practice questions for N5 essential verbs (iku, taberu, miru) covering present, past, and negative forms.',
                'Explain the difference between N4 grammar "~te wa ikemasen" (prohibition) and "~nakutemo ii desu" (not necessary) with 5 practice questions.',
                'Teach me techniques for "Task-Based Understanding" questions often found in N3 listening tests (reading questions first, taking notes, etc.).',
                'I run out of time in N2 reading. Explain tips for speed reading and how to focus on conjunctions (shikashi, tsumari).',
                'Propose some mnemonics or story memory methods to remember difficult N1 kanji (like "chucho," "kairi").',
                'Give me advice on what to do in the week before the JLPT (daily rhythm, review priorities).',
                'Correct my short essay ([Insert text here]) and rewrite it into more natural, advanced Japanese expressions.',
            ],
        },
        other: {
            focus: [['Hiragana e Katakana', 'Cumprimentos', 'Números e horas'], ['Gramática N5', '200 palavras', 'Frases simples'], ['Gramática N4', '500 palavras', 'Keigo básico'], ['Gramática N3', '1000 palavras', 'Leitura intermediária'], ['N3→N2', 'Vocabulário abstrato', 'Textos longos'], ['Gramática N2', 'Japonês de negócios', 'Leitura especializada'], ['Expressões N1', 'Nuances', 'Japonês acadêmico']], skills: [['Se apresentar', 'Responder perguntas simples'], ['Compras básicas', 'Pedir direções'], ['Pedir em restaurantes', 'Escrever emails'], ['Ler manchetes', 'Expressar opiniões'], ['Entender notícias', 'Participar de discussões'], ['Falar em reuniões', 'Escrever relatórios'], ['Ler artigos acadêmicos', 'Dar apresentações']], reasons: ['Dominar escrita japonesa e expressões essenciais.', 'Japonês mínimo para uso real e conversas básicas.', 'Japonês para vida diária e conversas naturais.', 'Expressões complexas para negócios e academia.', 'Habilidades práticas para trabalho e estudos.', 'Habilidades avançadas para uso profissional.', 'Competência quase nativa em qualquer situação.'],
            textbooks: [['Tae Kim\'s Guide', 'Duolingo'], ['Genki I', 'Anki Core 2k'], ['Genki II', 'NHK Easy Japanese'], ['Tobira Gateway', 'News Web Easy'], ['Tobira Advanced', 'Japanese Novels'], ['New Kanzen Master N1', 'Japanese News'], ['Read Japanese Society', 'Academic Papers']],
            aiPrompt: [
                'Explain the difference between Japanese "wa" and "ga" using simple example sentences a beginner can understand.',
                'Teach me 3 of the most basic and natural ordering phrases to use at restaurants or shops in Japan.',
                'Japanese counters (ippon, ippiki, ichimai) are hard to remember. Teach me the top 5 most used counters and how to remember them.',
                'Create a usage chart for Keigo (Teineigo, Sonkeigo, Kenjougo) showing representative verb changes (iku -> ikimasu, irasshaimasu, mairimasu).',
                'Summarize this recent Japanese news article ([Insert article here]) and rewrite it into simple Japanese a dictionary school student could understand.',
                'Teach me a short script for shadowing practice to improve my pronunciation, along with practice points.',
                'Teach me variations of "Aizuchi" (nodding/responses) Japanese use in conversation ("Hee," "Sou nanda," "Naruhodo") and how to use them.',
            ],
        },
    },
};

