import type { Translations } from './index';

export const zh: Translations = {
    title: '日语学习路线图',
    subtitle: '为您量身定制学习计划',

    currentLevel: '当前水平',
    targetLevel: '目标水平',
    learningPeriod: '学习周期',
    months: '个月',
    monthUnit: '个月',
    beginner: '初学者',
    native: '母语水平',
    purpose: '您学习日语的目的是？',
    createRoadmap: '📚 生成学习路线图',
    selectPurpose: '请选择您的学习目的',

    levelDescriptions: { n5: 'N5水平', n4: 'N4水平', n3: 'N3水平', n2: 'N2水平', n1: 'N1水平', nativeLevel: '母语水平' },

    purposes: {
        anime: { label: '动漫·漫画·游戏', description: '不看字幕也能看懂' },
        friends: { label: '交朋友·找恋人', description: '与日本人建立深厚关系' },
        travel: { label: '享受旅行', description: '自由探索日本各地' },
        culture: { label: '热爱日本文化', description: '礼仪·四季·美食文化' },
        live: { label: '想住在日本', description: '安全舒适的生活' },
        work: { label: '想在日本工作', description: '商务日语需求' },
        beauty: { label: '日语很美', description: '被日语的声音和文字吸引' },
        challenge: { label: '挑战自我', description: '求知欲·自我提升' },
        other: { label: '其他', description: '以上以外的目的' },
    },

    planSummary: '📊 您的学习计划概要',
    totalHours: '总学习时长',
    hoursPerWeek: '小时/周',
    levelUp: '级别提升',
    current: '当前',
    goal: '目标',
    dailyStudy: '每天约',
    hoursUnit: '小时',
    achievable: '的学习即可达成！',

    growthChart: '成长预测图',
    now: '现在',
    monthsLater: '个月后',
    level: '等级',

    lessonDistribution: '推荐课程分配',
    optimizedForYou: '为您的目标量身优化的学习平衡',
    whyThisBalance: '为什么是这个比例？',
    lessonTypes: { grammar: '语法', vocabulary: '词汇', conversation: '会话', reading: '阅读', listening: '听力' },

    monthlyMilestones: '月度里程碑',
    monthN: '月',
    targetLevelLabel: '目标',
    purposeStep: '接近您目标的一步',
    learningContent: '🎯 本月学习重点',
    achievedSkills: '✅ 可达成的技能',
    whyThisOrder: '📌 为什么是这个顺序？',
    recommendedLessons: '推荐课时数',
    textbooksLabel: '推荐教材',
    aiPromptLabel: 'AI角色扮演提示',

    lessonsPerMonth: '次/月',

    roadmapComplete: '🎉 您的专属路线图已完成！',
    ctaDescription: '按照这个计划，一定能达到目标。',
    ctaPeriod: '，用',
    ctaFrom: '从',
    ctaTo: '到',
    startFreeTrial: '✨ 开始免费试听',
    shareThisPlan: '分享这个计划',
    generating: '生成中...',
    trialBooked: '已预约免费试听！',
    imageError: '图片生成失败',
    shareOpened: '已打开分享菜单',
    downloaded: '图片已下载',
    errorOccurred: '发生了错误',

    distributionReasons: {
        anime: {
            beginner: '要理解动漫日语，听力是关键。在培养对口语化表达和独特说法的听辨能力的同时，打好语法和词汇基础。',
            advanced: '除了听力，还需要阅读漫画对话和游戏文本的能力。重点学习口语、俚语、拟声词等教科书上学不到的活日语。',
        },
        friends: {
            beginner: '要与人建立联系，首先需要"说的能力"。即使语法简单，能够进行对话就能加深关系。从表达自己的感受开始吧。',
            advanced: '建立深厚关系需要准确传达细微差别和情感。增加敬语与休闲表达的转换练习，理解日本人"察言观色"的文化。',
        },
        travel: {
            beginner: '旅行日语最需要的是"马上能用的实用短语"。优先掌握车站、餐厅、酒店的词汇和向当地人提问的会话能力。',
            advanced: '锻炼理解地方方言的能力，以及在英语不通的地区的沟通能力。重点提升阅读标识和与当地人聊天的能力。',
        },
        culture: {
            beginner: '深入理解日本文化需要阅读能力。优先记忆礼仪、节日、饮食文化相关的词汇，打好文化阅读的基础。',
            advanced: '古典表达、谚语、书信写法——目标是能品味日本文化的深层内涵。还会加入茶道、花道等专业词汇。',
        },
        live: {
            beginner: '优先掌握日本生活所需的"生存日语"。全面学习市政厅、医院、银行、房产等生活基础设施相关的词汇和会话。',
            advanced: '强化邻里交往、PTA、社区活动等融入日本社会所需的沟通能力。深化正确使用敬语和理解日本独特社会规则。',
        },
        work: {
            beginner: '商务日语的基础是"正确的敬语"。优先掌握邮件写作、电话应对、自我介绍等工作中立即可用的技能。',
            advanced: '磨练在会议发言、演示、谈判、撰写报告等方面获得专业信任的日语能力。加入行业专业术语。',
        },
        beauty: {
            beginner: '要品味美丽的日语，从文字世界开始。仔细学习假名书写顺序、汉字的由来、日语的声音节奏。',
            advanced: '触摸日语之美的精髓——俳句、短歌、诗意表达、四季词汇。还学习书法基础和优美的书信表达。',
        },
        challenge: {
            beginner: '均衡发展所有技能是最高效的方法。融入语言学视角，逻辑性地理解日语结构。',
            advanced: '以JLPT考试为主轴，提升阅读和听力分数。挑战高级语法模式和抽象词汇，满足求知欲。',
        },
        other: {
            beginner: '均衡发展5项技能的综合计划。在免费课程中告诉我您的具体目标，一起量身定制吧！',
            advanced: '全面强化所有技能的综合提升计划。可以根据您的目标进行个性化定制，欢迎在免费课程中咨询！',
        },
    },

    purposeMilestones: {
        anime: [
            '能读懂动漫片头曲歌词 🎵', '能听懂日常番简单的寒暄和台词 👂', '能理解带字幕动漫80%的内容 📺',
            '不看字幕能理解日常番一集的大意 🎉', '不用词典就能玩日语版游戏 🎮', '能直接阅读漫画原版 📖',
            '能理解动漫中复杂的台词和细微差别 ✨',
        ],
        friends: [
            '能自我介绍和聊兴趣爱好 👋', '能在LINE上简单聊天 📱', '能在咖啡厅聊30分钟 ☕',
            '能用日语表达自己的感受和想法 💬', '能听懂笑话，和日本人一起笑 😄', '能谈心事和深层话题 🤝',
            '能用日语吵架和好（真正的朋友！）💪',
        ],
        travel: [
            '能看懂车站标识和告示 🚃', '能在餐厅点餐买单 🍣', '能问路和理解答案 🗺️',
            '能和温泉旅馆工作人员聊天 ♨️', '大致能听懂地方方言 🏔️', '不需日本朋友带路就能独自旅行 🎒',
            '能和当地人打成一片，了解隐藏景点 🌸',
        ],
        culture: [
            '能正确使用基本礼仪和问候 🙇', '能说出日本节日和传统活动的名称 🎎', '能介绍日本料理名称和用餐礼仪 🍱',
            '能理解茶道·花道的基本用语 🍵', '能讨论日本历史和价值观 🏯', '能理解和欣赏俳句·短歌的基础 📝',
            '能像母语者一样深入品味日本文化 🌊',
        ],
        live: [
            '在便利店·超市购物无障碍 🏪', '能独自办理简单的市政手续 📋', '能在医院描述症状 🏥',
            '能和房东·邻居聊家常 🏘️', '能看懂银行·保险·手机合同 📄', '能参加PTA和社区会议 🤝',
            '完全融入日本社会，生活无障碍 🏠',
        ],
        work: [
            '能做基本的商务问候和交换名片 💼', '能写简单的商务邮件 ✉️', '能进行基本的电话应对 📞',
            '能在会议上发表意见 🎤', '能不用翻译直接和客户谈判 🤝', '能用日语做演示报告 📊',
            '能用日语发挥领导力，带领团队 🏆',
        ],
        beauty: [
            '能写出漂亮的平假名和片假名 ✍️', '掌握50个基本汉字的笔顺 📝', '能理解敬语的美 🌸',
            '能用优美的日语写信 ✉️', '尝试写俳句和短歌 🖊️', '能分辨日语微妙的语感差异 ✨',
            '能完全享受日语声音之美 🎵',
        ],
        challenge: [
            '攻克平假名·片假名·基本汉字 🏅', '能做N5级别的练习题 📚', '达到N4考试合格水平 🎯',
            '进入N3考试合格圈 💪', '准备挑战N2考试 🔥', '冲刺N1考试合格 🏆',
            '日语大师！下一个挑战什么语言？🌍',
        ],
        other: [
            '打好扎实的日语基础 📖', '能进行简单的日常对话 💬', '能用日语表达自己的想法 ✍️',
            '能用日语收集信息 🔍', '能就广泛的话题进行对话 🗣️', '能用日语理解专业内容 📊',
            '能自如地运用日语 ✨',
        ],
    },

    monthlyContent: {
        focus: [
            ['平假名·片假名', '基本问候', '数字·时间'],
            ['N5基础语法', '日常词汇200个', '简单造句'],
            ['N4语法句型', '词汇500个', '敬语基础'],
            ['N3语法', '词汇1000个', '中级阅读'],
            ['N3完成〜N2导入', '抽象词汇', '长文阅读'],
            ['N2语法·词汇', '商务日语', '专业阅读'],
            ['N1级别表达', '语感理解', '学术日语'],
        ],
        skills: [
            ['能自我介绍', '能回答简单问题'],
            ['购物基本会话', '能问路'],
            ['能在餐厅点餐', '能写日常邮件'],
            ['能读新闻标题', '能发表意见'],
            ['能理解新闻', '能参加讨论'],
            ['能在会议发言', '能写报告'],
            ['能读论文', '能做演示'],
        ],
        reasons: [
            '掌握日语文字系统和最初沟通所需的基本表达。',
            '掌握实际生活中可用的基本日语，能进行简单的日常会话。',
            '巩固日常生活所需的日语能力，能进行更自然的对话。',
            '作为商务和学术的入门，能理解和使用复杂表达。',
            '磨练实用日语能力，在工作和学习中活用日语。',
            '掌握专业使用日语的高级技能。',
            '目标接近母语水平，在任何场合都能自信使用日语。',
        ],
    },

    purposeMonthlyContent: {
        anime: {
            focus: [
                ['动漫常用寒暄·感叹词', '用片假名读角色名', '平假名·片假名基础'],
                ['动漫经典台词50选', '日常番基本词汇', '台词听力入门'],
                ['日常会话模式', '漫画台词阅读', '拟声词·拟态词'],
                ['口语vs敬语的区分', '游戏UI文本阅读', '动漫情感表达'],
                ['类型专业术语(战斗·科幻)', '攻略网站阅读', '俚语·年轻人用语'],
                ['复杂剧情理解', '轻小说阅读', '方言·角色语'],
                ['文学表达·隐喻', '动漫考察·评论阅读', '母语速度对话理解'],
            ],
            skills: [
                ['能读OP歌词', '能正确发音角色名'],
                ['理解基本感叹词', '能听懂日常番的寒暄'],
                ['能读漫画台词', '能理解带字幕动漫的50%'],
                ['能理解带字幕动漫的80%', '能读RPG基本文本'],
                ['不看字幕能理解大意', '能用日语玩游戏'],
                ['能直接享受漫画原版', '理解伏笔和隐喻'],
                ['完全理解语感', '能用日语讨论作品'],
            ],
            reasons: [
                '享受动漫的第一步是认字。能读OP歌词和角色名会让学习动力持续。',
                '优先学习动漫常用口语表达。接触教科书上没有的活日语来培养实战能力。',
                '用"听+读"双轮驱动。加入漫画台词阅读，高效提升动漫日语能力。',
                '理解口语和正式语的区别，掌握场景切换能力。',
                '掌握类型特有的专业术语和俚语，为无字幕观看架起桥梁。',
                '磨练理解角色特有说话方式、方言以及故事深层结构的能力。',
                '目标是像母语者一样深度品味作品，用日语进行考察讨论。',
            ],
            textbooks: [['Genki I', 'Anime Scripts'], ['Genki II', 'Yotsuba&! (Manga)'], ['Quartet I', 'Slice of Life Anime Scripts'], ['Quartet II', 'Shonen Manga (with Furigana)'], ['Tobira', 'RPG Game Scripts'], ['Shin Kanzen Master N1', 'Light Novels (Easy)'], ['Native Materials', 'Anime Scenarios']],
            aiPrompt: [
                'You are a Japanese teacher who loves anime. Teach me 5 basic greeting phrases a beginner should know, speaking in an energetic tone like Luffy from One Piece.',
                'Explain the nuance and usage of sentence endings like "~daze" and "~kashira" often found in anime, with character dialogue examples.',
                'Analyze the polite yet strong speaking style of Tanjiro from Demon Slayer and create 3 phrases I can use in daily life.',
                'Create 5 "tsundere" lines for an anime character, explaining the grammatical structure and emotional nuance of each.',
                'List 20 important words related to "magic," "equipment," and "adventure" frequent in fantasy RPGs, with example sentences.',
                'Reproduce lines of an anime character using Kyoto dialect (Kansai-ben) and explain the difference from standard Japanese.',
                'Write a philosophical monologue in Japanese like in "Neon Genesis Evangelion" and explain the abstract vocabulary used.',
            ],
        },
        friends: {
            focus: [
                ['自我介绍短语', '休闲问候', '平假名·片假名基础'],
                ['SNS·LINE消息表达', '兴趣爱好词汇', '附和的方式'],
                ['休闲敬语的切换', '情感表达词汇', '邀请·拒绝的方式'],
                ['表达意见', '幽默·玩笑表达', '随意语和敬语的切换'],
                ['倾诉烦恼的表达', '微妙的语感', '理解"察言观色"文化'],
                ['辩论·讨论表达', '深层话题词汇', '方言·地域差异理解'],
                ['讽刺·比喻表达', '理解日本人价值观', '母语速度对话'],
            ],
            skills: [
                ['能自我介绍聊兴趣', '能使用"请多关照"等寒暄'],
                ['能在LINE上简单聊天', '能询问对方的兴趣'],
                ['能持续30分钟闲聊', '能邀请·礼貌拒绝'],
                ['能用日语表达感受', '能讲笑话逗人笑'],
                ['能倾诉烦恼', '能读懂日本人的氛围'],
                ['能深入话题交流', '能用一些方言聊天'],
                ['能吵架又和好', '能与母语者平等对话'],
            ],
            reasons: [
                '交朋友从自我介绍开始。通过兴趣找到共同点，关系就此开始。',
                'SNS是现代交友的基础。掌握LINE上可用的短语。',
                '培养咖啡厅闲聊的持久力。学会自然地邀请和拒绝。',
                '深化关系需要表达感受的能力。加入幽默让对话更有魅力。',
                '理解"察言观色"文化，建立更深层的信任关系。',
                '培养用日语讨论深层话题的能力，达到真正挚友的水平。',
                '完善与母语者自然平等对话的能力。包含文化深层理解。',
            ],
            textbooks: [['Genki I', 'HelloTalk'], ['Genki II', 'LINE Stickers Japanese'], ['Tsunagu Nihongo', 'Tandem'], ['Quartet I', 'Japanese Dramas (Subtitled)'], ['Quartet II', 'Japanese Variety Shows'], ['Tobira', 'Japanese YouTubers'], ['Native Materials', 'Sharehouse Conversations']],
            aiPrompt: [
                'I want to make friends with a Japanese person I just met. Teach me 3 self-introduction phrases that are friendly but not rude.',
                'Create two examples of natural LINE messages to invite someone to dinner: one for a "close friend" and one for "someone I just met."',
                'Teach me the positive and negative nuances of slang words young people use like "maji-de" and "yabai," with example sentences.',
                'List 10 empathetic Japanese phrases (like "That must have been hard") I can use when listening to a friend\'s worries.',
                'Explain what "reading the air" specifically means using a Japanese drinking party situation as an example.',
                'Teach me phrases to exchange opinions on recent news with a friend, like "I think this, but what do you think?"',
                'Teach me some Japanese jokes or "dad jokes" (oyaji gag) and explain why they are funny (wordplay, etc.).',
            ],
        },
        travel: {
            focus: [
                ['车站·机场标识', '数字·时间·星期', '平假名·片假名基础'],
                ['餐厅点餐短语', '酒店办理入住', '问路方式'],
                ['交通换乘', '购物确认价格', '景点提问'],
                ['旅馆礼仪·对话', '地方特产词汇', '天气·身体表达'],
                ['地方方言基础', '历史建筑解说', '与当地人闲聊'],
                ['旅游博客·评论阅读', '电话预约', '紧急情况应对'],
                ['带方言的对话', '旅途中的深度交流', '日本文化解说'],
            ],
            skills: [
                ['能读车站标识', '能听懂数字'],
                ['能在餐厅点餐结账', '能告诉出租车目的地'],
                ['能换乘电车', '能在店里确认价格'],
                ['能享受温泉旅馆的对话', '能描述身体不适'],
                ['大致能听懂方言', '能和当地人闲聊'],
                ['能电话预约', '能看评论规划旅行'],
                ['完全独立自助游', '能从当地人那里了解隐藏景点'],
            ],
            reasons: [
                '旅行从看标识和数字开始。优先掌握出行最低所需。',
                '集中学习"马上能用的实用短语"。在餐厅和酒店不再困扰。',
                '达到能独立出行和购物的水平。重点练习交通和购物实用表达。',
                '用"款待"体验让旅行乐趣加倍。享受旅馆对话和地方美食话题。',
                '学习方言基础，达到能与当地人自然对话的水平。',
                '成为能自己查信息、电话预约的独立旅行者。同时提升阅读力和实践力。',
                '成为能享受日本每个角落的高级旅行者。能与当地人深度交流。',
            ],
            textbooks: [['Phrasebook', 'Google Maps'], ['Travel Japanese', 'Train Timetables'], ['Japan Travel Survival', 'Tabelog'], ['Omotenashi Japanese', 'Ryokan Booking Sites'], ['Dialect Chart', 'Rurubu (Travel Mag)'], ['Jalan (Booking Site)', 'Shinkansen App'], ['National Guides', 'Local Newspapers']],
            aiPrompt: [
                'I am lost at a station in Japan. Teach me a polite phrase to ask station staff "How to get to Shinjuku Station" and "How long it takes."',
                'I entered a restaurant in Japan. Create a phrase to say I have an allergy (e.g., shrimp) and ask for a menu without it.',
                'Explain basic manners I should know when staying at a Ryokan (taking off shoes, hot spring etiquette) in simple Japanese.',
                'Simulate a conversation where I ask a shop clerk "What do you recommend?" and ask for the reason.',
                'I am traveling to Kansai (Osaka/Kyoto). Teach me 5 simple Kansai-ben phrases (like "ookini") to use with shop staff.',
                'I want to book a restaurant by phone. Create a script saying "I would like to make a reservation for 2 people at 7 PM next Saturday."',
                'Think of 3 slightly intellectual mock questions to ask a guide about history when visiting Japanese castles or temples.',
            ],
        },
        culture: {
            focus: [
                ['基本礼仪规范', '和食名称', '平假名·片假名基础'],
                ['年中行事词汇', '饮食文化礼仪', '季节问候'],
                ['茶道·花道基础用语', '和服种类', '传统工艺词汇'],
                ['日本史基本用语', '神道·佛教基础', '和歌鉴赏入门'],
                ['古典文学基础', '谚语·惯用语', '书道基础'],
                ['能·歌舞伎鉴赏', '日本美术解说', '季语与俳句'],
                ['古文阅读', '文化论讨论', '日本美学理解'],
            ],
            skills: [
                ['知道鞠躬的种类', '能解释筷子礼仪'],
                ['能介绍日本节日和活动', '能说明和食用餐礼仪'],
                ['理解茶道流程', '知道和服的场合区别'],
                ['能概述日本历史', '能解释神社和寺庙的区别'],
                ['能在日常中使用谚语', '理解俳句基本规则'],
                ['能鉴赏和解说传统艺能', '能讲述日本美术特征'],
                ['能用原文鉴赏古典文学', '能深入讨论日本文化'],
            ],
            reasons: [
                '日本文化的入口是礼仪和饮食文化。从正确的鞠躬和筷子使用学习"形"。',
                '通过四季行事学习自然观。能使用季节问候会让日本人刮目相看。',
                '接触"道"的文化，加深对"侘寂"的理解。体验的质量显著提升。',
                '学习文化背后的历史和宗教。知识的深化会改变文化体验的质量。',
                '接触古典表达和谚语，品味日语中蕴含的文化智慧。',
                '从传统艺能到美术，达到能鉴赏和解说日本文化精髓的水平。',
                '用原文接触古典，达到与母语者同等深度理解和讨论的水平。',
            ],
            textbooks: [['Intro to Japanese Culture', 'Chopstick Tutorials'], ['Japanese Annual Events', 'Japanese Calendar'], ['Tea Ceremony Intro', 'Traditional Crafts Guide'], ['Japanese History Manga', 'Shrine Test Text'], ['Children\'s Analects', 'Hyakunin Isshu'], ['Kabuki Guide', 'Art History Intro'], ['Tale of Genji (Original/Modern)', 'Fushikaden']],
            aiPrompt: [
                'Explain the difference between Japanese bows (eshaku, keirei, saikeirei) and when to use each.',
                'Teach me Japanese phrases to explain the spiritual meaning of "Itadakimasu" and "Gochisousama" to foreigners.',
                'Briefly explain the Japanese aesthetic of "Wabi-Sabi" in Japanese, using moss or tea bowls as examples.',
                'Compare the differences between shrines and temples (worship methods, what is enshrined) and create a word list for each.',
                'Explain the meaning of the famous proverb "Ishi no ue ni mo sannen" and modern situations where it is used.',
                'I am going to see Kabuki for the first time. Teach me 3 points a beginner should know about unique calls and how to enjoy it.',
                'Explain the modern translation of the opening of "The Tale of Genji" and its unique atmosphere and cultural background.',
            ],
        },
        live: {
            focus: [
                ['便利店·超市标识', '地址的读法', '平假名·片假名基础'],
                ['市政厅手续用语', '银行开户', '医院挂号'],
                ['租房合同用语', '电·气·水', '邮寄·快递'],
                ['町内会词汇', '学校相关用语', '保险·养老金'],
                ['报税基础', '不动产词汇', 'PTA·社区活动'],
                ['法律用语基础', '转职·职业咨询', '育儿支援制度'],
                ['行政手续全般', '市民活动·志愿者', '深入理解日本社会'],
            ],
            skills: [
                ['能在便利店购物', '能写自己的地址'],
                ['能在市政厅办理迁入手续', '能开设银行账户'],
                ['理解租房合同要点', '能咨询公共费用'],
                ['能和邻居闲聊', '能理解学校寄来的信'],
                ['能理解报税文件', '能参加社区活动'],
                ['能理解法律权利', '能用日语求职'],
                ['完全融入日本社会', '能独立办理行政手续'],
            ],
            reasons: [
                '日本生活从便利店和地址开始。优先记住每天使用的词汇。',
                '独自完成生活基础设施手续。市政厅、银行、医院最优先。',
                '稳定住所和生活基础。重点学习合同和生活设施用语。',
                '融入社区的阶段。增加邻里交往和学校相关词汇。',
                '深化长期居住所需的知识。通过税务和社区活动扎根社会。',
                '培养应对职业发展和法律手续的高级日语能力。',
                '目标是完全融入日本社会，在任何场合都能自如生活。',
            ],
            textbooks: [['Japanese for Life', 'Supermarket Flyers'], ['City Hall Guide', 'Medical Japanese'], ['Reading Contracts', 'Rental Sites'], ['PTA Handbook', 'Circular Notices'], ['Tax Return Guide', 'Disaster Maps'], ['Business Law Intro', 'Hello Work Job Slips'], ['Understanding Japanese Society', 'Newspaper Editorials']],
            aiPrompt: [
                'Reproduce a natural interaction at a Japanese convenience store asking to warm up a bento and get chopsticks and a bag.',
                'Simulate a conversation at a hospital reception to convey "I have had a fever since yesterday and my throat hurts."',
                'I am looking for an apartment at a real estate agency. Create a dialogue conveying "Rent under 70,000 yen, within 10 min walk from station."',
                'Garbage sorting rules are confusing. Teach me a conversation to ask a neighbor "Which day should I put out this plastic?"',
                'Write a polite message for a child\'s school contact book saying "He will be absent tomorrow due to a cold."',
                'Explain basic keywords beginners should know about year-end tax adjustment and tax returns in Japan (deductions, withholding, etc.).',
                'Think of a self-introduction speech for a neighborhood association meeting saying "I am still studying Japanese, but nice to meet you."',
            ],
        },
        work: {
            focus: [
                ['商务问候', '名片交换流程', '平假名·片假名基础'],
                ['商务邮件格式', '接电话方式', '自我介绍(公司版)'],
                ['会议记录写法', '报联商文化', '敬语体系'],
                ['演示资料制作', '会议发言模式', '谈判表达'],
                ['合同阅读', '报告·文书', '公司内部政治词汇'],
                ['经营战略词汇', 'IR·财务用语', '领导力表达'],
                ['高管级日语', 'M&A·法务用语', '演讲·讲座'],
            ],
            skills: [
                ['能交换名片', '能在商务场合正确问候'],
                ['能写模板商务邮件', '能转接电话'],
                ['能写会议记录', '能向上司报联商'],
                ['能在会议发表意见', '能制作演示资料'],
                ['能理解合同', '能用日语写报告'],
                ['能参加经营会议', '能用日语领导团队'],
                ['能向高管做演示', '能用日语处理所有业务'],
            ],
            reasons: [
                '商务第一印象由问候和名片交换决定。首先掌握正确的形式。',
                '邮件和电话是日常业务基础。掌握模板表达成为即战力。',
                '"报联商"是日本企业的命脉。巩固与上司同事的沟通基础。',
                '强化输出能力。通过会议发言和演示展现存在感。',
                '培养准确读写文件的能力，赢得专业信任。',
                '目标管理层水平的日语能力，能进行团队管理和战略讨论。',
                '最高水平的商务日语，适用于高管角色。任何场合都能自信应对。',
            ],
            textbooks: [['Keigo Training', 'Business Card Manners'], ['Business Writing', 'Phone Manuals'], ['Manga Ho-Ren-So', 'Meeting Japanese'], ['Presentation Japanese', 'Logical Speaking'], ['Business Contracts', 'Internal Reports'], ['Nikkei Business', 'Drucker (JP Ver)'], ['HBR Japan', 'Corporate Law']],
            aiPrompt: [
                'Teach me the correct step-by-step procedure for exchanging business cards in Japan, with dialogue.',
                'Create an example of a polite business email asking a client "I would like to change the meeting date."',
                'Create an appropriate conversation flow for reporting progress to a boss (Ho-Ren-So) starting with "Actually, there is a problem..."',
                'Teach me 5 variations of phrases to point out concerns in a meeting while agreeing, like "I agree basically, but just one point..."',
                'Explain the usage of "Osewa ni natte orimasu," "Otsukaresama desu," and "Gokurosama desu" and their NG scenes.',
                'Create an opening speech for a business presentation that apologizes for a project failure but proposes improvements sincerely.',
                'Teach me ideal praise words a Japanese boss uses to motivate subordinates (like "Sasuga da ne, kitai ijo da yo").',
            ],
        },
        beauty: {
            focus: [
                ['优美的平假名笔顺', '片假名的由来', '日语声音的特征'],
                ['50个基本汉字笔顺', '音读·训读的区别', '拟声词之美'],
                ['汉字偏旁和含义', '优美的手写练习', '季节词汇'],
                ['敬语的体系与美', '写信方式', '颜色的和名'],
                ['俳句基本规则', '和歌鉴赏', '书道基础'],
                ['短歌·诗歌创作', '古语之美', '日语的韵律'],
                ['文学表达的完全理解', '书道的极致', '日语美学的体现'],
            ],
            skills: [
                ['能优美地书写平假名', '能体感日语元音的韵味'],
                ['能正确笔顺写50个汉字', '能解释汉字的由来'],
                ['能从偏旁推测汉字含义', '能写季节信件'],
                ['能优美地使用敬语', '能在信笺上写美丽的信'],
                ['能吟咏俳句', '能理解和歌的意境'],
                ['能创作短歌', '能品味古语的韵味'],
                ['完全理解日语声音之美', '达到书道的极致'],
            ],
            reasons: [
                '日语之美的原点是文字的形态和声音的韵味。一笔一画认真学习培养美感。',
                '了解汉字的由来，会发现每个字所蕴含的深层含义。书写的快乐加倍。',
                '系统理解汉字和学习季节美词。珍视手写温度的阶段。',
                '敬语是日语之美的结晶。能够区分使用就能体感到深奥之处。',
                '接触俳句和和歌，体验凝缩在17音·31音中的日语之美。',
                '进入创作的乐趣。接触古语所特有的美和深度。',
                '品味尽日语的声·形·义所有的美的最终阶段。',
            ],
            textbooks: [['Calligraphy Practice', 'Hiragana Chart'], ['Kanji Origins', 'Beautiful Words Dict'], ['Japanese Colors', 'Seasonal Words'], ['Aesthetics of Keigo', 'Letter Writing'], ['Haiku Almanac', 'Manyoshu Intro'], ['Kokin Wakashu', 'Tale of the Bamboo Cutter'], ['Tale of Genji', 'Pillow Book']],
            aiPrompt: [
                'Teach me tips to write hiragana "a" and "no" beautifully and balanced, relating them to shapes (triangle, circle).',
                'Introduce 5 beautiful Japanese words related to "rain" (samidare, shigure, etc.) and explain the scenery of each.',
                'Teach me seasonal greetings (jikou no aisatsu) used in letter openings like "Haikei, sakura no kisetsu..." for each of the 4 seasons.',
                'Introduce some Japanese expressions that convey love indirectly and elegantly, like "The moon is beautiful, isn\'t it?"',
                'I want to make Haiku. Create and explain 3 beginner examples using "Summer" and "Sea" as themes.',
                'Select 10 Japanese onomatopoeia with particularly beautiful sounds (like "shitoshito," "kirakira").',
                'Select one famous romantic poem from Hyakunin Isshu and explain its meaning and background in a modern way.',
            ],
        },
        challenge: {
            focus: [
                ['平假名·片假名完全记忆', '基本汉字100个', '日语句子结构'],
                ['N5语法全学', '词汇300个', 'N5模拟考试对策'],
                ['N4语法精通', '词汇800个', 'N4模拟考试对策'],
                ['N3语法体系', '词汇1500个', '中级阅读训练'],
                ['N2语法模式', '词汇3000个', '长文阅读·听力'],
                ['N1语法·词汇', '抽象表达', 'N1实战演练'],
                ['超高级表达', '学术论文阅读', '母语水平达成'],
            ],
            skills: [
                ['平假名·片假名完全掌握', '能读写100个基本汉字'],
                ['N5模拟考达到合格线', '能回答基本问题'],
                ['达到N4水平', '能进行日常会话'],
                ['进入N3合格圈', '能读新闻标题'],
                ['能解N2级别的题', '能理解新闻'],
                ['冲刺N1合格水平', '商务场合也能应对'],
                ['日语大师', '任何场合都能自如运用'],
            ],
            reasons: [
                '挑战从基础开始。彻底理解文字和句子结构，打下坚实基础。',
                '以N5完全攻略为目标，系统积累语法和词汇。用模拟考确认实力。',
                '目标达到N4水平，扩展语法模式同时强化日常会话力。',
                'N3是通往中级的登龙门。整理语法体系，快速提升阅读理解力。',
                'N2是实用水平的证明。战略性地提升长文阅读和听力分数。',
                'N1是日语学习者的最高峰。挑战抽象词汇和复杂语法模式。',
                '超越N1达到真正的日语大师。在学术·商务·日常任何场合都自如。',
            ],
            textbooks: [['Genki I', 'Kanji Master N5'], ['Shin Kanzen Master N5', 'JLPT N5 Prep'], ['Shin Kanzen Master N4', 'Sou Matome N4'], ['Shin Kanzen Master N3', 'Sou Matome N3'], ['Shin Kanzen Master N2', 'Sou Matome N2'], ['Shin Kanzen Master N1', 'Sou Matome N1'], ['Advanced Reading', 'Learn with News']],
            aiPrompt: [
                'Create 10 conjugation practice questions for N5 essential verbs (iku, taberu, miru) covering present, past, and negative forms.',
                'Explain the difference between N4 grammar "~te wa ikemasen" (prohibition) and "~nakutemo ii desu" (not necessary) with 5 practice questions.',
                'Teach me techniques for "Task-Based Understanding" questions often found in N3 listening tests (reading questions first, taking notes, etc.).',
                'I run out of time in N2 reading. Explain tips for speed reading and how to focus on conjunctions (shikashi, tsumari).',
                'Propose some mnemonics or story memory methods to remember difficult N1 kanji (like "chucho," "kairi").',
                'Give me advice on what to do in the week before the JLPT (daily rhythm, review priorities).',
                'Correct my short essay ([Insert text here]) and rewrite it into more natural, advanced Japanese expressions.',
            ],
        },
        other: {
            focus: [
                ['平假名·片假名', '基本问候', '数字·时间'],
                ['N5基础语法', '日常词汇200个', '简单造句'],
                ['N4语法句型', '词汇500个', '敬语基础'],
                ['N3语法', '词汇1000个', '中级阅读'],
                ['N3完成〜N2导入', '抽象词汇', '长文阅读'],
                ['N2语法·词汇', '商务日语', '专业阅读'],
                ['N1级别表达', '语感理解', '学术日语'],
            ],
            skills: [
                ['能自我介绍', '能回答简单问题'],
                ['购物基本会话', '能问路'],
                ['能在餐厅点餐', '能写日常邮件'],
                ['能读新闻标题', '能发表意见'],
                ['能理解新闻', '能参加讨论'],
                ['能在会议发言', '能写报告'],
                ['能读论文', '能做演示'],
            ],
            reasons: [
                '掌握日语文字系统和最初沟通所需的基本表达。',
                '掌握实际生活中可用的基本日语，能进行简单的日常会话。',
                '巩固日常生活所需的日语能力，能进行更自然的对话。',
                '作为商务和学术的入门，能理解和使用复杂表达。',
                '磨练实用日语能力，在工作和学习中活用日语。',
                '掌握专业使用日语的高级技能。',
                '目标接近母语水平，在任何场合都能自信使用日语。',
            ],
            textbooks: [['Tae Kim\'s Guide', 'Duolingo'], ['Genki I', 'Anki Core 2k'], ['Genki II', 'NHK Easy Japanese'], ['Tobira Gateway', 'News Web Easy'], ['Tobira Advanced', 'Japanese Novels'], ['New Kanzen Master N1', 'Japanese News'], ['Read Japanese Society', 'Academic Papers']],
            aiPrompt: [
                'Explain the difference between Japanese "wa" and "ga" using simple example sentences a beginner can understand.',
                'Teach me 3 of the most basic and natural ordering phrases to use at restaurants or shops in Japan.',
                'Japanese counters (ippon, ippiki, ichimai) are hard to remember. Teach me the top 5 most used counters and how to remember them.',
                'Create a usage chart for Keigo (Teineigo, Sonkeigo, Kenjougo) showing representative verb changes (iku -> ikimasu, irasshaimasu, mairimasu).',
                'Summarize this recent Japanese news article ([Insert article here]) and rewrite it into simple Japanese a dictionary school student could understand.',
                'Teach me a short script for shadowing practice to improve my pronunciation, along with practice points.',
                'Teach me variations of "Aizuchi" (nodding/responses) Japanese use in conversation ("Hee," "Sou nanda," "Naruhodo") and how to use them.',
            ],
        },
    },
};

